AcademySoftwareFoundation/OpenShadingLanguage

src/liboslcomp/oslcomp.cpp
src/oslc/oslcmain.cpp

This is the way it had always been, but I broke it with the compile_buffer patch. That caused problems for situations where other headers in that directory were assumed to be includable without having to separately specify the path on the command line.

oslcomp fix: add directory holding stdosl.h to the include path.

---

CHANGES
CMakeLists.txt
src/doc/languagespec.tex
src/liboslcomp/ast.h
src/liboslcomp/codegen.cpp
src/liboslcomp/oslgram.y
src/liboslcomp/typecheck.cpp
testsuite/oslc-comma/comma.osl
testsuite/oslc-comma/ref/out.txt
testsuite/oslc-comma/run.py

Recently noticed that the "comma operator" does not work as expected. You can see this with a common idiom of incrementing multiple counters in a for loop, like this:
for (int i=0; i < j; ++i, a *= 2) ...
It's not specific to 'for', of course; in general the comma operator should work in the same places it would in C. To do this properly, we need to split the grammatical 'expression' into the simple kind and a compound_expression, and also add a new AST node for the comma operator (because it's special: a,b has the type and value of b).

oslc fix: allow comma operator

---

CMakeLists.txt
src/liboslcomp/ast.h
src/liboslcomp/codegen.cpp
testsuite/struct-in-struct-init/ref/out.txt
testsuite/struct-in-struct-init/run.py
testsuite/struct-in-struct-init/test.osl

There was a case involving this kind of setup:
struct InnerStruct { ...fields... };
struct OuterStruct { InnerStruct inner; }
OuterStruct x = ...;
OuterStruct y = x;    <----- THIS
where incorrect oso code would be generated, to wit: directly assigning x.inner to y.inner (illegal!), instead of assigning the individual fields of x.inner to the corresponding field of y.inner.
We'd solved this a while back for ordinary variable assignment, with the solution implemented in ASTassign_expression::codegen_assign_struct, which needed to operate recursively to handle structs-within-structs as far down as necessary. But the way initialization assignments like the above were handled by ASTvariable_declaration was naive and botched it for nested structs.
This patch moves …

Bug fix in variable declaration + assignment of nested structs

---

src/include/OSL/rendererservices.h
src/liboslexec/constfold.cpp
src/liboslexec/rendservices.cpp

gettextureinfo constant fold fix: needs to call RS::get_texture_info(), but was incorrectly bypassing that straight to texturesys()->get_texture_info(). That's bad for a renderer that has a custom RS::get_texture_info and only a "mock" TextureSystem.

gettextureinfo constant fold fix: needs to call RS::get_texture_info

---

src/liboslcomp/oslcomp.cpp
src/liboslquery/oslquery.cpp
testsuite/oslinfo-metadata/metadata.osl
testsuite/oslinfo-metadata/ref/out.txt

Contributed by Steve Agland from Animal Logic. Steve sent this to us quite a while back, there was some delay in working out the CLA, and when it was finally done, LG dropped the ball and took embarrassingly long to integrate the patch.  So sorry for the delay, Steve.

Enable oslc output of shader-wide metadata, and OSLQuery reading it properly

---

src/liboslexec/shadingsys.cpp

Optimize level 0 seems like it should do very little optimization, and that counts instance merging.

Only merge instances when optimize level is at least 1

---

src/liboslexec/instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

1. When deciding whether an output param is a renderer output, we should have checked if the renderer output list contained the layer-specified output name, as well as the unqualified (any layer) name. We did it right for the group-specific output list, but not for the renderer-wide output list.
2. Don't consider a layer unused if its outputs are renderer outputs. We were optimizing away layers, or skipping them during "lazy" evaluation, if they weren't setting any "globals" and didn't have any downstream connections. But if it sets a renderer output, it needs to be run unconditionally.

Fix two bugs related to renderer outputs

---

src/liboslexec/llvm_gen.cpp

This was affecting shaders using the "averagecolor" attribute and corrupting
computations later on.

Clear derivs in gettextureinfo output

---

CMakeLists.txt
src/include/OSL/oslexec.h
src/liboslexec/instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp
testsuite/layers-Ciassign/ref/out.txt
testsuite/mergeinstances-nouserdata/a.osl
testsuite/mergeinstances-nouserdata/b.osl
testsuite/mergeinstances-nouserdata/ref/out.txt
testsuite/mergeinstances-nouserdata/run.py

The existing opt_merge_instances, when on (default), will merge shader instances within a group when they are completely isomorphic, having the same code, symbols, instance parameter values, and upstream connections. When two matching instances are found, they are combined into one.
However... we have discovered an interesting edge case, wherein the two retrieve userdata (geometry-bound parameters) and even though they are both retrieving what appears to be the same-named userdata, the particular renderer (not mine!) allows a level of flexibility where the renderer can bind different userdata ("hook the 's1' interpolated variable to this instance's 's' input parameter"), and that happens in a way where OSL per se doesn't really know that it's been bound to a different name than the name …

New option: opt_merge_instances_with_userdata

---

src/liboslexec/oslexec_pvt.h

I'm guessing the default value is preventing the compiler from detecting this name mismatch?

Small spelling mistake - missing 't' in alignment

---

src/include/OSL/rendererservices.h
src/testrender/simplerend.cpp
src/testrender/simplerend.h
src/testshade/simplerend.cpp
src/testshade/simplerend.h

This is just a placeholder for future functionality. I wanted to get the method into the class before the next stable release branch is made (hopefully soon).

Add RendererServices::supports()

---

src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h

RuntimeOptimizer::optimize_instance() was getting really big and unwieldy.  This refactor, which just moves code without changing any behavior, breaks it into two pieces: (1) optimize_instance still loops over passes, and does per-pass optimizations and other housekeeping; (2) optimize_ops does all the per-op optimizations, over a range of ops.  So the guts of the loop over ops has just been broken out into a separate function.
The added benefit, which will be apparent in a future review of something I'm working on, is that there is utility in calling the optimize_ops over shorter ranges of ops, for particular purposes. Stay tuned. I wanted to do the code movement as a separate review because once I start changing it, it will be hard to follow the diffs if it moves around in the same …

Refactor optimize_instance

---

src/include/OSL/oslexec.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

ShadingSystem: add a new version of execute() that takes a ShadingContext *, and if NULL, execute() will get and release the context for you. Easy.
This is just a convenience function, but makes it simpler to execute a shader without the app needing to keep track of shading context ownership itself. It's only a minuscule amount more expensive than when the app fully tracks it.

ShadingSystem: add a new version of execute() that takes a ShadingContext *

---

src/liboslexec/context.cpp
src/liboslexec/oslexec_pvt.h

For short shaders that don't use texture at all (and therefore don't
need the thread-specific pointer), this was causing undue overhead.

Have the context lazily grab texture_thread_info.

---

src/liboslexec/noiseimpl.h

This is related to this OIIO PR: https://github.com/OpenImageIO/oiio/pull/1079
This OSL-side patch simply makes OSL work whether or not the new OIIO patch is applied. Works before, works after.

Use rotl32 from fmath.h for sufficiently new OIIO

---

src/include/OSL/oslexec.h
src/liboslexec/context.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

More texture per-thread tweaking: allow get_context() to supply aTextureSystem::Perthread* to use for that context.
This is helpful for renderers that want to save a bit of time by allocating such things up front.

Allow get_context() to supply a TextureSystem::Perthread* to use for that context.

---

CHANGES
CMakeLists.txt
src/include/osl_pvt.h
src/liboslcomp/typecheck.cpp
src/liboslexec/instance.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/loadshader.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/osogram.y
src/liboslexec/osoreader.cpp
src/liboslexec/typespec.cpp
src/testshade/testshade.cpp
testsuite/vararray-connect/ref/out.txt
testsuite/vararray-connect/run.py
testsuite/vararray-connect/test.osl
testsuite/vararray-connect/upstream.osl
testsuite/vararray-param/ref/out.txt
testsuite/vararray-param/run.py
testsuite/vararray-param/test.osl

You could previously declare OSL functions that have parameters that are arrays of unspecified length (like 'float foo[]'), but there was not an effective way to make shader parameters like that.
This patch, mostly the work of Max Liani from Animal Logic (with a little touch-up from LG), more or less fully enables shader parameters that are arrays of unspecified length. When an instance value is provided, which must itself be of definite length, it fixes the length of the shader parameter. Or, within a shader group, when an upstream shader's output parameter (of definite length) is connected to a downstream shader's parameter of unspecified length, it fixes the length. This provides some interesting new flexibility to write shaders that take arrays as parameters, without knowing the …

Shader params that are arrays of unspecified length

---

src/liboslcomp/typecheck.cpp
src/liboslexec/llvm_gen.cpp

I'm really not sure why this didn't ever come up earlier, but I found a minor bug in codegen for closure construction, wherein testing whether the passed argument matches the prototype used a more exact test than was necessary (== versus equivalent()), and if a vector and color temporary were coalesced in just the right way, it would say it was a bad argument type passed.
Also improved a nearby error message.
Also, while inspecting diffs of recent checkins to see what might have exposed this problem, noticed that the recent array checkin introduced an off-by-one error in oslc argument checking. Unrelated to this issue, and thus far unreported! But fixing it anyway.

Bug fix with closure code generation

---

src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp

Fix subtle optimizer bug -- under some very specific circumstances, an output parameter whose default value comes from "init ops" but which actually got an instance value, and was also connected to a downstream layer, could be eliminated but incorrectly, by passing along to the downstream shader the constant value it would have been assigned by default, rather than the constant instance value.
In addition to the bug fix itself, I also added some additional debugging aids.

Fix subtle optimizer bug

---

src/liboslexec/runtimeoptimize.cpp

Recently, in #485 I fixed a bug in outparam_assign_elision(), which tries to notice output params whose values are assigned only once in the shader, to a constant value, and change it to eliminate the assignment but simply have an instance value with that value. That bug fix was realizing that if the op in question is an "init op" for the param (ops needed to establish a default that can't be statically constant), and the param has an instance value, then the init ops are moot, won't come into play, so it's wrong to redundantly turn it into an instance valued based on that assignment (in effect, it's incorrectly changing the instance value it will get).
OK, so the present bug is in the same spot and just an extension of this. Not only if it's got an instance value, but also if it's got an …

optimizer bug fix

---

src/include/osl_pvt.h
src/liboslexec/instance.cpp
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp

When two instances were being examined for possible merging, and
* a parameter was not actually used anywhere inside the shader at all
* but one or both instances have that parameter connected to downstream nodes
* the two nodes have difference instance values for the parameter
(Luckily, this is a very weird, unusual, particular circumstance.)
We weren't quite careful enough to not merge in those circumstances.
Tighten up some of the tests and preconditions for merging.

Fix bug with merging of instances

---

src/include/OSL/oslexec.h
src/liboslexec/context.cpp
src/liboslexec/instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

ShadingSystem::get_symbol() is what renderers call to retrieve the
memory location of renderer outputs, immediately after executing a
shader.  But it was more expensive than we ideally wanted.  Most of the
expense was in the name lookups, so we observe that if we can separate
the name resolution (expensive, but once per group) from the retrieval
of the address (once per shader execution, but cheap), we give renderers
a path to reduce per-shade overhead expense.
So we break it into two new methods: find_symbol(), which given a group
and the names will return an opaque pointer for the symbol that can be
reused for the lifetime of the shader group; and
symbol_address(ctx,sym), which retrieves the actual memory address of
the symbol for a particular shader execution of a context …

Refactor methods to retrieve output symbol locations.

---

src/liboslexec/runtimeoptimize.cpp

It was really implemented as if it were "unread AT OR after". It's used to determine whether it's safe to elide assignments to variables that aren't subsequently use. But sometimes the assignment is a function where the variable assigned to is also one of the arguments. For example,
x = func(x,y)
x is read on that op, but not AFTER. But because of how the unread_after also discounted elision if used on that op, it was less aggressive than it could have been in eliminating statements like this.
I'm seeing around a 1/2 - 1% speedup on production frames because of this, with a similar decrease in post-optimized symbols and instructions. Not dramatic, but every little bit counts.

Optimization: Be less conservative in implementation of unread_after().

---

CMakeLists.txt
src/include/osl_pvt.h
src/liboslcomp/ast.cpp
src/liboslcomp/codegen.cpp
src/liboslcomp/oslgram.y
src/liboslcomp/symtab.cpp
src/liboslcomp/typecheck.cpp
src/liboslexec/backendllvm.cpp
src/liboslexec/constfold.cpp
src/liboslexec/instance.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/loadshader.cpp
src/liboslexec/master.cpp
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp
src/liboslexec/typespec.cpp
src/liboslquery/oslquery.cpp
src/oslinfo/oslinfo.cpp
testsuite/oslc-err-outputparamvararray/ref/out.txt
testsuite/oslc-err-outputparamvararray/run.py
testsuite/oslc-err-outputparamvararray/test.osl
testsuite/oslinfo-arrayparams/arrayparams.osl
testsuite/oslinfo-arrayparams/ref/out.txt
testsuite/oslinfo-arrayparams/run.py
testsuite/vararray-connect/ref/out.txt
testsuite/vararray-default/ref/out.txt
testsuite/vararray-default/run.py
testsuite/vararray-default/test.osl
testsuite/vararray-param/ref/out.txt

This is a proposed modification of #496 keeps track of the number of initializers in the Symbol structure itself, without the need for abusing TypeDesc or requiring any changes on the OIIO size.
(Aside: I wish GitHub had a way to propose modifications to PRs, on the PR itself. Or some kind of "multiple contributor PR" where people other than the original author can amend the patch. But it doesn't.)
If you guys like this, I will squash it into a single commit before merging. But I kept it separate for review so it's easy to see exactly what I changed compared to Daniel.

Daniel Heckenberg + LG = vararray defaults without OIIO changes

---

CHANGES
src/liboslcomp/oslcomp.cpp

For some really complex shaders, we profiled track_variable_lifetimes to be an important bottleneck in shader runtime optimization time.
Part of this function was an outer loop over every instruction, and any time it found a loop instruction, it would then loop over EVERY symbol, looking for symbols that were modified within the loop body, and marking the symbol in such a way as to expand its lifetime to fill the whole loop (because its value may be needed the next iteration).
This refactor still loops over all instructions, but we use a simple stack to keep track of any nested loops we are a part of. For each instruction, it looks at just the symbols that are arguments of that instruction, and for those, extends its lifetime to fill any loops the instruction is part of.
This changes the …

Refactor of track_variable_lifetimes for vastly improved performance

---

src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h

For a very long time now, we have not used the 'useparam' stuff on the oslc compiler side at all, instead doing it all as part of the runtime compilation and JIT. So remove the remaining clutter from liboslcomp.

Remove unused insert_useparam and add_useparam from oslcomp

---

src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h

A big part of the runtime optimizer's housekeeping is keeping track of which symbols alias to which other symbols. For example if you have 'a=b' it will actually remember that they are the same, so then if you have c=a-b, it will understand this means c==0. Of course, it also clears it if you reassign something else to a. And if you get to the end of a basic block, it clears them all, since control could flow in from somewhere else with different assignments.  The basics of this was tracked by an alias array, length was the number of symbols, each element says which symbol this symbol is aliased to, if any, or -1 if it doesn't alias anything else.  And a common operation is to say "forget all the aliases", which is really filling the whole array with -1's.
Profiling on some enormous …

Dramatically speed up runtime optimization with flat_map

---

src/liboslexec/loadshader.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

Profiling was showing OSOReaderToMaster::instruction_arg as a hot spot when loading large shaders. This is because of a linear search to find symbol index from its name. I'm sure this made sense for short test shaders I was using when first bringing OSL online, but now we have immense shaders. Switch to a hash map for these lookups.
This results in over a 3x speedup of shader load time (which now is reported in the stats), on a scene with our production shaders.

Big speedup loading large shaders -- look up symbols with hashmap, not linear search

---

src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp

When a shader needs the value of a connected parameter, it runs the upstream layer it's connected to, if it hasn't been run already.  But, to keep a bzillion of these checks from occurring needlessly, it also tries to keep track (when building the LLVM ops) of which ones certainly have already been called, so that it isn't generating code to constantly check it at runtime. We were very subtly getting this wrong.  It's crucial not to do this for things pulled by init ops. They are inherently conditional, and also the m_layers_already_run set hadn't been cleared yet when they were run! So certain particular constructs of layer connections and init ops could result in it incorrectly skipping the execution of a layer by thinking it had already been run, even though it hadn't.

Critical bug fix -- error in keeping track of which layers have been run

---

src/liboslexec/instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp

The usual easy checks for if something is unused -- no code and no symbols -- aren't reliable in this case.

Keep track of layers that are the unused duplicate after an instance merge

---

src/include/osl_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h

Minor refactor of runtime optimizer internals. This encapsulates some code that's repeated a few times into a single add_symbol() call. Also, that call makes sure to temporarily mark a newly added symbol as used potentially at any time so any choices based on lifetime analysis will be extra conservative until the next time that lifetimes for all symbols are re-analyzed (which happens with each optimization pass over the code).

Refactor adding symbols to be more clear and simplify

---

src/liboslexec/builtindecl.h
src/liboslexec/llvm_instance.cpp
src/liboslexec/shadingsys.cpp
testsuite/debug-uninit/ref/out.txt

Found a source of "false positives" -- we shouldn't do a check for
uninitialized values of the arguments to a "useparam" pseudoinstruction,
since by definition the parameters named may be uninitialized before the
useparam action itself copies the values from connected layers.
In the process, beef up the uninitialized value error message to point
not only to the OSL source file and line, but also to the specific group
and layer, and (mainly for me in debugging the feature) which
instruction it is.

Improve uninitialized value detection mode ("debug_uninit")

---

src/testrender/testrender.cpp
src/testshade/testshade.cpp

--stats if applicable, prints statistics about the program inputs.
--runstats prints runtime statistics about the operation of the program itself (timing, memory, etc.)
oslinfo (and oiiotool) used this convention already, but testrender and testshade used --stats to print run statistics.

Harmonize the way all binaries use --stats versus --runstats

---

CMakeLists.txt
src/liboslexec/rendservices.cpp
src/liboslexec/shadingsys.cpp

For renderers that supply their own TextureSystem class, this will cause an assertion if a TS isn't either passed to the ShadingSystem constructor or returned by RendererServices::texturesys(), and definitely won't construct a default OIIO TextureSystem on its own.
This is an unusual need (though not unreasonable), so if you don't know why this is useful, don't worry, it's not meant for you.

CMake option to disallow creation of OIIO::TextureSystem.

---

Makefile
site/pixar/Makefile-bits
src/oslc/oslcmain.cpp

Just like we have for site/spi (and I'm happy to do for other sites that want to enshrine their weird build flags in the trunk so they don't need customizations on their end).
I'm only guessing about the contents, but with this structure in place, they can give it any additional customization it needs.
I also made a second search path for stdosl.h for where I know PRMan wants to look.
Note that this depends on a couple of the recently added build options.

Give Pixar a site file

---

CMakeLists.txt

Often when debugging, I comment things out, then get frustrated by clang warnings that a static function or local variable (whose use was commented out) is no longer used and breaks the build.
So at least turning off these warnings when in debug mode on clang.

In debug mode, don't warn about unused functions or variables with clang

---

testsuite/runtest.py

If OPENIMAGEIOHOME is not found in the environment, assume the binaries we need are in the execution search path.
This only affects running the testsuite (which occasionally needs maketx or oiiotool). It has nothing to do with building and linking.

testsuite - improve the way we find OIIO

---

src/include/OSL/oslexec.h
src/liboslexec/shadingsys.cpp

This can occasionally be handy to make it happen at a particular time, and not necessarily only as a side effect of shading.

Add ShadingSystem::optimize_group to force a group to optimize/JIT

---

src/include/OSL/rendererservices.h
src/liboslexec/rendservices.cpp

I'm starting to imagine reasons for an app to have multiple "renderers"
using different RendererServices subclasses. Each one should be allowed
to hold a distinct TextureSystem, which it couldn't before. The only
obvious way to do this is holding the pointer in the RS object itself.

Make RendererServices hold a TextureSystem*.

---

CMakeLists.txt
src/liboslexec/shadingsys.cpp
testsuite/vararray-deserialize/ref/out.txt
testsuite/vararray-deserialize/run.py
testsuite/vararray-deserialize/serial.oslgroup
testsuite/vararray-deserialize/test.osl

When an unsized array parameter comes in (like: param int[] 1 2 3 4) we
don't actually know the parameter type yet, because the shader itself
hasn't been declared. So, first of all, handle the "int[]" part without
ending up with an uninitialized length, duh. But then, we can't
preallocate at that point, because we don't know how many ints there
will be, so grow the array as we read them, and then reset the type to
the right length that we actually saw.

Fix bugs when deserializing shader group strings with unsized arrays.

---

src/liboslexec/builtindecl.h
src/liboslexec/constfold.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
src/liboslexec/shadingsys.cpp
testsuite/debug-uninit/ref/out-opt2.txt
testsuite/debug-uninit/ref/out.txt

Undetected for quite some time, it seems that the constant folding of format() involved inserting an op, and the insert_code() call omitted a vital parameter that would instruct it to recompute the read/write ranges of symbols after the insertion. This could lead to a cascade of bad things later, and in particular could cause it to make mistakes where a symbol assignment might be removed if it (incorrectly) thought it would not be subsequently read.
It must have needed a very precise set of circumstances -- we've had this bug in the code for over a year, it never was reported as a bug, and we only discovered it when for other reasons we resurrected a scene and a version of our shader library from a couple years ago and found it had some weird errors. Somehow none of our current shaders …

Fix subtle optimizer bug with constant folding of format()

---

src/liboslexec/instance.cpp

If asked the serialize the group before it's been optimized & jitted,
information about the concrete size of instance values of "unsized" arrays
will be in the SymOverrideInfo, not yet copied to the instance's copy
of the Symbol itself. So get it from the right place.

Bug fix serializing shader groups with "unsized arrays"

---

src/osl.imageio/oslinput.cpp

It is intended, at least for now, that the current OSL trunk should build against OIIO 1.5 or 1.6.

Fix OIIO 1.5 compatibility -- didn't mean to break it.

---

CMakeLists.txt
src/liboslexec/llvm_instance.cpp
testsuite/layers-nonlazycopy/a.osl
testsuite/layers-nonlazycopy/b.osl
testsuite/layers-nonlazycopy/ref/out.txt
testsuite/layers-nonlazycopy/run.py

Subtlety: When generating code for the "group entry" (last) layer, which
is also responsible for executing all earlier layers that are marked as
needing to run unconditionally (non-lazily), it is important that the
group entry layer initialize its input parameters BEFORE it runs the
earlier unconditional layers and copies the upstream outputs to its own
inputs. Of course. Because, duh, if it first runs the upstream layer and
copies the upsteam outputs to its own input, THEN zeroes out or
otherwise initializes its inputs, it will overwrite the value set by the
earlier layer.

Bug fix with unconditional running of earlier layers.

---

src/liboslexec/oslexec_pvt.h

This code triggers a range checking assert in our vs2012 debug builds, also potential undefined behaviour.

Fix for range checking asserts in vs2012 debug builds

---

Makefile

Ninja's command line arguments are different than make. If you use ninja, you need to pass -v to see fully verbose compilation commands as it goes.

Make VERBOSE=1 really be verbose with Ninja

---

src/liboslexec/backendllvm.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

I did this to help me debug something (which turned out not to be a bug), but it's still a useful item to keep in the stats output.

Keep and report stats on texture calls and handles

---

src/liboslexec/shadingsys.cpp

I wrote a group spec by hand and accidentally quoted the shader name. Took me a couple awkward minutes to figure out the error message I was getting.

Group deserialization: allow quoting of shader and layer names

---

CMakeLists.txt
src/include/OSL/oslexec.h
src/include/osl_pvt.h
src/liboslexec/backendllvm.h
src/liboslexec/context.cpp
src/liboslexec/instance.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp
src/testshade/testshade.cpp
testsuite/layers-entry/node.osl
testsuite/layers-entry/ref/out.txt
testsuite/layers-entry/run.py

Execution order refactor, and per-layer explicit execution order
Let's review what happens when you call
shadingsys->execute (contextptr, shadergroup, shaderglobals);
This executes the given shader group on the context, with a specific set of shader globals. The group may be composed of many individual layers (shader nodes), and execution proceeds from first to last layer, executing those that must be run unconditionally and skipping those that can be run lazily. Of course, if a layer executes, it may trigger lazy execution of other not-yet-run layers. The unconditional layers are the layers that set global variables (like Ci or P), the layers whose outputs are connected to designated renderer outputs (AOVs and the like), and layers that have no connected outputs at all (under the theory …

Execution order refactor, and per-layer explicit execution order

---

src/shaders/stdosl.h

Leave only the closure declarations needed by testrender
and testshade.

Closure cleanup

---

src/include/OSL/oslclosure.h
src/liboslexec/closure.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec_pvt.h
src/testrender/shading.cpp

These two fields were redundant with each other. Merging them lines things up a bit more nicely internally (closure data starts at offset 16 instead of 20).
Also added some convenience methods to reduce the need for verbose casts in client code.

Merge type and id fields in ClosureColor

---

CMakeLists.txt

Refactoring for simplification of the compiler-specific bits of the CMakefile.
Also synchronizes with the CMake scripts for OIIO -- there were places where they did basically the same things, but expressed differently or in different orders. I tried to make them more similar for ease of maintenance and transferring good ideas between them.

cmake: Better detection of Clang version, including Apple vs OSS Clang.

---

src/include/OSL/oslexec.h
src/liboslexec/instance.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp
testsuite/layers-Ciassign/run.py
testsuite/layers-entry/ref/out.txt
testsuite/layers-entry/run.py

New logic: the only layers unconditionally run are (1) the LAST layer
(presumed to be the "root"), (2) any layer that sets a designated
renderer output, (3) any layer that sets a global, but only if
lazyglobals is off (it's on by default now). Everything else is run
"lazily", that is, only if and when its connected outputs are needed
downstream.
The old logic additionally considered a layer to be unconditional (i.e.,
not lazy) if it has NO outgoing connections, on the theory that is must
be the root, and also lazyglobals was not turned on by default. That
seemed like a recipe for inefficient shader evaluation, and it doesn't
look like any renderer needs or wants this.

Change logic of lazy evaluation -- unconnected layers are now lazy.

---

src/liboslcomp/oslcomp.cpp
src/oslc/oslcmain.cpp

This had been the intent for some time, but a few references to
boost::filesystem had escaped our notice.

Replace bare boost::filesystem with strings & OIIO::Filesystem.

---

CMakeLists.txt
src/liboslcomp/ast.h
src/liboslcomp/codegen.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp
testsuite/struct-init-copy/Astruct.h
testsuite/struct-init-copy/a.osl
testsuite/struct-init-copy/b.osl
testsuite/struct-init-copy/ref/out.txt
testsuite/struct-init-copy/run.py

When a shader param that was a struct had its value initialized by copying    another struct WHOLE, it neglected to set the "method" name for the init    ops for each field. This made it incorectly chalk up the init ops to the    struct param itself (which is just a dummy placeholder) instead of the    fields, and under some circumstances this could simply leave the struct    fields uninitialized.
It was fine all along if the struct param's fields were initialized one    by one -- in that case, the init ops were correctly associated with each    field individually. It was only the case of initializing by copying    another whole struct that was problematic.
The solution is to pass a flag to codegen_assign_struct indicating if we    are generating that code for a parameter initialization, …

oslc bug fix for code generation of struct parameters copied whole.

---

src/doc/languagespec.tex
src/shaders/stdosl.h

`linearstep(edge0, edge1, x)` linearly interpolates from 0 to 1 as x goes from edge0 to edge1.
Here is a picture of `linearstep(0,1,x)`:
-----
`smooth_linearstep(edge0, edge1, x, eps)` is exactly linear (identical to linearstep) on [edge0+eps,edge1-eps] but has smooth ramp on and off between [edge0-eps,edge0+eps] and [edge1-eps,edge1+eps].
Below, linearstep(0,1,x) is blue, smoothstep(0,1,x) is green, smooth_linearstep(0,1,x,0.1) is red:
`smooth_linearstep` has some interesting properties:
* It is exactly linear in much of its domain, unlike `smoothstep` which is always curvy.
* Its slope is 1 in the linear range, exactly matching `linearstep`, unlike `smoothstep` which is "steeper" than linear interpolation.
* But it does this be having its tails extend slightly beyond the edge0 and edge1 …

New OSL builtins for patterns: linearstep(), smooth_linearstep()

---

src/liboslexec/opstring.cpp

We're getting crashes, very hard to reproduce so I'm not 100% sure this is related, but there is circumstantial evidence that the crash happens inside osl_endswith_iss. Looking at the code, I can see how NULL arguments could be trouble to this and some related functions, so I'm beefing up handling of those cases.

Make certain string ops robust to NULL arguments.

---

src/liboslcomp/oslcomp.cpp
src/liboslexec/llvm_gen.cpp

I'd inadvertently allowed a build break and a possible bug creep into
OSL 1.7 (dev) that depended on new features of OIIO 1.6 (dev). This
patch restores OSL trunk so that it will build correctly against the
stable release branch of OIIO which is currently 1.5.

Fixes for OIIO 1.5 compatibility.

---

src/shaders/stdosl.h

Try to make sure that when eps is detected to be constant and 0, it's as
close as possible to being as efficient as linearstep, by rearranging
the various clauses of the 'if'.

smooth_linearstep: Ensure that it's as efficient as possible when eps == 0

---

src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h

Makes debugging a little easier for me, I don't need to wonder what command line options (defines or include directories, etc.) were used.

Record oslc options in comment in the oso file

---

src/include/OSL/oslexec.h
src/liboslexec/backendllvm.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
src/liboslexec/shadingsys.cpp

1. Instead of hard-coding 10 passes over each layer when optimizing, let it be a SS attribute. (This is for me, I don't expect or want users to mess with it.)
2. Improved optimizer debugging messages -- refactored in a way that made it easier to have the little "I changed instruction FOO to instruction BAR because ..." debug messages to note which shader file and line that corresponds to.
3. Make an easy way for the JITer to insert code that will generate a runtime error or warning.
4. When encountering a request to make a closure that the renderer doesn't know about, instead of being a JIT-time error, do the thing from (3) above to make it a shader runtime error, which of course will only trigger if it actually tries to execute that line. This removes some spurious error messages in …

A collection of optimizer debugging aids

---

CMakeLists.txt
src/doc/languagespec.tex
src/liboslcomp/typecheck.cpp
src/liboslexec/constfold.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/shadingsys.cpp
testsuite/isconstant/ref/out.txt
testsuite/isconstant/run.py
testsuite/isconstant/test.osl

isconstant(expr) returns 1 if the expression can be turned into a constant
at runtime (with full knowledge of the shader group's parameters values and
connections).
This is primarily a debugging aid for advanced shader writers to verify
their assumptions about what expressions can end up being constant-folded
by the runtime optimizer. Also an aid for me in debugging that the runtime
optimizer is behaving as I expect.

isconstant(expr) returns 1 if the expression can be turned into a constant

---

src/include/OSL/oslconfig.h

Use OSL_CPLUSPLUS_VERSION rather than OSL_USING_CPP11. The former is better for long-run distinguishing between 03, 11, 14, 17, and so on, whereas the latter is shortsightedly binary.

C++11 compatibility clean-up

---

src/liboslexec/llvm_util.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
src/testshade/testshade.cpp

The reason for this is that I want to take the inclusion of boost::tsp out of the OIIO thread.h public header file. These are the only places in OIIO that we use it.

Use boost::thread_specific_ptr, don't rely on it in OIIO namespace.

---

src/include/OSL/oslexec.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
src/liboslexec/shadingsys.cpp

OSL's runtime optimizer tracks "value aliases" (one variable being set to be the same as another, or a constant), such as a=1, b=u. So then in subsequent use, if it sees c=a*d, it knows that can simplify to c=d (because a==1) and e = b-u can simplify to e=0 (because b and u hold the same value).  When a symbol's value is altered, of course the alias is removed from the active list. Also, we clear the list when we begin a new basic block (any contiguous series of instructions with strictly sequential control flow), because we don't know what values are held by variables at breaks of control flow.
However... there are a couple special (but common) cases where we know that even though an instruction is the target of a jump and therefore the beginning of a new basic block, we need not throw …

OSL optimization: much better tracking of basic block aliases.

---

src/include/OSL/oslquery.h
src/liboslquery/oslquery.cpp

This is handy feature to have for applications which has OSL in-memory bytecode
cache but still needs to run OSLQuery on such shaders without creating temporary
files on the disk.
Currently only explicit query.open_bytecode() call is supported, this is because
it's not really possible to distinguish filepath from memory buffer being passed
to the constructor.

Support OSLQuery from a given bytecode

---

src/include/osl_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h

* The temporary coalescing has always relied on the assumption that temp
lifetimes can simply be compared for overlap in their min/max
instruction numbers, and this is only possible if their lifetime
doesn't cross a loop boundary. As long as temporaries are restricted
to live within one basic block, this is safe -- and they do so as a
natural consequence of how they are created and used. EXCEPT that as a
result of the new analysis, their values could end up being used
outside their original basic blocks, and then could be inappropriate
coalesced. Oops.
The easy fix for this one is that when we save and restore the alias
list, we exclude temporaries from the copy. The fix is in the
implementation of copy_block_aliases.
* There are a couple circumstances in which code transformations call …

Fix some subtle bugs in the recent improved basic block alias analysis.

---

src/doc/languagespec.tex
src/liboslexec/runtimeoptimize.cpp
testsuite/isconnected/ref/out.txt
testsuite/isconnected/test.osl
testsuite/isconnected/upstream.osl

Old: isconnected(param) returns 1 if the param is connected to an upstream
layer, otherwise 0.
New: isconnected(param) returns 1 if the param is connected to an upstream
layer, 2 if connected to a downstream layer, 3 if both, 0 if neither.

Change isconnected() to reveal down-connections

---

.travis.yml
CMakeLists.txt
Makefile
README.md
src/build-scripts/build_openexr.bash
src/build-scripts/build_openimageio.bash
src/build-scripts/install_homebrew_deps.bash
src/cmake/externalpackages.cmake
src/cmake/oiio.cmake
src/liboslexec/CMakeLists.txt
src/testshade/CMakeLists.txt

Modeled after what I did recently for OIIO. Henceforth, all pull requests and pushes to the main OSL repo will cause builds to be kicked off for OSX and Linux, with a few different build options each. When somebody makes a PR, even before merging we can be reasonably certain it doesn't break the build, yay.
It's not 100% finished, but it's working and useful. The biggest unresolved issue is that I have to manually exclude 4 tests (out of almost 300) that don't match their output images exactly (and I'm sure are fine), and I haven't yet figured out how to recover the files it generates so I can commit it as an alternate reference image. But I'll sweep that under the rug for now and come back to it.

Travis-CI setup for OSL

---

.travis.yml
CMakeLists.txt
src/build-scripts/install_homebrew_deps.bash

Same changes as https://github.com/OpenImageIO/oiio/pull/1274
Last night's web surfing discovery: 5 lines added to CMakeLists.txt that causes it to use ccache if it's installed on the system. Cuts Travis builds by half, and will also speed up any other users building OSL who doesn't take steps on their own to use cmake.
Is there a downside? Does anybody feel like they are likely to have cmake installed but want specifically NOT to use it, and need a switch to turn this off? Or is "use cmake if they have it" good enough?
Also some cleanup and reformatting after discovering that in the .travis.yml file I can split commands over several lines, makes it more readable.

Travis cleanup, and use ccache

---

src/liboslcomp/ast.cpp
src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp

A subtle optimization bug was traced to this, and now I'm fully at Stage 6 ("how did that ever work?"). I think that the test we had before did not catch all the cases, and applied only to declared local variables, which I can't even fathom why I thought was not going to cause trouble.
I think that to be safe, the correct rule is that any symbol that is modified before or inside a loop, and read inside or after the loop, needs to have its lifetime extended to the full body of the loop, because it needs to preserve its value for possible additional iterations of that loop and NOT be optimized away or coalesced with another symbol in a way that would botch this.
As an important exception, there is the case of a temporary or local that is written strictly before being read, and whose entire …

Revision of the logic behind lifetime analysis inside loops.

---

.travis.yml

This will make it harder to inadvertently push OSL changes that break against even the older version of OIIO, or that break when using a newer gcc.

Travis: add to the matrix gcc 5, release OIIO (not just master)

---

src/include/OSL/rendererservices.h
src/osl.imageio/oslinput.cpp
src/testrender/simplerend.cpp
src/testrender/simplerend.h
src/testshade/simplerend.cpp
src/testshade/simplerend.h

None of the internals of OSL ever call this method

Remove has_userdata method from RendererServices

---

src/include/OSL/oslconfig.h

deprecated with argument only was introduced with gcc 4.6

Minor OSL_DEPRECATED adjustment

---

src/liboslcomp/osllex.l

This was never intentionally allowed; it was just a bug in the lexer's
regex describing a quoted string. The compiler would accept it silently,
but in the process forget the line count and botch subsequent error
messages.

Disallow quoted strings from spanning lines (just like you can't in C).

---

CMakeLists.txt
testsuite/pointcloud-fold/run.py
testsuite/runtest.py
testsuite/texture-derivs/run.py
testsuite/unknown-instruction/ref/out.txt
testsuite/unknown-instruction/run.py
testsuite/vararray-deserialize/run.py

The old way was that when CMake runs for the first time (when it builds your make or ninja files), it copies everything from testsuite/ into build/PLATFORM/testsuite/, and then when you run tests, it uses all the info (source data, scripts, and reference output) in the build area.
That was fine usually, but if you were developing or modifying a test itself, it was a big PITA, because changing something in testsuite/mytest would not be reflected in the build/PLATFORM/testsuite/mytest that had already been copied. It was the source of many frustrations and errors. And beware modifying something in the build area and then blowing it away, not remembering to copy it to the source testsuite/ area.
This overhaul NO LONGER COPIES source data or reference output en masse to build at all. Instead, …

Testsuite organization overhaul -- no more src or ref in build

---

src/liboslcomp/typecheck.cpp
src/liboslexec/loadshader.cpp
src/shaders/stdosl.h

This could lead to a cascade of optimization errors at runtime.
I have no idea why this never showed up as a problem before today.
In addition to fixing it on the oslc side, add a hacky fix to make sure    that old compiled shaders are retroactively fixed as they are loaded at    runtime.

oslc bug -- getmatrix failed to note that the matrix argument is written

---

src/liboslcomp/ast.cpp
src/shaders/stdosl.h

As Chris points out in #618, the fact that params are marked as output
is all we need to know that function's parameters are not all read-only
(duh). That seems a little more foolproof than requiring a separate notation
in stdosl.h.

For stdosl.h funcs marked builtin, auto-detect funny read-write cases.

---

.travis.yml
CMakeLists.txt
Makefile

make CODECOV=1
make CODECOV=1 test
on a gcc/clang system will run the testsuite and generate a code coverage
report in build/$PLATFORM/cov/index.html
I'm not yet sure how we should use this. It's just for information and to help spot places in the code that aren't covered by the testsuite. But I do not think we should aim to get 100% coverage -- eliminating all the stragglers for every possible error case and early return would be so much labor that we'd never get any real work done. So take with a grain of salt and use wisely.

First stab at code coverage

---

src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec_pvt.h

This shouldn't change any behavior. It's just removing some pointless code that checks if a layer has been run before, but there's no need to do that on the root layer which by definition is run exactly once.
Also be sure that the entry point doesn't use the "fast" calling convention.
This is just some stuff I noticed in the process of scrutinizing the code we were generating.

Don't test or set "layer ran bits" on last layer.

---

src/include/OSL/llvm_util.h
src/include/OSL/oslexec.h
src/liboslexec/backendllvm.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

I'm in the middle of a concerted effort to bring us into a more modern era of LLVM versions. This set of patches is not a complete solution, but contains several intermediate steps in that direction.
* Remove all support for LLVM 3.3 and earlier. This gets rid of lots of confusing `#if` clauses and simplifies the structure of the code. Henceforth, LLVM 3.4 will be the minimal version we support for OSL 1.8.
* A number of changes that allow us to build cleanly against LLVM 3.6. Although it correctly runs the llvmutil_test unit test, it fails all the testsuite tests involving OSL itself (against LLVM 3.6). But at least it compiles.
* Remove runtime selection of MCJIT for LLVM versions that support both MCJIT and old JIT. This simplifies the logic in some places, by cleanly dividing LLVM …

LLVM-related refactoring

---

src/liboslexec/llvmutil_test.cpp

* JIT two different functions, one of which uses vec3. One reason this
is nice is to expose any bugs that only crop up with more than one thing
is JITed, and the existance of multiple LLVM_Util's.
* Add a test that makes a function with a HUGE amount of unnecessary IR,
and JITs it repeatedly, so that we can verify memory usage and have a
simple time benchmark.

llvmutil_test enhancement: more comprehensive tests and benchmarks

---

src/include/OSL/oslexec.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp
src/testshade/testshade.cpp
testsuite/isconnected/ref/out.txt
testsuite/isconnected/run.py
testsuite/isconnected/test.osl

This adds a new ShadingSystem attribute, "userdata_isconnected". The
default of 0 is the old/usual behavior that most applications want.
However, setting this attribute to 1 will cause the OSL built-in
function isconnected(paramname) to return 1 not only for connected
parameters, but also for parameters that may be bound to userdata
(i.e., those that have lockgeom=0).
The use case for this involves a renderer implementation that can mix
C++ and OSL nodes within a shading group. The outputs exported by the
C++ nodes propagate their values to the downstream OSL node via
get_userdata(), hijacking the mechanism that is generally used geometric
primitive variable interpolation. But from the point of view of the
downstream node, they should semantically appear to be a connection.

Make an option to have OSL isconnected() return 1 for userdata parameters

---

CMakeLists.txt
src/liboslcomp/typecheck.cpp
testsuite/oslc-warn-commainit/ref/out.txt
testsuite/oslc-warn-commainit/run.py
testsuite/oslc-warn-commainit/test.osl

shader test ( output color Cout = 0 )
{
vector x = (1, 2, 3);
}
See where this goes wrong? This code will make x be (3,3,3).  If you
don't know why, think about how the comma operator works in C, C++, and
related languages.
The user almost certainly meant
vector x = vector (1, 2, 3);
With this change, the original (buggy) code will get the following
warning output:
test.osl:3: warning: Comma operator is very confusing here. Did you mean to use a constructor: x = vector(...)?

Warn for common misstep of forgetting constructor name.

---

CMakeLists.txt
src/liboslcomp/codegen.cpp
testsuite/oslinfo-colorctrfloat/ref/out.txt
testsuite/oslinfo-colorctrfloat/run.py
testsuite/oslinfo-colorctrfloat/test.osl

We're talking about a construct like:
shader foo (color c = color(1), ...)
It got it right if it was
color c = color(1,1,1)
In both cases, it properly reduced the default value to a static constant
value, but the bug was that it ALSO (unnecessarily) had extra init ops
for that parameter. That would be eliminated in runtime optimization, the
shader certainly ran correctly, but it threw off oslinfo, which figures
that if init ops are present, it can't figure out what the default values
were.

Fix oslc incorrectly emitting init ops for constructor color(float).

---

src/liboslcomp/osllex.l
src/liboslexec/osolex.l

Option "never-interactive" prevents flex from emitting calls to isatty,
which is not always present on Windows. This is fine because we never
use the lexer in interactive mode anyway.

Windows fix for lexer

---

src/liboslcomp/osllex.l
src/oslc/oslcmain.cpp
src/testrender/testrender.cpp

OpenImageIO/refcnt.h no longer includes all of thread.h

Include file fixes after recent OIIO change that split atomic.h & thread.h

---

src/liboslexec/runtimeoptimize.cpp

The optimize_ops method had a convenience reference to the op being
examined in the loop.  We carefully do a reserve() first to make sure
that there was enough room for one insertion so that the reference would
still be valid if the constant-folding function has to add an op.  But
this relied on the assumption that no folder would insert more than one
op as it did its work, which was always true (once).
Oops, much later, a new way to speed up "mix" ops had a particular corner
case in which up to 7 new ops might be inserted, and I never went back
and fixed the now-broken assumption here.
The fix here is to change the reference to the op (which cannot be
changed dynamically) into a pointer to the op, which can be re-pointed
after calling the folding function to make sure that it's valid and …

Fix subtle bug in optimize_ops that could seg fault.

---

CMakeLists.txt
src/liboslexec/instance.cpp
src/liboslexec/shadingsys.cpp
testsuite/mergeinstances-vararray/arrayparam.osl
testsuite/mergeinstances-vararray/ref/out.txt
testsuite/mergeinstances-vararray/run.py
testsuite/mergeinstances-vararray/shadergroup
testsuite/mergeinstances-vararray/simple.osl

Because the altered data offset wasn't transferred from the instance
overrides to the instance's full symbol table, it was comparing the
default values rather than the actual values, so two instances that
should not have been merged, were merged.
Also fixed a (harmless) bug in ShadingSystemImpl::ShaderGroupBegin,
where the serialized group is parsed, where it was double-calling
Parameter() to add the parameters.
Fixes #655

Bug fix: incorrect instance merging when unspecified-length arrays differed

---

src/include/osl_pvt.h
src/liboslexec/runtimeoptimize.cpp

Occasionally, a shader will use the incoming value of an output
parameter, before it is overwritten. If that value can be decuded, go
ahead and make the alias so that we can further optimize operations
involving that param until it is written.

Runtime optimization: seed block alias with initial value of output param

---

src/liboslcomp/ast.cpp

Minor issue, when compiling this shader with `oslc` or an application embedding the OSL compiler it crashes:
```
shader test()
{
closure color A;
A[0] = 0;
}
```
```
src/include/osl_pvt.h:314: failed assertion '! is_closure() && "Don't call this if it could be a closure"'
```
From: https://developer.blender.org/T49016

Fix OSL compiler assert when indexing into closure type

---

src/liboslexec/llvm_ops.cpp
src/liboslexec/opmatrix.cpp

Imath::M44f.transpose() transposes in place and returns the ref,
whereas transposed() returns the transpose without altering the original.
Not a symptomatic bug because we only did this on the result of an
inverse(), which was a temporary, so didn't hurt to mess with it in place.
But better to correct this code to properly reflect our intent.

Typo bug transpose() vs transposed().

---

src/include/OSL/oslexec.h
src/liboslexec/context.cpp
src/liboslexec/instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
src/testshade/testshade.cpp

The default is 1, which is the old behavior: each call to
ShadingSystem::execute() will run the shader group once.
How is this useful? Suppose you have a very complicated app like a
renderer, and you're curious how much total time is attributable to the
actual execution of the shader. Each individual shader execution may be
so quick that putting timers around the calls may throw off the overall
time of the app (it takes time to retrieve the time, so by measuring
you are changing the timing characteristics; Heisenberg would
be proud).
So you set exec_repeat to 2, running each shader TWICE per call to
execute(). If you time this and compare it to shading the usual 1 time
per execution, the difference should be the total time spent shading for
an ordinary run. (But NOT including texture I/O …

SS and group options "exec_repeat" can cause shader execution to repeat.

---

src/include/OSL/oslexec.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp

New SS attribute "force_derivs", when nonzero, will store and compute
derivatives for all float-based symbols, even if dependency analysis shows
they are not needed.
This is handy for quantifying how good we are at recognizing when we need
derivs (answer: very good, only a small percentage of post-optimized syms
end up with derivs) and also for debugging suspected derivative problems
(by essentially forcing derivs on almost everywhere).
Also amend stats report how many symbols carry derivatives.

Add ability to have derivs everywhere.

---

CMakeLists.txt
src/include/OSL/oslexec.h
src/liboslexec/constfold.cpp
src/liboslexec/instance.cpp
src/liboslexec/master.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
src/liboslexec/shadingsys.cpp
src/testshade/testshade.cpp
testsuite/raytype-specialized/ref/out.txt
testsuite/raytype-specialized/run.py
testsuite/raytype-specialized/test.osl

A new ShadingSystem::optimize_group() method takes bit fields describing
which ray types are known to be true and known to be false (not being
specified in either means it's indeterminite at optimize time, will only
be known at execution time).
When compiled in this manner, the runtime optimizer will constant-fold
calls to raytype(name) when the name matches those in the "in" and "out"
lists you have supplied.
This allows an app to specialize a shader for particular ray types (such
as a highly optimized version just for shadow rays).
There is also a new group attribute query "raytype_queries", which reveals
the bit pattern of any raytype() calls mde by any of the shaders within
the group.
As an example, the basic logic for specializing shadow shades and non-shadow
shades looks like this: …

Allow optimization of shader groups with known raytype bits.

---

CHANGES.md
CMakeLists.txt
src/include/OSL/oslnoise.h
src/liboslexec/CMakeLists.txt
src/liboslexec/constfold.cpp
src/liboslexec/opnoise.cpp
src/liboslnoise/CMakeLists.txt
src/liboslnoise/gabornoise.cpp
src/liboslnoise/oslnoise_test.cpp
src/liboslnoise/simplexnoise.cpp

This patch makes a new library, liboslnoise (with corresponding
oslnoise.h), that just contains the various noise functions from OSL,
exposed in a way that can be easily called from other applicaitons.
For our first stab at this, only the perlin noises (signed and unsigned)
and cellnoise are exposed. We have varieties that take 1-, 2-, 3-, and 4-D
domain coordinates, and return either float or vector (3D) noise values.
At this point, we DO NOT expose the varieties that take derivatives, nor
the periodic perlin noises, nor the gabor and simplex noise varieties,
or varieties that directly take or return our simd types.  We may add
some or all of these in the future, but I thought that we should gague
reaction to what we have so far and make sure we're on the right track.
Although we produce …

liboslnoise -- C++ library with noises that match OSL

---

CMakeLists.txt
src/doc/languagespec.tex
src/liboslexec/constfold.cpp
src/liboslexec/shadingsys.cpp
src/testrender/testrender.cpp
src/testshade/testshade.cpp
testsuite/debug-uninit/ref/out-opt2.txt
testsuite/debug-uninit/ref/out.txt
testsuite/getattribute-shader/ref/out.txt
testsuite/getattribute-shader/run.py
testsuite/getattribute-shader/test.osl

getattribute ("shader:shadername", dst)
getattribute ("shader:layername", dst)
getattribute ("shader:groupname", dst)
And of course they constant fold, so there is no runtime cost.
Beware: the layer names could be screwy if you are using the duplicate
instance merging optimization. If you are depending on layer names for
debugging, you may want to turn off just that optimization (set
ShadingSystem attribute "opt_merge_instances" to 0) while debugging.

New getattribute queries for shader, layer, and group name.

---

src/liboslcomp/codegen.cpp
testsuite/matrix/ref/out.txt
testsuite/matrix/test.osl

When generating the static construction values, it needed to recognize
that case and set the "completed" flag to false, so that it would know
that it couldn't be constructed statically and needed init ops emitted
for that paramter.

Bug fix: matrix param initialized with matrix(space,1) left out init ops

---

src/liboslexec/CMakeLists.txt

With static libraries the indirect dependency is not picked up automatically, so explicitly add it to `testshade` and `testrender`.

Fix oslnoise link errors when building static OSL libraries.

---

src/liboslexec/constfold.cpp
src/liboslexec/runtimeoptimize.h

matrix(spaceA,spaceB) already optimized to a constant matrix if spaceA and spaceB were both constant names and did not refer to motion-blurred transformations.
New case: if spaceA and spaceB alias to the same symbol, then we know this is the identiy matrix, even if they are not known constant values, and even if they refer to a motion-blurred space.
matrix(float0, float1, ... float15) already turned into a constant matrix if all the values were constant.
New case: matrix(float0) can be turned into a constant matrix if its value is constant (it's usually 1, but it doesn't have to be).

Better runtime optimization of some matrix constructors.

---

src/liboslexec/runtimeoptimize.cpp

Params that needed init ops, but the initialization was just a single assignment, could be "aliased" to the thing they were assigned to (a constant or a global or another param). It was identifying this by basically asking "does this param's init ops consist of just one op, and is it 'assign'?"
But... maybe the initialization started out as several ops, and runtime optimization whittled it down to just one assignment -- it might look like multiple ops, but all but one are 'nop'.
So now we "trim" the init ops of any leading or trailing nop instructions, before doing this test. And it catches some more cases that can be simplified!
As a real-world example, consider:
param s = u * scale + offset
Where scale and offset are also parameters.  This initially compiled to:
tmp1 = u * scale
s = …

Improve aliasing of params with simple init ops.

---

CMakeLists.txt

Equivalent to the change we made in OIIO on this same topic: https://github.com/OpenImageIO/oiio/pull/1529

Suppress clang 3.9 warnings

---

CMakeLists.txt
src/liboslcomp/ast.cpp
src/liboslcomp/typecheck.cpp
testsuite/oslc-err-notfunc/ref/out.txt
testsuite/oslc-err-notfunc/run.py
testsuite/oslc-err-notfunc/test.osl

See the new testsuite example. This crashed oslc before!
Fix it up to not crash (by marking the unfound function's symbol as NULL),
and also improve the resulting error message.
Fixes #681

oslc better err reporting for use of non-function symbol as function.

---

src/liboslexec/constfold.cpp

Opt: triple(space,const,const,const) can get fully folded to a constant if the space name is known to be equivalent to "common".

Opt: triple(space,const,const,const) can get fully folded to a constant

---

site/spi/Makefile-bits

* Change default to use llvm & clang 3.5 rather than 3.4.
* More flexibility for overriding which compiler version.
* Some refactoring to regularize the OIIO and OSL cmake files that overlap.
This doesn't affect non-SPI sites.

SPI - Options to run other compilers

---

src/include/OSL/oslexec.h
src/liboslexec/backendllvm.h
src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

This can be helpful to OSL's developers for certain debugging tasks.

Debugging option 'llvm_debug_ops' adds a printf before running each op

---

src/liboslexec/backendllvm.h
src/liboslexec/llvm_gen.cpp

Just a small refactor I did while working on some other things.

Make BackendLLVM::llvm_debug_printf/gen_warning/gen_error take string_view

---

src/liboslexec/llvm_instance.cpp

A good optimization in any case, but some of the new code triggered
assertions in LLVM that only seemed to happen for empty shaders.

Skip LLVM JIT for empty shaders.

---

CHANGES.md
src/cmake/externalpackages.cmake
src/liboslcomp/codegen.cpp
src/liboslcomp/oslcomp.cpp
src/liboslcomp/symtab.cpp
src/liboslcomp/symtab.h
src/liboslcomp/typecheck.cpp
src/liboslexec/automata.h
src/liboslexec/constantpool.h
src/liboslexec/context.cpp
src/liboslexec/dictionary.cpp
src/liboslexec/instance.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/loadshader.cpp
src/liboslexec/master.cpp
src/liboslexec/opnoise.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/pointcloud.cpp
src/liboslexec/rendservices.cpp
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
src/liboslexec/shadeimage.cpp
src/liboslexec/shadingsys.cpp
src/oslc/oslcmain.cpp
src/testrender/simplerend.h
src/testrender/testrender.cpp
src/testshade/simplerend.h

I've waited a long time for this flurry of adjustments to 'master', now that we are safely assuming a base of C++11 minimum, Boost minimum 1.55 per VFXPlatform's guidelines (as far back as CY2015), and also our stated intention for OSL master/1.9 to require a minimum OpenImageIO version of 1.7 (which is the current supported release, so seems safe).
In the process, a whole bunch of our Boost use disappears, in favor of C++11 std and modern OIIO wrappers:
* BOOST_FOREACH -> C++11 "range for"
* boost::unordered_map and unordered_set -> std
* boost string algorithms -> OIIO Strutil utilities
* boost::bind and ref -> std
* boost::filesystem -> OIIO Filesystem utilities

C++11 and Boost changes

---

src/liboslcomp/ast.h
src/liboslcomp/typecheck.cpp
src/liboslexec/loadshader.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
src/testrender/testrender.cpp
src/testshade/testshade.cpp

New changes in this patch:
* boost::intrusive_ptr -> OIIO::intrusive_ptr (we could've done this a while back probably, but it's trivial now that we've bumped master's minimum OIIO version)
* boost thread, bind -> std + OIIO thread utils
After this patch is applied, our ONLY direct boost use in OSL is:
* boost::wave (for oslc's C preprocessor)
* boost's flat_map and flat_set containers (header only, fast)
* boost's thread-specific pointer (very handy, and equivalent is not yet in std::thread)
* boost::regex (only because std::regex is incompletely implemented prior to gcc 4.9, so we'll remove this next year if VFXPlatform moves to gcc 4.9 or beyond)
That's getting pretty minimal, and none of it is in the public APIs.

More boost removal

---

src/cmake/externalpackages.cmake
src/cmake/modules/FindLLVM.cmake

Split into a proper FindLLVM.cmake, require at least 3.4 (for now).

Refactor finding of LLVM

---

.travis.yml
src/cmake/externalpackages.cmake

Also one test against 3.5, while we still support it, to be sure it doesn't break.
The real trick here is that I couldn't find a proper apt package for the somewhat older flavor of Ubunu ("precise") that's on the Travis servers, for any LLVM newer than 3.4. The solution, at least for now, is to use wget to download the handy per-build packages available from llvm.org and use those directly.

Change TravisCI builds on Linux to build primarily against LLVM 3.9.

---

src/include/OSL/oslquery.h
src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.h

Goes along with (and is necessary for) https://github.com/OpenImageIO/oiio/pull/1619
but this change should work fine with OIIO before this change as well.

Remove direct reference to tinyformat in lieu of C++11 variadic templates

---

CMakeLists.txt
site/spi/Makefile-bits
src/cmake/externalpackages.cmake
src/liboslexec/constfold.cpp
src/liboslexec/context.cpp
src/liboslexec/opstring.cpp
src/liboslexec/oslexec_pvt.h

On the currently supported compilers, we believe the only time we
need to fall back to boost::regex is for g++ 4.8.x.
Also change the ShadingContext::m_regex_map to use unique_ptr<>
so that the allocated regexes free upon destruction without needing
an explicit loop and delete calls.

Use std::regex any time it is available.

---

.travis.yml
CMakeLists.txt
INSTALL.md
Makefile
site/spi/Makefile-bits
src/cmake/externalpackages.cmake
src/cmake/modules/FindLLVM.cmake
src/include/OSL/oslversion.h.in
src/liboslcomp/CMakeLists.txt
src/liboslcomp/oslcomp.cpp
src/liboslexec/CMakeLists.txt

Boost Wave is a bit of a pain, in particular it can have problems if compiling OSL with C++11 (as is mandatory now in master) but link against a Boost that was compiled without the C++11 options.
At Chris Kulla's suggestion, we can switch to using the C preprocessing faciliies from clang's internals. Ordinarily, LLVM/clang would be much to painful to add just for this, but since we're already tied to LLVM as a dependency, it's really no additional burden.
So here we are. There's a build time cmake option USE_BOOST_WAVE, which defaults to off, but if problems are discovered with the clang cpp, that gives is a Plan B. Eventually, when we're completely confident in the way I've done it with clang, we may remove the Wave option entirely.
This is not 100% working. It seems to work fine if you …

Use clang's C preprocessor as alternative to Boost Wave

---

src/liboslexec/dictionary.cpp

It was incorrect to take a reference to an element of the vector
m_nodes, and then to keep using the reference inside the loop in
which the vector is grown (thus possibly invalidating the memory
that the reference points to).
Found by address sanitizer!

Fix subtle use-after-free error in Dictionary::dict_find

---

src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h

Use OIIO::Filesystem::read_text_file to read the whole file at once
instead of doing piecemeal file reads.
This eliminates an occasional buffer overrun as well.

Simplify how we put raw source code into .oso comments

---

src/cmake/externalpackages.cmake
src/liboslcomp/oslcomp.cpp

We were not setting up "diagnostics" properly, which led shaders
with certain errors in their use of the C preprocessing to hit
assertions in the clang code.

oslc with clang cpp: capture preprocessor errors properly

---

src/include/OSL/dual_vec.h

This could lead to NaNs or Infs on very small arguments.

Fix inconsistency in normalize between Dual and float versions

---

site/spi/Makefile-bits
src/cmake/externalpackages.cmake

On some systems, sometimes, when linking against LLVM <= 3.5 and using
clang internals for C preprocessing, we've seen assertions coming from
llvm::cl::OptionCategory::registerCategory, which we aren't even
intentionally using.
This email explains the issue:
http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20140203/203968.html
Seems pointless to fight what appears to be an awkward mis-design in
older LLVM. The problem was fixed some time between 3.5 and 3.9.
So let's sweep it under the rug by falling back to boost wave when using
older LLVM.

Fix clang assertion / linkage error

---

src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
src/liboslexec/shadingsys.cpp

OSL's runtime optimizer tries to eliminate operations whose results are never used (people don't write shaders like this, but as we optimize and rewrite the shader's ops, many ops may reveal themselves as having no effect).
But, we don't do this with built-ins that have no written arguments at all (such as printf or setmessage), because it figures that having no immediate outputs means it's there purely for the side effects.
But -- OH NO! -- it turns out that trace() is an exception to the rule. It has a writeable output (the return value), but it ALSO has an important side effect (it sets up trade state that may later be queried by getmessage("trace")). So if you wrote a trace call and did not assign its return value to something that got used, the trace call might be eliminated …

More robust handling of exceptions to "useless op elision."

---

CMakeLists.txt
src/cmake/compiler.cmake
src/include/OSL/export.h

They are very similar. From time to time I do two-directional transfers
to migrate the best practices of each to the other.
I also try to nudge them even closer in various ways, such as using
${PROJECT_NAME}_BLAH in both instead of OSL_BLAH in one and
OpenImageIO_BLAH in the other.

Synchronize some build scripts between OIIO and OSL.

---

src/liboslexec/CMakeLists.txt
src/testrender/CMakeLists.txt
src/testshade/CMakeLists.txt

liboslexec contains all the functionality of oslcomp. You never need
both. It used to be harmless to link against both, though, until we
included clang C preprocessing functionality. Clang has some components
that cause trouble if linked twice, and so we run into that both
liboslexec and liboslcomp contain statically linked clang components.

Fix linkage problem with some tests unnecessarily linking liboslcomp

---

src/include/osl_pvt.h
src/liboslcomp/ast.h
src/liboslexec/accum.cpp
src/liboslexec/accum_test.cpp
src/liboslexec/automata.cpp
src/liboslexec/context.cpp
src/liboslexec/dictionary.cpp
src/liboslexec/instance.cpp
src/liboslexec/loadshader.cpp
src/liboslexec/shadingsys.cpp
src/liboslquery/oslquery.cpp
src/osl.imageio/oslinput.cpp
src/oslc/oslcmain.cpp
src/testshade/testshade.cpp

Now that we have C++11 as a minimum, we can use this handy feature that
grows a vector by one slot (uninitialized) and the constructs a new
object in that location. In contrast, push_back() constructs the object
first, then grows the vector with a default constructed object, they
copies (or if you're lucky moves) the new object into the vector
position. Maybe the compiler will figure it all out, maybe not.  Using
emplace_back guarantees that there are no needless copies, moves, or
pointless constructions.
Thanks, clang-tidy, for making this a 5-minute change!

Use C++11 vector::emplace_back() where appropriate.

---

src/include/OSL/oslexec.h
src/liboslexec/instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp

This makes it possible to use this feature of the optimizer even when relying on lazy JIT of shader groups.

Add an API call to define raytypes_on and raytypes_off

---

src/include/OSL/oslconfig.h
src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h

Use type-safe variadic templates instead.
The implementation details get cleaner if you have a sufficiently new OIIO, so there are a couple `#if`s
for now, but eventually the old path can be removed.
Not a pressing issue, just some cleanup I finally got around to.

Eliminate varargs from OSLCompilerImpl and ASTNode

---

.travis.yml
Makefile
src/liboslcomp/oslcomp.cpp
src/oslc/oslcmain.cpp

There was a discrepancy in how stdosl.h is searched for, among the different ways that compiles are triggered (osl from command line, versus OSLCompiler from file, versus OSLCompiler from buffer). This patch unifies them, and expands with additional heuristics for finding the file.
Also falling out of this is that the build and test scripts are now much more robust to the user not setting $OSLHOME -- a top-level 'make test' will find it all in the build itself. Also, it fixes some cases where osl.imageio.so can't find stdosl.h, and thus would appear inexplicably broken.

More robust finding of stdosl.h

---

src/include/OSL/genclosure.h
src/include/OSL/oslclosure.h
src/include/OSL/oslexec.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

`ubsan` complained that our closure memory accesses were not properly aligned. The previous code wasn't tracking the actual `alignof` that the target struct wanted.
Due to how we pack the user's closure `struct` into the memory of `ClosureComponent`, we can't support arbitrary sizes. But I have at least added some error detection code to check that the user isn't trying to use a struct with wider than usual alignment requirements.
I've nuked the old `alignment` flag to `register_closure` because it wasn't working as intended and was somewhat hard to use (none of the example `test*` programs set it, nor did our renderer).

Fix the handling of alignment for closure structs

---

src/liboslexec/loadshader.cpp

One way you could bump into this is if you
testshade ... test.oso
it would complain about the shader not being found.

Allow shaders to be accidentally specified with trailing .oso

---

.travis.yml
CMakeLists.txt
Makefile
src/build-scripts/build_openimageio.bash
src/build-scripts/install_homebrew_deps.bash
src/cmake/install.cmake

Our TravisCI builds on OSX have been failing for a while and I finally
got a chance to track down the issues.
1. Slight adjustment to ensure that on OSX the rpath is set correctly.
(At least I think it's more "correct" now. Seems to fix some things.)
2. Make sure that on Travis we install the homebrew freetype package,
which is needed for the texture-udim test.
3. Make sure OIIO_LIBRARY_PATH is set to help the osl-imageio test, which
needs to find the osl plugin for OIIO.
4. Also simultaneously depends on a change to OIIO (analogous to the first
item here) to adjust its RPATH behavior slightly on OSX.
None of these things should affect non-OSX builds.
Also, as was recently done to OIIO, add to the wrapper Makefile the
ability to set INSTALL_PREFIX, which is passed along to cmake as …

Fix OSX build problems on TravisCI, support make INSTALL_PREFIX=

---

src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/oslcomp_pvt.h
src/liboslcomp/oslgram.y

Chris discovered that oslc was leaking ASTNode allocations, which was
interfering with some of his sanitizer runs.
Function declarations had the raw pointers squirreled away in the symbol
table without ever keeping a ref-counted version, so they were never
freed. So now we keep a vector of the ref-counted pointers for
ASTfunction_declaration in the OSLCompilerImpl, which all get freed when
the compiler destructs.
Quite independently, we were leaking the nodes associated with certain
metadata, they were just dropped on the floor by the add_meta() method,
which walked through what it was handed and used it to adjust things,
but never freed the pointers. This is fixed by changing add_meta to
force the raw pointers to be converted to ref-counted.
I added some code that for DEBUG builds only …

Fix memory leak of ASTNode's in osl compiler.

---

src/testshade/testshade.cpp

I discovered that while you can pass a parameter that's an int array, float array, etc., string arrays didn't quite work, they were treated as single strings.

testshade: fix to accept array of strings as parameter value

---

CMakeLists.txt
src/doc/languagespec.tex
src/include/OSL/oslversion.h.in
src/liboslcomp/oslcomp.cpp
src/liboslexec/constfold.cpp
src/testrender/simplerend.cpp
src/testrender/simplerend.h
src/testshade/simplerend.cpp
src/testshade/simplerend.h
testsuite/oslc-version/ref/out.txt
testsuite/oslc-version/run.py
testsuite/oslc-version/test.osl

* C++: define OSL_VERSION (10900 for 1.9.0), OSL_VERSION_MAJOR,
OSL_VERSION_MINOR, OSL_VERSION_PATCH.
* osl source at compile time: oslc now pre-defines OSL_VERSION,
OSL_VERSION_MAJOR, OSL_VERSION_MINOR, OSL_VERSION_PATCH.
* osl runtime now supports getattribute("osl:version"), which also
get properly constant folded.
Note that this means that renderers ought to make sure their
implementation of RendererServices::get_attribute detects requests for
"osl:version" and in that case retrieve the integer value of
OSL_VERSION. But in practice, you will only notice a renderer's failure
to do this if you turn off runtime optimization and the constant folding
of the attribute doesn't occur.

Add ways to test OSL version:

---

src/liboslexec/llvm_gen.cpp

When we can detect that the user is passing the empty string as subimage
name to a texture call, there's no need to have the useless call to
osl_texture_set_subimagename.

Improve efficiency for texture (..., "subimage", "")

---

CMakeLists.txt
src/liboslexec/instance.cpp
testsuite/paramval-floatpromotion/ref/out.txt
testsuite/paramval-floatpromotion/run.py
testsuite/paramval-floatpromotion/test.osl

SS::Parameter(), which is used to pass parameter instance values,
is very strict about the types matching exactly. I'm loosening it
somewhat -- by allowing the user to pass a float as the
instance value of a triple (color, point, etc.), and to pass one triple
when a different was the declared parameter. This makes it have similar
flexibility to that afforded by ConnectParameters, and I can't think of
a good reason why one should be any stricter than the other.

Relax the strict typing of ShadingSystem::Parameter()

---

src/doc/languagespec.tex
src/liboslexec/constfold.cpp
src/liboslexec/pointcloud.cpp

In the default RendererServices implementation of retrieving data from
point clouds via Partio, there had to be an exact match between the
attribute type of the point cloud file (as understood by Partio) and the
element type of the OSL array used to store the retrieved data.
Because OSL doesn't support 2D arrays, that means that you could retrieve
only data of the main non-array OSL types: int, float, 3-float (color,
point, vector, normal etc.).
But we had somebody create a point cloud that stored float[4] to store
quaternions (don't ask), and then was unable to retrieve it from OSL,
because there is no float[4] type.
So the solution is that we are loosening the type matching tests.
Simply stated, it's willing to match either a float or a float[n] in the
point cloud, when retrieving into …

More flexibility in pointcloud_search/get retrieval

---

CMakeLists.txt
src/doc/languagespec.tex
src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/codegen.cpp
src/liboslcomp/typecheck.cpp
testsuite/oslc-err-struct-ctr/ref/out.txt
testsuite/oslc-err-struct-ctr/run.py
testsuite/oslc-err-struct-ctr/test.osl
testsuite/struct/ref/out.txt
testsuite/struct/test.osl

You know how you can have an expression for a built-in type like color?
foo = color(1,1,1)
or
void func (color c) { ...}
func (color(1,1,1);
It was really awkward to do this with structs.
So with this patch, for every struct, you can construct it by name
with a function-call-like syntax, where the arguments must be the same
types as the data members of the struct, in order.
For example:
struct RGBA {
color rgb;
float a;
};
RGBA x = RGBA(color(1,1,1), 1);
void func (RGBA x) { ... }
func (RGBA(Cblah,alpha));
You don't need to explicitly declare the constructor like in C++, it
just exists.

Struct constructors work like built-in type constructors.

---

src/liboslexec/shadingsys.cpp

This utility is used by renderers for getattribute and other
renderer-to-OSL data copying, and is meant to facilitate the
obvious set of copy conversions between slightly mismatched yet
sensible types.
Adding a clause that lets you retrieve a triple (point, color, etc.)
even if it was declared on the renderer side as float[3], and vice
versa.

ShadingSystem::convert_value, allow float[3] <--> triple conversion.

---

src/liboslcomp/symtab.cpp
src/liboslexec/typespec.cpp

Just moving these methods from one file to another, so they live with the rest of the methods for the TypeSpec class.

Move TypeSpec::string and c_str from symtab.cpp to typespec.cpp

---

CMakeLists.txt
src/liboslexec/typespec.cpp
testsuite/function-overload-struct/ref/out.txt
testsuite/function-overload-struct/run.py
testsuite/function-overload-struct/test.osl

It was incorrectly saying that two different structs matched! The
problem was a subtle issue of the ordering of clauses in a complex
comparison -- we need to test the structure case first, because the
other clause makes the assumption that the types are simple and not
structures and will have a false positive in that case. An important way
this could manifest is that if you had two overloaded functions whose
arguments were structs, say foo(structA) and foo(structB), it was not
able to correctly distinguish between them for type checking.

Fix bug comparing structure types with equivalent() -- false positive

---

src/testshade/testshade.cpp
testsuite/texture-udim/run.py

A grab-bag of minor testshade improvements:
* Rename command line arguments `--scalest` and `--offsetst` to `--scaleuv` and `--offsetuv`, since what they do is change the u,v range, had nothing to do with anything named "s" or "t". (For compatibility, the old names also still work, but are no longer documented and are considered deprecated.)
* New option `--print` sends to the console the value of all saved outputs. This is useful if you are trying to unit-test or directly inspect the outputs of a shader, without needing 'printf' calls in the shader. Though it's probably not helpful to do this when using -g to produce big output images -- too much console output to be useful.
* When `-o` is outputting to a JPEG, GIF, or PNG file, automatically convert the linear shader output to the sRGB …

testshade improvements

---

src/testrender/testrender.cpp

Just like we recently did for testshade.

testrender: output jpg/gif/png in sRGB

---

src/shaders/stdosl.h
testsuite/geomath/ref/out.txt
testsuite/geomath/test.osl

These functions are declared as builtin in stdosl.h but not implemented anywhere, which leads to errors when executing the shader. This fix implements them in stdosl.h following the OSL specification.
Alternatively, these functions could be removed since no one seems to have missed them until now, I don't really care one way or the other.

Fix missing faceforward() implementation

---

src/liboslexec/typespec.cpp

Change the implementation of TypeSpec::string(), which returns the text
representation of a TypeSpec, so that it prints the name of the struct
rather than just its numerical designation.
An example of the old behavior, as applied to a type checking error
message:
test.osl:10: error: No matching function call to 'max (struct 1, struct 1)'
...
And the new behavior:
test.osl:10: error: No matching function call to 'max (struct vector4, struct vector4)'
...

Improve type checking errors with structs

---

src/liboslcomp/codegen.cpp
testsuite/operator-overloading/test.osl

The recent patch that allows users to specify operator overloading
for structs means that, in this particular spot, the AST node type
that might be passed as the argument to a function might be a binary
or unary expression -- those could never have returned a struct before,
so were not enumerated in the list of nodes of this conditional, causing
an assertion to hit.

Fix oslc assertion when passing stucts with operator overloading.

---

src/testshade/testshade.cpp

--shader is like a combination of --layer, and then naming the shader to create an instance of it.
The reason I prefer --shader is that when you use it, the command line is almost identical to the shader group serialization. So much nicer!
For example:
```
$ testshade -param texturename "grid.tx" \
-shader texturemap tex1 \
-param frequency 4.0 \
-shader noisy noise1 \
-param scale 1.0 \
-shader contrast cont1 \
-shader umixer mix1 \
-connect tex1 out cont1 in \
-connect cont1 out mix1 left \
-connect noise1 out mix1 right \
-g 256 256 -o out noisetex.jpg
```
corresponds very symmetrically to the shader group
```
param texturename "grid.tx" ;
shader texturemap tex1 ;
param frequency 4.0 ;
shader noisy noise1 ;
param scale 1.0 ;
shader contrast cont1 ;
shader umixer mix1 ;
connect tex1.out …
```

testshade --shader <shadername> <layername>

---

src/shaders/stdosl.h

The mixing factor may be either a float or a color, and it blends the
color closures in the obvious way.

Add mix() for color closures

---

src/cmake/compiler.cmake

Since d771ee8 OPENEXR_DLL is defined when LINKSTATIC=ON which I'm guessing was not an intentional change. This restores the behavior before the refactor, fixing a bunch of LNK4217 warnings when building with static IlmBase libraries.
The same fix is needed in OpenImageIO.

Fix IlmBase linker warnings with LINKSTATIC on Windows.

---

src/liboslexec/builtindecl.h

This broke in master in a9c21bdf, there's a runtime error for many OSL shaders when building with USE_LLVM_BITCODE=OFF.

Fix osl_range_check not found error with USE_LLVM_BITCODE=OFF.

---

src/testshade/testshade.cpp

Example:
$ testshade -param x 1.0 test
x=1.0
$ testshade test -param x 1.0
ERROR: Pending parameters without a shader: x
Did you mistakenly put --param after the shader declaration?

testshade: proper error for common mistake with order of --param vs shader

---

src/shaders/MaterialX/CMakeLists.txt
src/shaders/MaterialX/build_materialX_osl.py

No need to SHOUT the type names.
This is all internal to the build system. Users aren't affected.

MaterialX build process: Change all type names to lowercase

---

src/shaders/MaterialX/build_materialX_osl.py

mx build script wasn't properly resetting the mx template after substitution. 
This change copies the template into the var_type scope for each new var_type

fixes var types not substituting properly

---

site/spi/Makefile-bits
src/liboslexec/llvm_util.cpp

Very minor. This is the most minimal LLVM upgrade I can recall.
Note that the changes to Makefile-bits are site-specific to SPI.

Make OSL work with clang5/llvm5

---

src/liboslexec/constfold.cpp
src/liboslexec/shadingsys.cpp

This was never done as a runtime optimization, just never got around to it because % is so rarely used in shaders. But once somebody pointed it out, it was just a few minutes of work.
No new tests need to be added, since % is already tested in the testsuite. If the constant folding doesn't work, testsuite/arithmetic will break.

OSL runtime constant folding of % (modulus)

---

src/liboslexec/instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

This allows a color to be declared as float[3] for example. This may be useful when declaring shaders from systems that do not explicitly keep track of the source data type.

Allow an (optional) slightly more relaxed policy when declaring parameters

---

src/include/CMakeLists.txt
src/liboslexec/CMakeLists.txt

I noticed, doing some unrelated work, that changes to certain header files were not triggering a recompile of llvm_ops.cpp into bitcode.

Make sure that changed headers properly rebuild llvm_ops.cpp bitcode

---

src/include/OSL/dual.h
src/include/OSL/dual_vec.h
src/liboslexec/CMakeLists.txt
src/liboslexec/dual_test.cpp
src/liboslexec/splineimpl.h

In this patch, I completely overhaul the main class that implements our
dual arithmetic-based automatic differentiation. No more Dual2, with
hard-coded x and y partials. Now we have Dual<T,P>, templated on the
number of partial dimensions P. Now Dual2<T> is just a templated typedef
that specilizes to 2 dimensions.
In addition to general cleanup, this leads to several benefits:
1. It is now trivial to extend to 3 dimensions (dx, dy, dz) if we wanted
to use Dual for automatic differentiation of volumetric functions.
2. Dual<T,1> can be used for automatic differentiation of 1-D functions,
which doesn't have any applications within OSL that I'm aware of, but
makes it a whole lot more convenient to re-use outside of OSL, any time
you want to use A.D. with these techniques.
3. It sets us up for …

Dual refactor and generalization

---

src/liboslcomp/symtab.cpp
src/liboslexec/typespec.cpp

This is a back-port of a fix that went into master a long time ago, and seems to fix some reported bugs in RB-1.8.
Turns out that in addition to making nicer error printing (its original use, per the commit message), it also fixes a bug wherein use of arraylength() on an *array of struct* resulted in generated code that would make a confusing error message in `oslinfo/oslquery`.
Sorry for the confusing diffs; the function is changing a bit, in addition to moving from file to file.
----
Change the implementation of TypeSpec::string(), which returns the text
representation of a TypeSpec, so that it prints the name of the struct
rather than just its numerical designation.
An example of the old behavior, as applied to a type checking error
message:
test.osl:10: error: No matching function …

Improve type checking errors with structs (#761)

---

src/liboslcomp/osllex.l
src/liboslexec/constfold.cpp
src/liboslexec/dictionary.cpp
src/liboslexec/opstring.cpp
src/liboslexec/osolex.l
src/liboslexec/shadingsys.cpp
src/testrender/testrender.cpp
src/testshade/testshade.cpp

@marsupial correctly points out that we are unsafely passing
a string_view.data() into both atoi and strchr, which is unsafe because
there's no guarantee that a string_view is null-terminated. Ugh!
He proposed a fix here: https://github.com/imageworks/OpenShadingLanguage/pull/800
and there's nothing wrong with it per se, but I suspected it could be done
more simply, so this PR is my stab at it, using the `OIIO::Strutil::parse_*`
functions.

Fixes to ShadingSystemImpl::decode_connected_param

---

src/liboslcomp/oslcomp.cpp
src/liboslcomp/osllex.l
src/liboslexec/instance.cpp
src/liboslexec/osolex.l
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp
src/oslc/oslcmain.cpp
src/oslinfo/oslinfo.cpp

I got quite the education this week, realizing just how much of C++'s I/O functionality implicitly takes the system's "locale" into consideration.  Of particular concern is the conversion of text to floating point numeric values and vice versa, for which much C++ functionality will happily swap the role of '.' and, say, ',' (comma) for the decimal mark, depending on the user's country and whether they are savvy enough to set their locale to the classic "C" (essentially US-style) version. On the other hand, who can blame somebody for not blindly accepting US hegemony these days?
But dammit, OSL is a programming language, and so '.' has a specific role in numeric constants and ',' does something quite different (comma operator!), and if you start mixing up the two when parsing programs, it …

Sort out locales for OSL

---

src/liboslcomp/osllex.l
src/liboslexec/osolex.l

We can't fix the code -- it's not "our" code, it it's the stuff
generated as part of the build process by flex itself. The expedient
thing is to just suppress the warning in the flex-generated module.

Suppress gcc7 warning about signed vs unsigned compare.

---

.travis.yml
src/liboslexec/instance.cpp
src/testshade/testshade.cpp

OSL's Travis tests build against OIIO master and release. A couple months ago when OIIO changed release from 1.7 to 1.8, that resulted in our no longer testing directly against OIIO 1.7, and a few incompatibilities creeped in despite our advertising that OIIO 1.9 ought to be compatible with OIIO >= 1.7.
This patch fixes those things, as well as adding an explicit test vs OIIO 1.7 to our Travis test matrix.

Restore support for OIIO 1.7

---

.travis.yml
CHANGES.md
INSTALL.md
src/cmake/externalpackages.cmake
src/liboslcomp/oslcomp.cpp
src/liboslexec/llvm_util.cpp

This cleans up a lot of #if cases where we were trying to support a very
wide range of LLVM releases in the face of changing APIs. With 3.5 gone,
so too is the "old" JIT (it's all MCJIT now).
By the time we get around to the next major release, we may further
reduce the complexity by dropping support for 3.9 (i.e., minimum LLVM >=
4.0), but I'll leave that for a later review.
Also tweak the Travis settings to assure we test against all the supported
LLVM releases.

Bump LLVM minimum from 3.5 to 3.9.

---

src/liboslcomp/typecheck.cpp

Functions that take optional argument lists in token/value form, like `texture` or `pointcloud_search` needed to mark just those value references as "writeable" that are (for example, the one following "alpha" for texture calls, but all of the optional value slots for pointcloud_search).
The logic on the oslc side here was broken -- it worked when the token was a string literal, but when it was a variable whose value wouldn't be known until runtime, it was failing to mark it as writeable, whereas the correct thing to do is to conservatively conclude that it *might* be written to (we don't know yet) and mark it as such.
The cascade of errors could lead to incorrect runtime optimization, if the only used output of the function call was one of these parameters that failed to be marked as an …

oslc: Fix param write analysis bug for token/value optional arguments

---

src/liboslcomp/osllex.l

Doesn't matter much from the command line, but when compiling in memory
with OSLCompiler, you don't want the errors leaking into stderr.
Sorry, a few tab/space changes snuck into the diff.

oslc internals: Police up some uses of stderr -- use the error handler

---

src/include/OSL/oslexec.h
src/liboslexec/loadshader.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

Default is 0, for old behavior in which it's an error for
LoadMemoryCompiledShader to try to load the same named shader more than
once.
If set to nonzero, this is allowed, replacing the old shader master.
This does not change any already declared shader groups, which
will continue to use the original definition at the time of their
declaration. But subsequent groups that reference the master will get
the latest one.

ShadingSystem option "allow_shader_replacement"

---

src/cmake/modules/FindPugiXML.cmake

Without this, certain build / change cmake / rebuild cycles could give
cmake errors instead of correctly re-finding the pugi files.

FindPugiXML.cmake touchup -- make robust to re-builds

---

src/include/OSL/oslclosure.h
src/include/OSL/oslconfig.h
src/liboslexec/oslexec_pvt.h

In #740 the `alignment` parameter was removed from `register_closure`. This was originally added in bcaf5778, and Cycles still needs 16 bytes alignment for SSE types, while it is fixed to 8 bytes in OSL master now.
This patch uses the simple solution of enforcing 16 byte alignment for `ClosureComponent.mem`, under the assumption that in practice this is the most alignment you need on x86.
Alternatively the `alignment` parameter could be added back. Maybe in theory someone might care about 32 byte alignment for AVX. In practice I guess it's not so likely since alignment is only required for older CPUs that don't support unaligned loads well.

Fix ClosureComponent to work with SSE alignment requirements

---

src/include/OSL/dual.h
src/liboslexec/oslexec_pvt.h

There were a couple of compilation failures on VisualStudio 2015 (64-bit community edition tested) with the latest 1.9 code. This patch is to address those. Specifics are detailed in the commit messages.
I ran the render-cornell test using testrender.exe after a successful build, comparing the generated .exr with previous versions of OSL on Windows (comparable results).
- [N/A ] I have updated the documentation, if applicable.
- [N/A] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).

VisualStudio 2015 x64 compilation fixes for 1.9.x

---

src/liboslcomp/ast.cpp

Fixes edge case of building debug OSL 1.9 against OIIO 1.7. Affected Windows, Linux and macOS, as tested.
OIIO 1.8's atomic.h unconditionally includes <atomic>, and defines Strutil::printf.
I wasn't sure of the best alternative to Strutil::printf in OIIO 1.7, so went with just using printf as a fallback.
Also, I couldn't see a macro to generate an OIIO version number as an integer, so went for duplicating what's in oiioversion.h.in.
I haven't seen any replies to my post on OSL developers to see if anyone would use this combination, but I thought I'd submit this for completeness.
Built debug on all three platforms. Tested render-cornell.
- [N/A] I have updated the documentation, if applicable.

Fix to compile OSL debug against OIIO-1.7.x.

---

src/include/OSL/oslquery.h
src/include/osl_pvt.h
src/liboslexec/shadingsys.cpp
src/liboslquery/oslquery.cpp

* OSLQuery::Parameter -- add copy/move constructors
* Make the ShadingSystem side of OSLQuery correctly report default vals.

OSLQuery improvements

---

.travis.yml
CHANGES.md
INSTALL.md
src/cmake/externalpackages.cmake

OSL 1.9 will of course remain compatible with OIIO 1.7.

Bump minimum OIIO dependency to 1.8 (master only)

---

src/liboslcomp/ast.cpp

I missed this in the last PR I made.
Fixes compiler error (AppleClang,Gcc) in using std::atomic values as printf arguments.
Compiler error in AppleClang (Xcode8) is
```
/Users/mark/dev/Thirdparty/OSL-1.9/src/liboslcomp/ast.cpp:76:33: error: call to implicitly-deleted copy constructor of 'std::atomic<int>'
i, node_counts[i], node_counts_peak[i]);
^~~~~~~~~~~~~~
```
Compiler error in Gcc (4.8) is
```
/home/mark/dev/Thirdparty/OSL-1.9/src/liboslcomp/ast.cpp:76:68: error: use of deleted function ‘std::atomic<int>::atomic(const std::atomic<int>&)’
i, node_counts[i], node_counts_peak[i]);
^
```
Believe this is a problem because printf accepts arguments by value, whereas OIIO 1.8's Strutil::printf takes by reference, and you can't copy a std::atomic.
Compiled this change with MSVC, AppleClang …

Improved compatibility of OSL 1.9 debug against OIIO 1.7.x

---

src/liboslexec/optexture.cpp

The code was all prepared to do this, but for some reason we always passed `NULL`. This means the carefully pre-generated texture thread handles were not getting used.

Pass the context's texture_thread_info to the render services texture callbacks instead of always passing NULL

---

src/include/OSL/llvm_util.h
src/include/OSL/oslexec.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
testsuite/array-range/ref/out-alt.txt
testsuite/array-range/ref/out.txt
testsuite/component-range/ref/out-alt.txt
testsuite/component-range/ref/out.txt
testsuite/debug-uninit/ref/out-opt2.txt
testsuite/debug-uninit/ref/out.txt
testsuite/testshade-expr/ref/out.txt

* Add a new shadingsys option "llvm_optput_bitcode" that will dump the
bitcode for each group, even if the other debug options aren't turned all
the way on.
* bitcode now dumps in text as well as binary. (It saves a step of running
"llvm-dis" if your goal is just ot see the text in the first place, and also
it helps the llvm bug where sometimes it refuses to work because of mismatched
version strings.)
* Make sure that both in the bitcode output and other debug symbols,
we are more careful about being sure the shader group name is included,
not just the layer name, and also if a layer name is not specified to
ss->Shader(), make one up based on the shader master name and the
layer number.

Some bitcode and symbol debugging aids

---

site/spi/Makefile-bits
src/liboslexec/llvm_util.cpp

This also bumps the version of llvm we're using at SPI, that part won't affect anyone else.

Enable symbols in the JIT for the Intel Vtune profiler

---

src/include/OSL/oslexec.h
src/include/OSL/rendererservices.h
src/liboslexec/rendservices.cpp
src/liboslexec/shadingsys.cpp

Remove a method that has been deprecated since OSL 1.6, and mark some
methods that were deprecated since 1.8 with the OSL_DEPRECATED warning.

Adjust deprecations

---

src/liboslexec/instance.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/oslexec_pvt.h

* Better guaranteed unique naming of missing names.
* When dumping ll/bc files for debugging to filenames derived from the
group name, beware group names that have slashes in them! Also,
sheesh, watch out for group names that are so long that they exceed
the longest filename allowed (256 chars for most modern filesystems).
* Decided only the ll files are useful for debugging, I don't think we
need the binary bc files, so I removed the bc output.
* Simplify ShaderGroup ctr by using C++11 data member defaults and
delegating constructors.

Fixes to group names and debug bitcode output

---

CMakeLists.txt
src/liboslcomp/ast.cpp
src/liboslcomp/codegen.cpp
testsuite/oslc-err-field/ref/out.txt
testsuite/oslc-err-field/run.py
testsuite/oslc-err-field/test.osl

Attempting to access a non existent field on struct or type will crash oslc:
```
shader test ()
{
color c = color(4,3,2);
printf("c.nope: %g\n", c.nope);
}
```
**testsuite/oslc-err-field/test.osl**
- [x ] My code follows the prevailing code style of this project.

Fix oslc crash with invalid field selection.

---

src/oslc/oslcmain.cpp

oslc command line arguments placed after the shader path are ignored.
Indeed, the compilation is triggered just after encountering the supposed shader path.
This PR handles that case.
That's true that the documentation says put `options` before `file`, but it could be nice to get the similar behavior of some unix commands.  
testsuite/oslc-D
testsuite/oslc-comma
testsuite/oslc-empty
testsuite/oslc-err-arrayindex
testsuite/oslc-err-closuremul
testsuite/oslc-err-field
testsuite/oslc-err-format
testsuite/oslc-err-intoverflow
testsuite/oslc-err-noreturn
testsuite/oslc-err-notfunc
testsuite/oslc-err-outputparamvararray
testsuite/oslc-err-paramdefault
testsuite/oslc-err-struct-array-init
testsuite/oslc-err-struct-ctr
testsuite/oslc-err-struct-dup
testsuite/oslc-variadic-macro …

oslc: handle args if the shader file is not the last argument

---

CMakeLists.txt
src/liboslcomp/ast.h
src/liboslcomp/typecheck.cpp
testsuite/function-overloads/a_fcn.h
testsuite/function-overloads/a_ivp.h
testsuite/function-overloads/b_nci.h
testsuite/function-overloads/b_vpf.h
testsuite/function-overloads/c_cnf.h
testsuite/function-overloads/c_vpi.h
testsuite/function-overloads/ref/out.txt
testsuite/function-overloads/run.py
testsuite/function-overloads/test.osl

OSL currently does not define how function overloads are chosen very well.
As such **oslc** can choose different overloads depending on the order of declaration.
This attempts to define how overloads are chosen in a more concrete way by scoring:
1. all arguments match without conversion
2. prefer promotion of int -> float over float -> int
3. use return type to resolve any possible ambiguities
**testsuite/function-overloads**

Fix poorly defined behavior when choosing certain function overloads.

---

CMakeLists.txt
src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/oslgram.y
src/shaders/color2.h
src/shaders/stdosl.h
testsuite/oslc-err-funcredef/ref/out.txt
testsuite/oslc-err-funcredef/run.py
testsuite/oslc-err-funcredef/test.osl

Previously, if you for some reason defined two identical functions in
the same scope (including redefining a "built-in" function exactly in
the outermost scope), it would just silently accept it, and then you
wouldn't be sure which one would actually end up getting called.
Now it's an outright error.

oslc: Add error detection of duplicate functions in the same scope.

---

src/shaders/stdosl.h

When I committed #746, in which I made double declarations of user functions to be a warning, I changed some declarations to remove duplicates in stdosl.h, not realizing that there was some overloading resolution logic that was order dependent (as was so astutely pointed out and attempted to be solved by Marsupial in #837) and that I was inadvertently *depending* on the redundant declaration to get it right.
Ugh, so I broke it, then Marsupial's patch fixed it. Then Marsupial discovered some problems (not this!) with his patch and we reverted it, thus re-introducing the bug.
I'm reviewing another attempt to fix the order dependency problem once and for all (#844), but in the mean time, this fix to stdosl.h fixes the pow and fmod cases that are broken at the moment.

Fix slightly broken overload resolution

---

src/liboslcomp/ast.cpp
src/liboslcomp/oslcomp.cpp

Minor fixes that #836, #838, & #839 depend on that are less intrusive/controversial:
- `ASTfunction_call::m_poly` can possibly be left uninitialized.
- Duplicate/redefined functions are being silently ignored.
- Preprocessing with boost::wave is currently inserting whitespace into the _.osl_ source.
Yes

Minor fixes

---

src/cmake/compiler.cmake

This makes it safe so that if we want to disable -Wall by default for *release* branches as part of the branching prep process (but never master!), we'll still catch any new warnings on the CI builds.

Force -Wall on Travis builds

---

CMakeLists.txt
src/liboslcomp/typecheck.cpp

I think the merge caused a renamed test to not be removed in CMake.
Also fixes Windows strcasecmp usage.

Minor fixes to recent changes.

---

CHANGES.md
CMakeLists.txt
src/include/osl_pvt.h
src/liboslexec/loadshader.cpp
src/liboslexec/shadingsys.cpp
src/testshade/testshade.cpp
testsuite/allowconnect-err/a.osl
testsuite/allowconnect-err/b.osl
testsuite/allowconnect-err/ref/out.txt
testsuite/allowconnect-err/run.py
testsuite/missing-shader/ref/out.txt
testsuite/missing-shader/run.py

If a shader input parameter has this metadata present and set to
nonzero, no incoming connections via ConnectShaders() will be accepted,
resulting in a runtime error if it is attempted.

Shader parameter metadata [[ int allowconnect = 0 ]]

---

src/include/OSL/oslquery.h
src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h
src/liboslexec/instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.h
src/osl.imageio/oslinput.cpp
src/testshade/testshade.cpp

For some time, the current master had advertised that it requires OIIO >= 1.8. This patch simplify code by removing #if clauses related to OIIO versions older than that.

Tweak OIIO related deprecations

---

src/liboslcomp/typecheck.cpp
testsuite/function-overloads/ref/out.txt
testsuite/function-overloads/test.osl
testsuite/oslc-err-funcoverload/ref/out.txt
testsuite/oslc-err-funcoverload/test.osl

Fixes [hopefully] all remaining undefined behavior from return type disambiguation.
Adds color closures, structs, and void to the defined precedence order of resolving via return type.
Errors when disambiguating via return type and more than one user struct is a match.
###
Opted for the order:
**float, int, color, vector, point, normal, matrix, string, color closure, struct, void**
Should be no behavioral change against prior PR except in cases where behavior was undefined.
(i.e. color closure, struct, void were all previously sorted last as well)

Fix remaining undefined behavior from ambiguous function returns

---

src/liboslcomp/oslcomp_pvt.h
src/liboslcomp/typecheck.cpp

The most important change here is to modify the practice making
multi-line warnings/errors by issuing a warning/error for the first line
followed by message() calls for the subsequent line.  Instead, we
generate those line-by-line messages as strings, and at the very end
issue a single warning or error call.
Also, directly call m_compiler->warning or error, don't bypass the
compiler by calling the app's error handler.
The reason both of those are important is that I have a separate change
I am ready to submit that is about giving a `#pragma nowarn` that can be
used to suppress warnings on the following line. This is totally borked
by warnings that span multiple calls and where most of their output is
in the form of message() and thus aren't easily recognized as part of
the warning.
This …

Warning fixes and general cleanup to recently added typecheck code

---

src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/oslgram.y

For many grammatical constructs, the "source line" recorded in the AST
node is where the grammatical case ENDS. As an example,
1:  shader foo (int holdout
2:                    =
3:                    1)
4:  { }
There is a warning because 'holdout' masks another symbol at the same
scope. You would think the warning should be reported as occurring on
line 1, but it is reported for line 3, because that's where the clause
ends.
This will tend to happen for grammatical constructs that look like
ANCHOR potentially-long-expression-that-may-span-lines
where any sensible person would want the warning associated this to be
on the line of the anchor, not wherever the long expression happens to
end.
In this patch, I carefully fix a whole lot of these grammatical
constructs to patch the 'sourceline' …

Improve oslc error reporting

---

CHANGES.md
CMakeLists.txt
README.md
src/doc/languagespec.tex
src/include/osl_pvt.h
src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslgram.y
src/shaders/oslutil.h
testsuite/oslc-err-write-nonoutput/ref/out.txt
testsuite/oslc-err-write-nonoutput/run.py
testsuite/oslc-err-write-nonoutput/test.osl
testsuite/struct-array-mixture/test.osl

It has been a longstanding problem that oslc did not properly flag
attempts to write to function paramseters that were not marked as
'output'.
I've rigged this so that in the current master (and any past releases,
assuming we backport this to release branches), it will just be a
warning. In future versions, it will be a full error. That should give
people some advanced warning (no pun intended) to fix any problems that
this catches that previously went unnoticed.

Errors for writing to read-only function parameters or globals

---

CHANGES.md
src/include/OSL/oslexec.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
testsuite/error-dupes/ref/out.txt
testsuite/error-dupes/run.py

Previously, exactly identical error and warning messages (including from shaders themselves) printed the first time and suppressed the duplicates. The rationale is that an error in a shader could easily turn into thousands of error messages if duplicates weren't suppressed. There wasn't a way to turn this behavior off.
Now it's controlled by ShadingSystem attribute "error_repeats", an int, which has default value 0 (do not issue repeated errors -- the current behavior). If changed to 1, repeated errors and warnings will be allowed to pass to the error handler, without suppression in the ShadingSystem.
Furthermore, the act of setting the attribute (to either 0 or 1) has the side effect of clearing the list of remembered errors. This means that even if you want error suppression, poking it …

SS attrib "error_repeats" controls suppression of repeat errors & warnings

---

src/include/OSL/rendererservices.h

Allowing the base class to be used as a trivial RendererServices, can
be helpful for certain applications where not much renderer functionality
is needed.

RendererServices: make non-abstract

---

src/cmake/flexbison.cmake

The windows version of flex needs the --wincompat flag set.

Flex --wincompat patch

---

src/liboslexec/instance.cpp

If you tried to pass in something like:
`float[9] values 1 0 0 0 1 0 0 0 1`
To a shader that had `color values[]` declared, OSL would understand that as:
`color[9] values ...`
Instead of the expected:
`color[3] values ...`
This only comes up if you are using relaxed type checking of course.

Fix incorrect array length on unbounded arrays specified via relaxed parameter type checking

---

src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/oslgram.y

If you have something like
float table[65536] = { 0.1, 0.35, -0.72, ... }
This might take TENS of seconds for oslc to parse, because the mechanics
of how that long list of values is parsed -- it involves a singly-linked
list of ASTNodes, and with each new one, we are appending to the far end
of the linked list. This leads to an O(n^2) parsing time, where n is the
length of the list.
The straightforward (but wrong!) way to fix it is to change the Bison
grammar for init_expression_list from "left-recursive" to "right-recursive".
That makes it natural to prepend items (O(1)) to the accumulating list,
but it's very inefficient for Bison and can overrun Bison's fixed-size
parsing stack. Bison docs discurage use of right-recursion in grammars,
since left-recursion grammar can parse arbitrarily …

Speed up parsing of long initializer lists.

---

src/liboslexec/serialize-bc.bash

Not every system has bash installed in /usr using env to call bash is a better cross platform method.

Remove use of a fixed path to call bash

---

src/osltoy/osltoyapp.cpp
src/osltoy/osltoyapp.h

'Pause' (which changes its label to 'continue' when paused) stops the
clock and continued execution of the shader, until 'continue' is hit.
'Reset' sets the time counter back to 0.0 again.
It starts in a paused state, and starts the clock the first time you
successfully compile a shader.

osltoy: add 'pause' and 'reset' buttons

---

src/testrender/testrender.cpp

A suspicious line in testrender seems to depend on undefined behavior
regarding the specific order of evaluation of quantities in a math expression.
It has been there forever, but only seems to fail on certain builds of gcc 5
and possibly clang 7.
It's just a one-line fix to remove the order-of-evaluation ambiguity.
Thanks, Tim Grant, for pointing this out!

Fix testrender bug with undefined order of operations

---

src/liboslcomp/typecheck.cpp
src/liboslexec/loadshader.cpp

For these functions, oslc failed to mark the results output param as write only.
Fix the bug in oslc, and also put in a provision in loadshader that will correct the old already-compiled incorrect files.
Thanks to Steena Monteiro from Intel for pointing this out!

Fix oslc read/write error for regex_search/regex_match

---

.travis.yml
src/liboslexec/loadshader.cpp

This is hoped to relieve 3DSMax users of some unexplained crashes in
this section of code. (We can't reproduce, we're making our best guess.)
Related to a more extensive change under review in master (923), which
backports straightforwardly to OSL 1.9, but for this backport to OSL
1.8, we need to accommodate much older OIIO so we are more focused
here. (The other, more permanent, overhaul of this section of code
relies on string parsing that was part of OIIO 1.7, but OSL 1.8 must be
compatible with OIIO 1.6.)

Defensive parsing of hints in oso files

---

src/liboslexec/loadshader.cpp

Zap is seeing sporadic (but frustraingly impossible to reproduce) crash
reports from inside this function, specifically in the part that parses
%argrw hints.
There was a longstanding comment:   // FIXME -- use string_view ops here
So, sure, rewrite the whole thing using string_view and Strutil::parse
functions, and remove the assertions, and put extra guards to make sure
we aren't acessing a symbol or op (via blah.back()) if there aren't any
in the vector yet, and pretty much just let it ignore or be robust to any
malformed hints.
I've never seen a repro case, so I don't know that this will fix it, but
it's programmed a lot more defensively now, so hopefully there will be
no further crashes (after I backport this to whatever version Zap is
using).  I even put in an error message for a …

Rewrite OSOReaderToMaster::hint

---

src/include/OSL/oslexec.h
src/liboslexec/loadshader.cpp

New rules:
* If NO "searchpath:shader" attribute is specified to the ShadingSystem,
the current working directory (".") will be searched.
* If a searchpath is specified, it will look ONLY in those directories,
in order. The current working directory will only be searched if
it is listed among the paths.

Change to search path rules for .oso files

---

.travis.yml
src/build-scripts/install_homebrew_deps.bash
src/osltoy/osltoyapp.cpp

Recent changes used a new ImageBufAlgo convention only present in current
OIIO master, not older 1.8 that we still promise compatibility with.
Didn't catch this before because the Travis tests don't install qt and
therefore don't build osltoy at all. Add qt to the Mac travis setup so
that it at least builds to prevent this from happening.

Fixes to make recent osltoy changes not break against OIIO 1.8

---

site/spi/Makefile-bits

Default Makefiles build to use vanilla boost.
Remove filesytem and wave from link flags, which seem no longer necessary.

Default to use vanilla boost

---

src/liboslcomp/oslcomp.cpp
src/liboslexec/backendllvm.cpp
src/liboslexec/constfold.cpp
src/liboslexec/context.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/loadshader.cpp
src/liboslexec/master.cpp
src/liboslexec/pointcloud.cpp
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp
src/osltoy/osltoyapp.cpp

OIIO's ustring has an "operator int()" that is possibly ill-advised, as
claimed by Thiago Ize and John Haddon from an oiio-dev thread from back
in 2015 (I'm doing some old thread necromancy). They claimed that an
operator int (or for that matter bool) could result in subtle bugs from
type conversions you don't expect to happen.  The fact that there's no
equivalent operator int/bool for std::string or std::string_view
bolsters their argument.
I started off just trying to eliminate all OSL uses that assume this
operator would work (the proper idiom is simply `!str.empty()`). Along the
way, I found *TWO* bugs related to this -- one in osltoy and one
when constant folding "wrap" arguments to texture functions! So Thiago
and John were surely right, and I am appropriately chastened and …

Wean ourselves off of 'operator int' of ustring, and bug fixes

---

src/liboslexec/builtindecl.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/optexture.cpp

One side was trying to make use of dresultdz while the llvm codegen was always providing nullptr. Since the shading system only supports Dual2 at the moment for derivative lookups, it seems more consistent to forget about trying to come up with a meaningful Z derivative for the time being.

Fix texture3d lookups with derivatives

---

src/include/OSL/oslquery.h

On Windows, osltoy fails to link because of a missing OSLQuery::Parameter constructor. Even when a class is properly exported, nested structs or classes within this class must be exported too.
Just made myself sure it compiles and links :-^

Export struct OSLQuery::Parameter for Windows

---

src/include/OSL/oslexec.h
src/liboslexec/shadingsys.cpp

Just mirror the conversions allowed for float[2] and float[3] types for float[4] 
I'm not seeing a test-harness where I can..?

Allow type conversion to float[4] in ShadingSystem::convert_value

---

src/liboslexec/shadingsys.cpp

Admittedly a fairly unlikely occurrence, but `ShadingSystem::convert_value` could lead to undefined behaviour if src & dst overlap.

Use memmove as dst & src may overlap

---

src/liboslcomp/ast.cpp
src/liboslcomp/oslcomp.cpp
testsuite/oslc-err-write-nonoutput/ref/out.txt

It was never supposed to be allowed. It used to be ignored in most
cases, error neither detected nor issued. PR #878 "fixed" it to detect
the error. But there were too many shaders that did it, users are
confused and it breaks things.
So this patch downgrades it from an error to a warning. If you ignore
the warning, you get what you deserve (which is probably not
bad... people lived with it for years). Anybody who wants it to be fully
illegal can always compile with -Werror to turn warnings in to full
errors.
I also "uniformized" two separate error messages on the same general
topic, so they look the same.

Demote writing to non-output function parameters to be a warning.

---

src/liboslcomp/codegen.cpp
src/liboslcomp/oslcomp.cpp

%.9g is needed to totally guarantee full precision preservation for all
possible float32 values.

Change %.8g formatting to %.9g

---

src/liboslexec/shadingsys.cpp
src/testoptix/testoptix.cpp

I didn't notice this in Tim's code before today, but he made the
retrieval of these group attributes more complex than they needed to be.
Instead of messing with pointers (which we avoid), you can just directly
getattribute(name,string&). So now we use that. Also eliminate group_name
entirely, since it's redundant with the existing groupname.

Fix group_name, group_init_name, group_entry_name

---

src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
testsuite/breakcont/ref/out.txt
testsuite/breakcont/test.osl

An empty conditional clause of a `for` statement was leading to bad
things. It's understood that `for (;;)` means `for (;1;)`, so just
make sure that happens when parsing.
Fixes #688

oslc: Fix crash when encountering `for (;;)`

---

src/liboslcomp/codegen.cpp
testsuite/loop/ref/out.txt
testsuite/loop/test.osl

The problem was specific to using an integer variable directly as the
loop test, rather than a comparison. So for example, this would work
fine:
i = 3;
while (i > 0) {
--i;
}
But this would loop forever:
i = 3;
while (i) {
--i;
}
Because of a hilarious chain of events, this would eventually lead to
the optimizer thinking that since the value of i was nonzero at the
beginning of the loop, it must be equivalent to while(1). There was a
subtle assumption that the scope of the loop control variable would be
entirey inside the condition code. That was true of the the temporary
created to hold the result of "i > 0", but not true of the direct use of
i itself.  The solution is to force it to create a bool comparison
(which turns into the same machine code later anyway, so there is no
efficiency …

Fix bug in oslc loop code generation

---

CMakeLists.txt
src/build-scripts/hidesymbols.map

I guess everbody who builds with NAMESPACE=... to customize OSL's namespace
must (like we do) pick a name that include the substring "OSL".
Because if they don't... a bunch of public API symbols will be improperly
hidden!
Oops. Seems like the most foolproof solution is that if a custom namespace
is supplied that doesn't include the substring "OSL", have the build
script prepend "OSL_". Then the symbol hiding regex will work.
(You may object: "But then you're not using exactly what they asked for!"
Correct, but remember we are already overriding their literal choice by
automatically appending the OSL version number as well.)
While there, also take care to hide symbols containing "pvt", which I
think should not be exposed, despite the fact that they're in the main
OSL namespace.

Fix custom namespace vs symbol hiding clash

---

src/include/OSL/oslcomp.h
src/include/OSL/rendererservices.h
src/liboslexec/rendservices.cpp

These were marked as deprecated in 1.8. The latest release is 1.10. Let's remove it from master.

Remove long-deprecated methods

---

.travis.yml
src/include/OSL/oslconfig.h
src/include/OSL/oslquery.h
src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/codegen.cpp
src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h
src/liboslcomp/symtab.cpp
src/liboslcomp/typecheck.cpp
src/liboslexec/automata.cpp
src/liboslexec/backendllvm.cpp
src/liboslexec/backendllvm.h
src/liboslexec/constfold.cpp
src/liboslexec/instance.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvmutil_test.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
src/liboslexec/shadingsys.cpp
src/liboslexec/typespec.cpp
src/liboslnoise/oslnoise_test.cpp
src/osl.imageio/oslinput.cpp
src/osltoy/osltoyapp.cpp
src/osltoy/qtutils.h
src/testshade/testshade.cpp

This is related to OIIO 2.0 adding a new "sprintf" function that currently is a synonym for "format", but we anticipate that format will one day be modified to conform to an upcoming C++20 std::format that uses a different notation for formatting commands (more like python string formatting, quite nice).
In oslconfig.h, if the version of OSL is too old to have sprintf, define it as a synonym for format.

Change all calls to Strutil::format to Strutil::sprintf

---

src/liboslcomp/oslcomp.cpp
src/liboslcomp/osllex.l

Fixes #654.
There's a problem with the lock we use to protect the global
`oslcompiler` pointer -- it's locked for the duration `osl_parse_buffer`
(where it's assigned), but it is used and also cleared to NULL after the
lock is released (in particular, the clearing that happens in compile()
and compile_buffer().
The solution is to move the lock itself to compile/compile_buffer, and
do all of the assignment, use, and clear within the scope of that lock.
I think this went unnoticed for so long because most of us highly
multithread the shader execution (and runtime optimization), but not the
initial compilation -- except for Issue #654, and my sincere apologies for
letting that slip through the cracks.

Improve thread safety of OSLCompiler

---

src/include/OSL/oslexec.h
src/liboslexec/context.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadeimage.cpp
src/liboslexec/shadingsys.cpp
src/testrender/testrender.cpp
src/testshade/testshade.cpp

There were a variety of places that took a Context* that defaulted
to null, where passing null means to let the called funtion allocate
a context.
This relies on a boost::thread_specific_pointer which could be easily
mishandled and lead to problems.
So with this patch, we move toward requiring the app to allocate and
own the contexts and PerThreadInfo objects.
* No more default null parameter value on contexts or threadinfo.
* Explicitly passing nullptr will still work (use with caution!) on
2.0 with a warning, but will be a full error in 2.1 as that functionality
is totally removed.
* execute() takes a ShadingContext& instead of ShadingConext*, to emphasize
that it must not be null. (For 2.0, the pointer one will still exist
and work, but is slated for deprecation.)
* Fixed comments that …

Deprecate the auto-allocation of contexts and per-thread-info

---

src/liboslexec/lpeparse.cpp

This is not useful in practice and we've seen a case of exponential DFA
state blowup in issue #971 because of its accidental use. This does not
make LPEs totally robust to ReDoS but prevents this particular mistake.

Forbid LPE repetitions inside groups

---

src/cmake/modules/FindLLVM.cmake
src/liboslexec/CMakeLists.txt
src/shaders/MaterialX/CMakeLists.txt

In particular, some system distributions bundle everything in one
libLLVM, without a separate libLLVMMCJIT.

FindLLVM: Make more robust to library configuration of llvm

---

src/cmake/externalpackages.cmake

I needed this on my end to make Cuda 9 and 9.1 work.

OptiX: always seem to need --cuda-path flag, even for cuda 9

---

src/cmake/flexbison.cmake

Rely on CMake's own finding of flex/bison, simplifying our code to
just the helpful shortcut macro. Also make finding these REQUIRED,
which makes an easier-to-interpret error message than simply not
defining the macro.

Simplify flex/bison handling

---

src/liboslcomp/oslgram.y
src/liboslcomp/typecheck.cpp
testsuite/oslc-comma/comma.osl
testsuite/oslc-comma/ref/out.txt
testsuite/oslc-warn-commainit/ref/out.txt
testsuite/oslc-warn-commainit/test.osl

We previously had warnings that attempted to catch mistakes in using
the "comma operator" when the user intended an "aggregate type
constructor", for example:
color x = (a, b, c);    // comma operator! equivalent to: x = c;
color x = color(a,b,c); // this is what they probably meant
However, the way we implemented the warning was specific to assignment:
x = (a, b, c);
and variable declaration with initialization:
color x = (a, b, c);
But it missed similar bugs in other constructs, for example
color x = Cdiffuse * (a, b, c);
Here the user surely intends to multiply Cdiffuse channel-by-channel
with color(a,b,c), but what they will actually get is Cfiffuse scaled
by float c.
This patch changes the strategy for this warning, no longer tied to
variable declaration or assignment, but more …

Improve warnings about ill-advised use of comma operator

---

src/testoptix/testoptix.cpp
src/testrender/testrender.cpp
src/testshade/testshade.cpp
testsuite/testoptix-noise/run.py
testsuite/testoptix/run.py

* Change -r to -res to match testrender (and for that matter, make -res
work for testshade, not -g). (In both cases, the old oddballs are
silent synonyms.)
* Respond to several additional OSL options, and set them the same
was as testrender
* Allow --iters (much like it works in testshade) to make it easy to
run all the rays many times to make accurate timing easier.
* Do some of synchronizing of near-identical code between
testshade, testrender, and testoptix. And synchronize some of the
analogous command line arguments (e.g., -res for everybody, not -res
for testrender and -r for testoptix and -g for testsahde).
* Add empty `OPTIMIZEONLY` marker files in the optix test directories
to signify that they don't need -O0 test cases run (currently, such tests
will fail due to the OptiX path …

testoptix enhancements to make more analogous to testrender

---

src/include/OSL/oslexec.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
src/testoptix/testoptix.cpp
src/testrender/testrender.cpp
src/testshade/testshade.cpp

The ShaderGroupBegin / ShaderGroupEnd (with interspersed Parameter,
Shader, and ConnectShaders calls between them) relied on hidden state
indicating which shader group was the single one undergoing
specification.  This made the shader declaration process unable to
occur concurrenty for different shaders by different threads.
This patch introduces new versions of Parameter(), Shader(), and
ConnectShaders() that take an explicit `ShaderGroup&` parameter and
don't depend on any saved state. Remember that ShaderGroupBegin
returns a ShaderGroupRef, it's this dereferenced object that is passed
to the other functions that help specify the contents of the group.
This allows multithreaded apps to be building the scene, including
shader specification, from many threads concurrently.
The old …

ShadingSystem: allow for thread-safe/reentrant shader specification

---

src/liboslexec/shadingsys.cpp

Recursive invocations need to use the same group. This bug only occurs when using the brand new APIs just added for threaded shader definition.

Small fix for ConnectShaders

---

src/testoptix/testoptix.cpp

PR #984 had a typo, which my unit tests didn't catch because it was
inside code that only is compiled when building OptiX support.

Fix related to thread-safe shader specification

---

CMakeLists.txt
src/liboslcomp/typecheck.cpp
testsuite/oslc-err-assignmenttypes/ref/out.txt
testsuite/oslc-err-assignmenttypes/run.py
testsuite/oslc-err-assignmenttypes/test.osl
testsuite/oslc-err-closuremul/ref/out.txt
testsuite/oslc-err-struct-ctr/ref/out.txt
testsuite/struct-err/ref/out.txt

Turns out that some of the various type checking we do for simple
assignment,
x = y
was not being checked at all for variable declaration with initialization,
Type x = y
So this patch adds the necessary checks. And also goes back and improves
the error messages for regular variable assignment, changing from messages
like
Cannot assign 'float' to 'int'
to the more clear (I think, because it names the variable, and looks
more like the grammatical construct being complained about)
Cannot assign int i = float

Improve oslc type error detection for variable declaration with init

---

src/liboslcomp/typecheck.cpp
testsuite/oslc-err-assignmenttypes/ref/out.txt

Consider int=float to be a warning, not an error.
This is partly because C allows it and we ran accross some
examples where it seems more strict than necessary.
(Of course it works without warning if you use a cast, showing
that any trucation is intentional.)

oslc: slight adjustment to assignment typechecking

---

src/include/OSL/oslexec.h

The implementation of #984 inadvertently lost one of the old
variants of the SS::Parameter() call. There was a 3-param version
and a 4-param version separately declared, but somehow in the code
that was merged, only the 4-param version has an implementation.
Fix by merging the declarations so that it's a 4-param method with
a default value for the last argument (which I think was my intent
all along).
Fixes #999

Fix inadvertently missing SS::Parameter() implementation

---

src/testshade/testshade.cpp
testsuite/testoptix/run.py

We had a weird chicken-and-egg problem after a recent testshade
refactor, where getargs parsing made the individual shadingsystem
calls to set up the group, but also set other options we wished had
been established before this parsing starts.
The solution is change the main getargs to NOT fully set up the shader
group, but instead to just stash away the group setup args for later
processing. Then after the renderer and SS are fully set up
considering all the other options, we re-parse the stashed options and
set up the shader group.
This fixes some embarrassing reliance on the TESTSHADE_OPTIX environment
variable during tests.

Refactor testshade argument parsing

---

src/cmake/modules/FindOptiX.cmake

Improves the logic for finding the OptiX libraries in two ways. Firstly, a fallback has been added to the OPTIX_find_api_library macro to set the library version based on the OPTIXHOME variable and our knowledge of the default directory structure of an OptiX install. Secondly, the logic now uses the version number that is already being fetched from the OptiX headers to correctly match the versioned OptiX libraries.

Improve FindOptiX.cmake logic

---

src/liboslexec/instance.cpp

When specifying a parameter value for an unbounded array, supplying a scalar parameter would lead to a failed assert.
For example, shader declares: `string[] foo`, but the user provides the parameter type: `string` instead of `string[1]`.
It seems ok to me to allow this (at the very least, it shouldn't be an assert).

Fix a subtle issue with parameter arrays

---

testsuite/runtest.py

* Fix bug from PR 1001, default value for missing OSL_SOURCE_DIR env
variable should not have included the testsuite directory itself.
* Be sure to correctly redirect all stderr to the same saved file as
stdout. This makes it easier to have testsuite entries that test
warning or error output.

testsuite runtest.py cleanup

---

src/include/OSL/llvm_util.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/testrender/cuda/rend_lib.cu
src/testshade/optixgridrender.cpp
testsuite/printf-whole-array/ref/out.txt
testsuite/printf-whole-array/test.osl

Hopefully this'll make picking off tests a bit easier.
I haven't found much documentation about Cuda's vprintf, but it seems to be supported back to at least v6 ?
Enabled printf-whole-array for Optix, and added some lines.

Optix: support array and va_args printing

---

CMakeLists.txt
src/include/OSL/oslexec.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
src/liboslexec/shadingsys.cpp
testsuite/opt-warnings/ref/out.txt
testsuite/opt-warnings/run.py
testsuite/opt-warnings/test.osl

* Properly track gettextureinfo handle use in the stats.
* New ShadingSystem option: "opt_warnings" enables warnings about
things that couldn't be optimized and may be performance issues.
* New ShadingSystem option: "gpu_opt_error" enables full error status
of the subset of those warnings that are also hard no-go's when
executing on GPUs.
As an example, the first such warning/error is for texture calls where
the name of the texture cannot be fully resolved to a known string
constant during the course of runtime optimization. We will add other
warnings/errors over time.
The warnings/errors are sent back to the renderer's ErrorHandler,
and as an example they look like this:
Optimization warning:
group: bumpy_material_14
layer: disp_texture_2
shaders/tex.osl:58: texture(): texture name …

Warn about missed optimizations

---

src/include/OSL/oslconfig.h
src/liboslexec/backendllvm.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/shadingsys.cpp
src/liboslexec/splineimpl.h
src/testrender/optixraytracer.cpp
src/testshade/optixgridrender.cpp

Trying to simplify / cleanup portions of the current implementation.
Make OSL::pvt::gSplineData constant which can avoid avoid CPU->GPU upload.
Introduce BackendLLVM::llvm_load_string to localize the branching done when uploading strings.
Send actual bitcode bytes vs a point to std::vector (which is currently incurring a temporary allocation penalty)

Optix simplification / cleanup

---

appveyor.yml
src/oslc/oslcmain.cpp
src/oslinfo/oslinfo.cpp
src/osltoy/osltoymain.cpp
src/testrender/testrender.cpp
src/testshade/testshade_dso.cpp
src/testshade/testshademain.cpp
testsuite/runtest.py

Recently, OIIO sysutil.h added a way to set up a stack trace dump in
case of crash. Use those in OSL binary commands (it does not
automatically happen from the library). This only work with a new
enough version of OIIO, and only if that OIIO was compiled with a new
enough boost to contain boost's stack trace library (>= 1.65).
This is primarily to help developers figure out what's going on with
CI tests fail on remote machines -- you can't catch it in the
debugger, but maybe the stack trace will give you the clue you need as
to what's going on. I definitely don't expect it to be very helpful if
the crash happens in the JITed shader. But if the crash is in our code,
maybe it will help the detective work.
To that end, we also change the testsuite runtest.py so that when a
command fails …

Install crash handlers with stack trace dump

---

CMakeLists.txt
src/liboslexec/shadingsys.cpp
src/testshade/testshade.cpp
testsuite/allowconnect-err/ref/out.txt
testsuite/array-range/ref/out-alt.txt
testsuite/array-range/ref/out.txt
testsuite/component-range/ref/out-alt.txt
testsuite/component-range/ref/out.txt
testsuite/debug-uninit/ref/out-opt2.txt
testsuite/debug-uninit/ref/out.txt
testsuite/error-serialized/ref/out.txt
testsuite/error-serialized/run.py
testsuite/error-serialized/test.osl
testsuite/error-serialized/test.oslgroup
testsuite/groupstring/ref/out-noopt.txt
testsuite/groupstring/ref/out.txt
testsuite/missing-shader/ref/out.txt
testsuite/testshade-expr/ref/out.txt
testsuite/unknown-instruction/ref/out.txt

When using the variety of ShaderGroupBegin that takes a serialized
description of the group, errors in the individual 'shader', 'param',
or 'connect' commands were not bubbled up into a proper error message
for the ShaderGroupBegin call itself, nor caused it to return null
as the group.

Improve errors for badly formed serialized shaders

---

src/liboslcomp/codegen.cpp
src/liboslcomp/oslgram.y
src/liboslcomp/typecheck.cpp
testsuite/oslc-err-initlist-return/ref/out.txt
testsuite/struct/ref/out.txt
testsuite/struct/test.osl
testsuite/vararray-default/ref/out.txt
testsuite/vararray-default/test.osl

Still gets length 1 (we don't allow 0-length arrays, that's a whole
other can of worms), but this is now treated as equivalent to
`= { default_value }` (0 for int or float, "" for string).
It's syntactic sugar, but it removes some clutter for people who want to
have shader parameters that are arrays of undetermined length (and thus are
probably expected to have a runtime-assigned instance value or be
conntected to an output of an earlier layer within the shader group),
removes the requirement for spelling out an initializing value that
won't be used anyway.

Allow shader params (arrays/structs) empty brace initialization lists

---

src/include/OSL/oslclosure.h
src/testrender/cuda/rend_lib.cu
src/testrender/cuda/rend_lib.h
src/testrender/cuda/wrapper.cu

The current implementation of the OptiX run time defines its own closure structures that replicate that of the native OSL closure structures. This is likely just legacy code as it was easier to use OptiX types like float3 than add support the native OSL types. Removing this duplication and using the native OSL closures improves the maintainability of the code as you will no longer need duplicate logic if the structures ever change.
Some notes regarding this PR that are worth thinking about:
* In OSL/oslclosure.h I have to align the ClosureComponent struct to 8 bytes instead of 16. This is because the memory pools we use to store these structs are aligned to 8 bytes and we need to align them in a compatible way to avoid misalignment issues.
* ~~There is an order dependency when including …

Add support for native OSL closures in OptiX

---

src/liboslexec/llvm_instance.cpp
src/testrender/testrender.cpp
src/testshade/testshademain.cpp

As reported in #1025, ShaderGroup compilation fails when a shader uses closure parameters and OptiX is enabled. This is due to an improper type check that is only present in the OptiX path. The fix here is to check whether a parameter is of type closure before checking if it's a string.
No new tests.

OptiX closure param fix

---

src/liboslexec/shadingsys.cpp

Respect 'lockgeom' default when building from commands.
ReParameter was asserting after parameter lookup, if the symbol was not on the instance.
Since the call already has a return value to signal success, use that instead.

Respect lockgeom default for 'GroupSpecs' and remove ASSERT from ReParameter

---

src/include/OSL/rendererservices.h
src/liboslexec/builtindecl.h
src/liboslexec/constfold.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/optexture.cpp
src/liboslexec/rendservices.cpp
src/liboslexec/runtimeoptimize.cpp
src/testrender/optixraytracer.cpp
src/testrender/optixraytracer.h
src/testshade/optixgridrender.cpp
src/testshade/optixgridrender.h
testsuite/gettextureinfo/ref/out-opt.txt

This goes together with https://github.com/OpenImageIO/oiio/pull/2277
I've also attempted to constant fold get_texture_info even if the call would fail (and generate an error message to maintain runtime behavior).
Remove unused function get_texture_perthread from RendererServices to reduce confusion. It was never getting called internally.

Take advantage of proposed OIIO APIs to pass thread_info to texture related calls

---

src/liboslexec/constfold.cpp
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h

Noticed we were making a bunch of tiny `std::vector`s while working on the `gettextureinfo` patch.
Probably a drop in the bucket compared to everything else that goes on during runtime optimization, but every little bit helps.
Also `rop.insert_code` also makes a fresh `Opcode` struct, so there's no need to tweak the read/write flags if they are the same as the default.

Avoid creating tiny std::vectors during constant folding where possible

---

src/liboslexec/constfold.cpp
testsuite/array-range/ref/out-opt.txt

This extends constant folding for `aref` even in the cases where the array index is out of bounds. If the user asked for range checking, we will generate an error instruction in the event that control flow reaches there, but the array index will be clamped regardless.

Constant fold array access even if they are out-of-bounds

---

src/include/OSL/llvm_util.h
src/liboslexec/backendllvm.cpp
src/liboslexec/backendllvm.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h

This is inspired by the recent refactors in the constant folding code. There was an opportunity to apply the same idiom here as well as remove a bunch of un-necessary `std::vector` usage.
I made a small assumption about the number of arguments in one place (verified via an assert of course). Testsuite for OSL and our renderer suggest the limit is large enough.

Avoid creating tiny std::vectors during LLVM code generation

---

.travis.yml
INSTALL.md
src/cmake/externalpackages.cmake
src/include/OSL/oslconfig.h
src/include/OSL/oslexec.h
src/liboslexec/dual_test.cpp
src/liboslnoise/oslnoise_test.cpp
src/osltoy/osltoyapp.cpp
src/osltoy/osltoyrenderer.cpp
src/testshade/testshade.cpp

We've been talking about this for a long time.
This is only in master. The 1.10 family of releases will always retain compatibility with OIIO 1.8.

Bump minimum OIIO version to 2.0

---

src/cmake/cuda_macros.cmake

The other option seems to be getting **OpenImageIO/fmt/core.h**  to use `[[deprecated]]` in the nvcc/cuda case?

Define FMT_DEPRECATED for CUDA, as NVCC doesn't like __attribute__(deprecated)

---

src/include/OSL/ImathMatrix_cuda.h
src/liboslexec/CMakeLists.txt
src/liboslexec/backendllvm.cpp
src/liboslexec/opmatrix.cpp

Here is a fix for #1041. @timgrant added a fix for the crash. Essentially matrices were not being dealt with in `BackendLLVM::getOrAllocateCUDAVariable`, hence the crash. The rest of these changes are to port the correct matrix ops to OptiX that are needed to use the transform functions. This meant adding the device decorations to the `Matrix44` class in `ImathMatrix_cuda.h` and to the matrix ops in `opmatrix.cpp`. I've only done the simple ops as the others will need some more thinking to port and also don't help fix the problem at hand.
I've tested this against the repro in #1041 and can confirm it fixes the issue.

Fix crash in optimize_group when compiling transform command for OptiX

---

.travis.yml
src/build-scripts/install_homebrew_deps.bash
src/osltoy/codeeditor.cpp
src/osltoy/osltoyapp.cpp

Keep warnings about marked-as-deprecated methods from breaking the OSL build.
On OSX, Homebrew just upgraded to a new enough Qt to see this breakage.
Also fix install_homebrew_deps to make sure Travis OSX test can find
Qt so it builds osltoy. (It wasn't before, so this build break would
not have been found by Travis-CI.)

QFontMetrics.width() is marked as deprecated in new Qt.

---

src/cmake/modules/FindPugiXML.cmake
src/include/OSL/export.h

1. Allow to use pugixml-1.9
2. MIngw compiler use ````__declspec```` macroses too for export symbols
3. Fix export symbols by liboslexec to allow properly link osltoy

Some fixes for mingw compiler

---

CHANGES.md
CMakeLists.txt
src/doc/languagespec.tex
src/include/osl_pvt.h
src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/codegen.cpp
src/liboslcomp/typecheck.cpp
testsuite/color/ref/out.txt
testsuite/color/test.osl
testsuite/named-components/ref/out.txt
testsuite/named-components/run.py
testsuite/named-components/test.osl
testsuite/named-components/test_named_comp.h
testsuite/oslc-err-named-components/NOOPTIMIZE
testsuite/oslc-err-named-components/NOOPTIX
testsuite/oslc-err-named-components/ref/out.txt
testsuite/oslc-err-named-components/run.py
testsuite/oslc-err-named-components/test.osl
testsuite/vector/ref/out-alt.txt
testsuite/vector/ref/out.txt
testsuite/vector/test.osl

Spatial geometry triples (point, vector, normal) now support A.x, A.y,
A.z as synonyms for A[0], A[1], A[2], respectively. It's not the
notation I prefer (obviously, or I would have done it 25 years ago),
but other people really dig it, so fine by me.
Colors now support A.r, A.g, A.b as synonyms for A[0], A[1], A[2],
respectively.  To be honest, this worries me a little because I fear
we will regret it if we ever shift to supporting spectral rendering
(and the components will not necessarily represent red, green, and
blue, and may have arbitrary number). But again, people really seem to
like this, so fine, but don't come complaining to me in a few years
when your shaders all need rewriting for your new spectral renderer.
In both cases, it's for direct reference to lvalues (variables, …

Allow aggregate component access with .[xyzrgb]

---

src/liboslexec/backendllvm.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/opmatrix.cpp
src/testrender/cuda/rend_lib.cu

In this pull request I have ported the remaining matrix ops to OptiX. This therefore allows renderers to add support for transforms (camera, raster, screen space etc..) in the OptiX runtime. The majority of this PR was just adding the device decorations for the correct functions and using `llvm_load_string` in stead of `llvm_load_value` in the correct places so that device strings are dealt with correctly. Notice that I have left the `osl_get_matrix` and `osl_get_inverse_matrix` functions as extern functions. The design of this is because they need some kind of renderer callback. As extern this allows the renderer to directly implement these ops in the same way we do with such ops as `osl_allocate_closure_component`. I have created the basic functions for these in the rend_lib.cu file but …

Add remaining matrix ops to optix

---

src/liboslexec/opcolor.h
src/liboslexec/shadingsys.cpp
src/testrender/optixraytracer.cpp
src/testshade/optixgridrender.cpp

Fixes reliance on liboslexec/opcolor.h in client code.
There isn't a super-great simple-solution here while still keeping liboptix out of liboslexec.
Final version seem like it should be extensible enough to at least handle other data upload that needs to convert device strings...but uploading OCIO transforms will probably change all of this anyway?

Fix private header inclusion of opcolor.h

---

src/liboslexec/backendllvm.cpp
src/liboslexec/backendllvm.h
src/liboslexec/llvm_instance.cpp

There was [an issue](https://groups.google.com/forum/#!topic/osl-dev/qwymeCvdFOw) raised on the osl-dev group about variable updates no longer working in optix. This was due to a missing call to `createOptixMetadata`, which I had inadvertently removed in #973. I fixed that issue and squished out a bit of duplication in CUDA/OptiX variable creation.
I followed @fpsunflower's suggestion from #1057 and now use `TypeDesc` instead of `std::string` to communicate the type when creating a CUDA variable.
No new tests added, but existing OptiX tests pass.

Overhaul OptiX variable creation

---

.travis.yml
src/build-scripts/build_cmake.bash
src/build-scripts/build_openexr.bash
src/build-scripts/build_openimageio.bash

Recent changes in OIIO master's build scripts require CMake 3.12+.
Also update openexr build script to handle OpenEXR 2.4 (copied from OIIO).

Ensure a new enough cmake for OIIO master

---

src/liboslexec/shadingsys.cpp

We provided a way to specify the "current" shader to use in the shader setup functions, but were not using it in the version of `ShaderGroupBegin` that works from a pickled representation of the shader.
This would prevent these from being loaded in parallel.

Make ShaderGroupBegin re-entrant when parsing a description from a pickled representation

---

src/include/osl_pvt.h
src/liboslcomp/oslcomp.cpp
src/liboslcomp/osllex.l
src/liboslcomp/symtab.cpp
src/liboslexec/osogram.y
src/liboslexec/osolex.l
src/liboslquery/oslquery.cpp
src/oslinfo/oslinfo.cpp
testsuite/oslinfo-metadata/metadata.osl
testsuite/oslinfo-metadata/ref/out.txt
testsuite/string/ref/out.txt
testsuite/string/test.osl

"Unescape" all string literals in .osl and .oso as they are parsed,
then "escape" them properly for output.  We weren't being careful and
consistent before. This led to at least two subtle behavioral errors:
1. oslinfo would appear to add an extra set of escape characters to
metadata values that contained escape codes.
2. If s = "\n", then strlen(s) was 1 if s was a local variable, but was
incorrectly 2 (wowza!) if s was a parameter!

Handle escaped string literals (like "\tfoo\n") more correctly.

---

site/spi/Makefile-bits

Build stopped working with rpath after latest overhaul. This seems to fix it.

Uncomment old lines to fix rpath on macosx

---

src/liboslcomp/oslcomp.cpp
src/liboslexec/backendllvm.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/master.cpp
src/liboslexec/opclosure.cpp
src/testshade/testshade.cpp

I found several additional places where we were not being locale
independent, so if run in a locale with "," as the decimal separators,
output would change or bad things would happen.

Ensure locale independence

---

src/osl.imageio/CMakeLists.txt

OIIO master/2.1 on OSX changed the extension used for imageio plugins.
Make us do the right thing here. OSX problem only, and only when
straddling the OIIO 2.0/2.1 boundary.

Better logic about whether OIIO plugin must be module or shared lib

---

src/include/OSL/oslconfig.h

New macros:
* OSL_ASSERT / OSL_ASSERT_MSG -- always test, always print error if the
test fails, abort only in debug build.
* OSL_DASSERT / OSL_DASSERT_MSG -- debug mode only test, print, abort.
Does nothing for release build.
Eschew the old OIIO macros ASSERT/DASSERT, since it is perferable to not
purposely abort when in release mode.
Ported over from OIIO copies of a few other related macros.
This patch just adds definitions, we will change the existing macros
in subsequent PRs.

Assertion overhaul

---

src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h
src/liboslexec/osolex.l
src/oslc/oslcmain.cpp

This can be useful in debugging situations, since the oso file would
completely contain a readable (though preprocessed) and recompilable
version of the source.
In the oso file, this is signified by the hint `%preprocessed_source`,
and following that the remainder of the file is assumed to be source
code or comments and will be ignored by the oso parser.

oslc --embed-source : embed preprocessed source at end of oso file

---

src/include/OSL/oslconfig.h

Just disable it when compiling Cuda code -- which doesn't need this
functionality anyway. That skips the headers that Cuda is complaining
about.

Work around Cuda problem with the {fmt} lib that OIIO bundles

---

src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
src/osltoy/osltoyapp.cpp
src/osltoy/qtutils.h

Found a couple more internals to change the names to be extra sure we
keep straight which ones are "printf-style" formatting ("%6.2f"), versus
future C++ converstion of std::format (Python-like: "{:6.2}"). Currently
we use exclusively printf-style, but some day there may be a mix, so I'm
removing ambiguity in the names. This is strictly internal, does not
change any public APIs.

osl internals: be clear about printf style formatting

---

.github/workflows/workflow.yml
.travis.yml
CHANGES.md
INSTALL.md
Makefile
appveyor.yml
src/cmake/externalpackages.cmake
src/liboslexec/llvm_util.cpp

LLVM 9 is about to branch... supporting 6,7,8 and soon 9 is more than enough, we don't
need to support 5 versions back.
Also, LLVM 6 is the minimum that can be used with the new OptiX work, so 5 will soon be very undesirable if not already.

Raise minimum LLVM to 6.0, drop LLVM 5

---

CMakeLists.txt
src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h
src/liboslcomp/osllex.l
src/oslc/oslcmain.cpp
testsuite/oslc-M/myheader.h
testsuite/oslc-M/ref/mydep.d
testsuite/oslc-M/ref/out.txt
testsuite/oslc-M/ref/test.d
testsuite/oslc-M/run.py
testsuite/oslc-M/test.osl

This patch adds support for `-M`, `-MM`, `-MD`, `-MMD`, `-MF` flags,
akin to how they are used in gcc or clang, to generate dependency
files that can be used by make, ninja, etc., to express header
dependencies of osl files.  For example, output might look like:
$ oslc -MMD test.osl
Compiled test.osl -> test.oso
$ cat test.d
test.oso: test.osl \
dist/macosx/share/OSL/shaders/color2.h \
dist/macosx/share/OSL/shaders/stdosl.h
`-MD` and `-MMD` output a dependency file (all headers for `-MD`, just
user headers for `-MMD`), by default to `<inputbasename>.d`, but
overrideable by `-MF<filename>`.
`-M` and `-MM` are versions of `-MD` and `-MMD` but that print the
resulting dependency list to stdout.
We also adjust the printing of "Compiled foo.osl -> foo.oso" so that
it does not happen in the …

oslc can generate dependency files

---

src/include/OSL/dual.h
src/include/OSL/dual_vec.h
src/include/OSL/oslconfig.h
src/liboslexec/opcolor.cpp
src/liboslnoise/gabornoise.cpp

Change Dual<T,PARTIALS> to not use array based data members and avoid any control flow loops for operations on it.  The change better enables compilers to keep values in registers via SROA (Scalar Replacement of Aggregates) optimizations as well as enable more efficient SIMD vectorization of loops using dual types.
The generic implementation of Dual defers storage of base class DualStorage which can be specialized for 1, 2, or 3 PARTIALS.  Specialized DualStorage have individual data members: m_val, m_dx, m_dy, m_dz instead of an array m_elem[PARTIALS].  To provide index based access to the data members, a ConstIndex<int> is introduced.  The DualStorage provides element access to applicable ConstIndex<#>:
constexpr const T& elem (ConstIndex<0>) const { return m_val; }
constexpr const T& …

Refactor implementation of template<class T, int PARTIALS> Dual

---

src/include/OSL/dual.h
src/include/OSL/dual_vec.h
src/include/OSL/oslconfig.h
src/include/OSL/oslnoise.h

* Port a bunch of compiler identification and manipulation macros from
OIIO's platform.h to OSL's oslconfig.h. (Renaming OIIO_blah -> OSL_blah
obviously.)
* Rename the recently-added OSL_INLINE -> OSL_FORCEINLINE to match the
similar macro from OIIO and use OIIO's definition which is is more
robust to a wider range of compilers. Rename many places where we
previously used OIIO_FORCEINLINE to the OSL name.
* Rename the recently-added OSL_EXPECT_TRUE and OSL_EXPECT_FALSE ->
OSL_LIKELY and OSL_UNLIKELY, porting and matching the similar macro
that we already used extensively from OIIO. Rename all the places
where we used it with the OIIO name.
* Change bare references to `__cplusplus >= 201402L` into
`OSL_CPLUSPUS_VERSION >= 14`.
* Change stray OIIO_CONSTEXPR to OSL_CONSTEXPR which we have …

Some stylistic touch-ups on compiler related macros

---

src/include/OSL/Imathx.h
src/include/OSL/matrix22.h
src/include/OSL/oslconfig.h
src/liboslexec/opmatrix.cpp

Move inclusion of Imath*cuda.h from Imathx.h to oslconfig.h
Avoid aliasing in helper math functions by not using Vec3::operator [] and instead accessing .x, .y, .z data members directly.  Likewise for Vec2.
Avoid aliasing in helper math functions by not calling Matrix44::operator [] which returns a float *.  Instead use the x[4][4] datamember directly which keeps it type safe and avoids casting down to a float *.
Made math helper functions static OSL_FORCELINE where possible to avoid any collisions with other translation units who might be compiled with different compiler flags (like target ISA).
To make some of the aliasing avoidance changes, needed to introduce some free functions to be called instead of existing base class methods (which exist in a different open source project). …

Math and aliasing improvements

---

src/include/OSL/oslconfig.h

The main change is recognizing which MSVS version is C++14 compliant.
Also fixed some comment typos, and initial support for C++20 detection.
(Ported from similar change I made in OIIO recently.)

Slight revision of detection of C++ version

---

src/build-scripts/gh-installdeps.bash
src/osltoy/osltoyrenderer.cpp

libsquish saves a little OIIO build time by not having to build the
embedded version.
qt5 lets the CI build osltoy (doesn't run it, but makes sure there's a
clean build).. and sure enough, there wasn't a clean build on gcc8, so
I have a fix for a picky warning.

CI: On Linux, preinstall libsquish & qt5

---

.github/workflows/workflow.yml
.travis.yml

Not sure why, but something changed recently on GitHub CI that is
causing our CI tests to fail... but not on the OSL build itself, only
on the OpenEXR dependency build, and only when using OpenEXR 2.2.
I don't have time for this nonsense, so just adjust all the GH CI
tests to use OpenEXR >= 2.3. Adjust some of the TravisCI tests to use
OpenEXR 2.2 so we still have some proper test coverage of it.

Fix CI problems on GI, need OpenEXR 2.3+

---

CMakeLists.txt
src/liboslexec/shadingsys.cpp
testsuite/mergeinstances-duplicate-entrylayers/a.osl
testsuite/mergeinstances-duplicate-entrylayers/b.osl
testsuite/mergeinstances-duplicate-entrylayers/ref/out.txt
testsuite/mergeinstances-duplicate-entrylayers/run.py
testsuite/mergeinstances-duplicate-entrylayers/shadergroup

Assertion in merge_instances() with a shader group containing multiple identical entry layers.
This was initially encountered in the 1.9 branch, the issue is still present in the master branch; however only when built with the debug flag, due to the OSL_DASSERT change.
The error in master is:
src/liboslexec/shadingsys.cpp:3159: merge_instances: Assertion 'B->unused()' failed.
To fix this I've added a check into merge_instances() to ensure that a group is not an entry layer.
1. Yes I've added a new test case.
2. For the record I am unable to get my test case to fail when running make test.
It seems to only run (for me) using the non-debug build, user error on my part?
The command I was running was 
make debug test TEST=mergeinstances-duplicate-entrylayers
I did however verify that I …

Don't merge a layer if it's an entry layer

---

src/liboslexec/opstring.cpp

The string concatenation op was going through `sprintf` which forced at least one
memory allocation to happen, in addition to the expense of going through the parsing logic, etc ... This was roughly doubling the cost of this (already expensive) operation. This commit implements a more direct concatenation via `memcpy`, and uses a small stack buffer in most cases.
Production shader which was abusing string concat renders 10% faster (now only `ustring` creation shows up in vtune). Obviously the offending shader will be rewritten, but this seemed like a low hanging fruit.

Speedup string concat op

---

src/liboslcomp/oslcomp.cpp

You see, we are taking a file path, which on Windows might look like
"c:\path\to\new\osl" (the Windows design mistake we will all live with
forever), and then injecting that into the osl source parse string as
a double quoted string, it will be unescaped and turn into
"c:\path<tab>o<newline>ew\osl", which of course is wrong.
This leads to hilarious bugs on Windows if OSL is installed someplace
where one of the directories in the sequence starts with an "n", as
above.

Windows fix to escape stdosl path

---

src/include/OSL/oslconfig.h
src/include/OSL/platform.h

oslconfig.h was getting a little jumbled. Split off all the compiler,
language, and platform detection and macros that need to vary based on
those, put in a new platform.h.
Both in platform.h and what remains in oslconfig.h, reorder for clarity
and to group similar things together. Almost no actual code has changed.
One of the few changes is that I beefed up the pragma macros (now in
platform.h) to include a few more items.

Refactor oslconfig.h, split parts to platform.h

---

CHANGES.md
src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h
src/oslc/oslcmain.cpp
testsuite/oslc-M/ref/mycustom.d
testsuite/oslc-M/run.py

Completing the recent dependency generation feature, -MT lets you
customize the name of the dependency target.
Also, to match the C/C++ compilers, we now accept both
-MF<filename>       # all as one arg
-MT<target>
-MF <filename>      # two args
-MT <target>

oslc: add -MT option

---

src/liboslexec/context.cpp
src/liboslexec/oslexec_pvt.h

This caching layer was added a long time ago when the renderer at SPI took a long time to find
out that an attribute query failed. This is no longer the case, and our usage of attribute lookups
has changed enough as to make the caching no longer helpful (and sometimes hurtful, such as
when a shader performs many successful queries). Renderers that need the caching behavior
can re-implement it internally to their RendererServices class.

Remove the failed attribute query cache

---

INSTALL.md

Just a small addition to the INSTALL.md linking to the issue about compiling OSL on macOS Catalina.

Include link for compilation on macOS Catalina

---

src/liboslexec/constfold.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/loadshader.cpp
src/liboslexec/master.cpp
src/liboslexec/oslexec_pvt.h

This patch adds the metadata annotation `"int range_checking=0"` at the shader level to mean that the shader author is certain that range checks can be safely omitted for this particular shader. This can help speedup particularly expensive shaders without needing to globally disable the checks in other shaders.

Add shader level annotation to disable range checking

---

src/include/OSL/oslconfig.h
src/include/OSL/oslnoise.h
src/include/OSL/platform.h
src/include/OSL/sfm_simplex.h
src/include/OSL/sfmath.h
src/include/OSL/wide.h
src/liboslnoise/gabornoise.cpp
src/liboslnoise/gabornoise.h
src/liboslnoise/sfm_gabornoise.h

Introduce sfm (SIMD Friendly Math) namespace with versions of math functions friendly to use inside SIMD loops.
Introduce IntHashBasedNoise to serve as base for HashNoise & CellNoise.
Reimplemented PeriodicHashNoise and PeriodicCellNose to use an adapter to wrap their input values and reuse existing HashNoise & CellNoise implementations.
Introduce code generation policies for Perlin based based functions and Noise objects in order to resuse the same perlin noise functions with or without SIMD intrinsics.  Using a "scalar"(non-intrinsic) version of the algorithm is required when calling from inside a SIMD loop.
Defined Scalar versions of any Noise objects that used SIMD intrinsics internally.
Provide optimized inthash, sfm_simplexnoise, sfm_gabornoise implementations suitable for use …

SIMD Friendly Math and Noise refinements to work inside SIMD loops

---

src/include/OSL/oslversion.h.in

For some reason, the namespace declaration was attached to the end of
OSL_NAMESPACE_EXIT. Which would make an error in any source module that
had multiple OSL_NAMESPACE_ENTER/EXIT blocks.

Disentangle namespace declaration from use to avoid double decl.

---

src/include/OSL/dual.h

* Fix `<<` stream output that broke its pretty formatting in a recent
overhaul.
* Supply missing Dual/float comparison operators: for example, we had
Dual<float, but not float<Dual.
* Add equalAll that is like equalVal, but also compares whether the
derivs are equal (when both items being compared have derivatives).

Minor Dual fixes

---

CMakeLists.txt
src/build-scripts/ci-build-and-test.bash
testsuite/runtest.py

The tricky bit was that we have variants of tests: mytest, mytest.opt,
and when using OptiX, also mytest.optix and mytest.optix.opt.
Those previously all ran from the same working directory, which was
fine if run in serial. When they run at the same time, they will
clobber each other's outputs. So the testsuite logic had to be changed
so that each of the variants runs in its own special test directory.
On my workstation at work, this makes running the whole testsuite
(including all the optix tests) go from 5 mins to 30 seconds.  Woo!

Allow testsuite to run in parallel

---

src/liboslexec/llvm_util.cpp

While looking at #1114, I noticed a totally unrelated issue which is that we don't seem to be making any use of the function optimization passes that LLVM is making for us.
This might be a side effect of the old set of hand picked passes we used before.
Looking at other projects that JIT using LLVM I found what I think is the more correct idiom to use.
Benchmarks indicate no change to either JIT time or runtime (either adding _or_ removing the function passes entirely), so maybe its not that important, but it seems better to call the passes that LLVM is giving us?

Add code to actually run the LLVM function passes on the module

---

src/liboslexec/backendllvm.cpp
src/liboslexec/llvm_util.cpp

The release of LLVM 10.x is imminent, there are just a few API changes that impact OSL.

Allow OSL to compile with LLVM 10.x

---

src/liboslexec/llvm_ops.cpp

This was broken by #1114. 
In a second PR coming later, I will add a testsuite entry where we build with `USE_LLVM_BITCODE=0` just so that this code path cannot be easily broken again.

Avoid compilation error -- can't use always_inline with USE_LLVM_BITCODE=0

---

.github/workflows/workflow.yml
src/build-scripts/build_llvm.bash
src/cmake/externalpackages.cmake

* Use llvm 10 in some CI tests
* build_llvm: New download location for llvm 10
* Build-time check that LLVM 10+ requires C++ >= 14

LLVM 10 odds and ends

---

src/liboslcomp/oslcomp.cpp
src/liboslexec/closure.cpp
src/liboslexec/llvm_ops.cpp
src/liboslexec/optexture.cpp
src/liboslnoise/oslnoise_test.cpp

Avoid potential aliasing issues by avoiding use of Vec3::operator[]
which does a reinterpret_cast and instead explicitly use data member
names .x, .y, .z.
This doesn't matter much for scalar code, but when loops are
explicitly or automatically vectorized, using myvec[0] can confuse the
compiler enough to inhibit vectorization, whereas myvec.x does not.

Change Vec3 [] to .xyz

---

src/liboslexec/builtindecl.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/opmatrix.cpp

Some of the internal matrix ops didn't use the usual naming
convention.  Fix. Also remove at least one that is never used because
it's a combination that oslc will never output.
Submitted on behalf of Alex Wells

Matrix function naming cleanup

---

src/liboslcomp/typecheck.cpp
src/liboslexec/backendllvm.cpp

They aren't used in release builds, and some compilers will warn about
that.
By Alex Wells, with edits by Larry Gritz.

Fix warnings about unused varables

---

.travis.yml
INSTALL.md
src/build-scripts/build_llvm.bash
src/cmake/externalpackages.cmake
src/liboslexec/llvm_util.cpp

Four major releases of LLVM (7, 8, 9, and 10) ought to be enough, so let's drop support for llvm 6 and clean up the cruft. That also simplifies some upcoming changes from Alex if it doesn't need to support llvm6.

Bump LLVM minimum to 7

---

src/liboslexec/context.cpp

Required to get OSL building with a bleeding edge version of fmtlib (via OIIO).

Fix for fmtlib not allowing printf syntax %p with non-void pointers

---

site/spi/Makefile-bits
src/liboslexec/pointcloud.cpp

We previously did not support indexed strings (only int, float, vector).
Also some SPI adjustments to partio finding, the rest of you can
ignore that part.

Support partio string attributes on particles

---

.github/workflows/workflow.yml
.travis.yml

* Fix newly broken Mac CI -- GHA's default homebrew now has llvm 10, which
requires C++14.
* Schedule a nightly cron job for CI.
* Do not launch full builds and tests for pushes that only change
documentation (md, rst, and tex files).

CI on GitHub Actions improvements

---

src/cmake/modules/FindLLVM.cmake
src/liboslcomp/oslcomp.cpp

On OSX, with LLVM 10, it seems that there can be a double linkage of
the libc++ that is built with llvm and the one in /usr/lib.
This leads to a very subtle problem where oslc's use of libclang for
preprocessing is unable to find included files when there are multiple
include search paths (!), unless you have the llvm lib directory first
in your DYLD_LIBRARY_PATH. That is obviously too brittle a fix.
Solve by forcing use of statically linked llvm/clang libraries when
on OSX and using LLVM+clang 10+, even if the user did not explicitly
request that.

Fix include path bugs from libclang on OSX with llvm 10

---

src/cmake/modules/FindLLVM.cmake

Since 9.0 LLVM defaults to building a single clang-cpp library for
non-developer builds.
As this is just the default, and some distributions enable it only with
LLVM 10 (e.g. Fedora), make the clang-cpp search dependent on the build
mode.
Compile tested with openSUSE Tumbleweed (LLVM 10) and Leap 15.2 (LLVM 7).
For some background, see https://fedoraproject.org/wiki/Changes/Stop-Shipping-Individual-Component-Libraries-In-clang-lib-Package and https://llvm.org/docs/CMake.html, option "BUILD_SHARED_LIBS".
Fixes the clang-cpp isssue mentioned in #1155

Use single shared clang-cpp library starting with LLVM 9

---

src/liboslexec/llvm_gen.cpp

Point/color and array accesses were range checked at runtime EXCEPT
when the indices were constant and known to be within legal range.
But matrix component access (m[r][c] = x, x = m[r][c]) were always
range checked.
This patch from Alex Wells (and then enhanced by LG) skips the range
checking on the row or column indices, or both, when they are constant
and >= 0 and < 4, which is probably a lot of the time, thus speeding
up matrix component access a little by skipping the range checking
when it's safe to do so.

Only range check matrix component access when necessary

---

src/liboslexec/llvm_instance.cpp
testsuite/debug-uninit/ref/out-opt2.txt
testsuite/debug-uninit/ref/out.txt
testsuite/debug-uninit/test.osl

Both were plagued by checking the entirety of the matrix, when in fact
only one element needs to be checked. This is wasteful because it
checks elements that aren't read or written by the op we are checking,
and it can also lead to "false positives", errors about elements that
are not touched by the present op.
Refinement of the debug_nan and debug_uninit cases was by Alex Wells.
LG added comments to clarify the implementation of these functions.
LG also amended the testsuite/debug-uninit to specifically test
arrays, triples, and matrices (checking for true positives and check
against false positives). In the process, he noticed another bug (!)
where float-based arrays were not being correctly initialized with
their uninitialized value sentinels, and thus were not detecting use
of …

Make debug_nan and debug_uninit work more accurately for matrices

---

src/include/OSL/llvm_util.h
src/include/OSL/oslexec.h
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

Previously, we had `LLVM_Util::internalize_module_functions` that
reduced the LLVM optimize + JIT work by finding function symbols in an
IR module that started with "osl_" and were not our known entry points
and marking them with "internal" visibility. This lets LLVM recognize
them, if they are not called internally to the module, as dead code
and discard them before spending any time optimizing or jitting those
functions.
This patch from Alex Wells adds an additional method,
`prune_and_internalize_module`, that is even more aggressive, pruning
all symbols that we don't think can be reached with our generated code
(are not "materialized", in LLVM parlance), and then marking
everything that is not a known entry point as "internal".
N.B. Some care is needed not to mark as internal a few …

LLVM_Util::prune_and_internalize_module

---

src/include/osl_pvt.h
src/liboslcomp/symtab.cpp
src/liboslexec/backendllvm.cpp
src/liboslexec/constfold.cpp
src/liboslexec/instance.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
testsuite/debug-uninit/ref/out-opt2.txt
testsuite/debug-uninit/ref/out.txt

In the compiler, symbol.name() is the human-readable name and
symbol.mangled() is a mangled symbol that keeps identical names in
different scopes from clashing. We use mangled() in the oso file but
name() in error messages.
However... at runtime, it reads the pre-mangled name from the oso, and
doesn't know the original name, so name() and mangled() are identical
and are both the mangled version. That's fine for almost everything,
but there are just a few runtime errors that involve the symbol name,
and we would prefer that these be the unmangled version, for the sake
of clarity when communicating errors to the user.
So we add a Symbol::unmangled() that trims the mangling from the front
of a mangled symbol, and in runtime error messages we use this to strip
the mangling.
I also modified …

Demangle symbol names for certain runtime error messages.

---

src/include/osl_pvt.h
src/liboslcomp/codegen.cpp
src/liboslexec/backendllvm.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/runtimeoptimize.cpp

I'm not sure how this happened, but TypeSpec had `is_float_based` and
`is_floatbased` methods, and they were subtly different (the latter is
false for float-based arrays). This has led to at least one bug.
A careful examination reveals that the vast majority of uses of
`is_floatbased` really intended `is_float_based`, so I changed those.
For the remainder, I renamed `is_floatbased` to `is_float_based_notarray`
for clarity.

Fix confusing TypeSpec::is_float_based vs is_floatbased

---

src/liboslexec/oslexec_pvt.h

Obsolete since C++11, where vector::shrink_to_fit() does the same thing.

Remove stlfree -- not used

---

src/include/OSL/llvm_util.h
src/include/OSL/oslconfig.h.in
src/include/OSL/oslexec.h
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/llvmutil_test.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

We aren't saving object files like an offline C compiler; we are
JITing and immediately executing on a specific machine, so we may as
well have LLVM optimize for that very chip. This patch from Alex Wells
adds optimization passes that do so.
LG amended it to make it a shading system option "llvm_target_host"
(defaulting to true).  And we force it to off when compiling for
OptiX, since obviously the GPU is not the host architecture.
Production benchmarks do not show a noticeable speed gain in scalar
code. (Nor does it slow down.) There is no harm in targeting the
specific host CPU, and it may be more helpful when we are dealing with
vectorized code down the road.
Alex also added a developer only macro OSL_DEV_ONLY(STUFF) to leave
developer debugging/tracing code around and only have it …

JIT code for the specific host target

---

src/liboslcomp/oslcomp.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/shadingsys.cpp
src/oslc/oslcmain.cpp
src/osltoy/osltoyapp.cpp
src/testrender/optixraytracer.cpp
src/testshade/optixgridrender.cpp
src/testshade/testshade.cpp

Because they are UTF-8 safe and work properly on MinGW.
Simplified a bit more as I went -- some reading idioms could be
replaced by a single call to Filesystem::read_text_file, some close()
calls were redundant because streams close upon destruction / scope
exit, some open flags unnecessary because the default write mode
already will truncate an existing file.
Closes #1187 

Change all bare std::ofstream/ifstream to OIIO::ofstream/ifstream

---

src/testrender/optixraytracer.cpp
src/testshade/optixgridrender.cpp

This fixes some namespace/compilation errors I was seeing when building the OptiX test renders.
no changes in existing tests
- [x ] I have read the [contribution guidelines](../CONTRIBUTING.md).

adding OIIO namespace to Strutil uses in OptiX renderers

---

.github/workflows/workflow.yml
INSTALL.md
src/build-scripts/gh-installdeps.bash
src/liboslcomp/osllex.l
src/liboslexec/constfold.cpp
src/liboslexec/osolex.l

* Use the new ASWF VFX Platform 2021 docker image for gcc9/py37/llvm10/C++17
* Alter the "bleeding edge" CI test to use gcc10
* Fix some new warnings that pop up with gcc9 and gcc10

Add gcc9 and gcc10 tests to CI matrix

---

src/include/OSL/oslexec.h

For attribute and getattribute, we had some specializations that make
it extra easy to do the common cases of a single float, int, string.
This is just adding the same kind of convenience functions for
Parameter() and ReParameter().

Helper Parameter and ReParameter varieties for common types

---

src/include/OSL/oslexec.h

Amendment to #1195, I called the wrong/deprecated version of Parameter.

Fix new Parameter call -- didn't call the group-specific version

---

src/cmake/compiler.cmake
src/liboslexec/CMakeLists.txt

People linking against oslexec needed to know to use -fno-rtti when
building their apps. Very brittle. This correctly adds the flag as
an interface compile flag in our exported CMake config files.

Propagate rtti compile options to exported cmake config

---

src/include/OSL/Imathx/ImathLimits.h

For some reason ICC feels that its necessary to have the storage keyword, in this case "static" first and will print out a message similar to the following.
`
remark #82: storage class is not first
IMATH_HOSTDEVICE constexpr static bool        isSigned()   {return true;}
`
Although this message is mainly benign it is nice not having ICC spit out a few hundred of these messages all the time.

Fix ICC remark: storage class is not first

---

CMakeLists.txt
testsuite/example-deformer/CMakeLists.txt
testsuite/example-deformer/getP.osl
testsuite/example-deformer/osldeformer.cpp
testsuite/example-deformer/ref/out.txt
testsuite/example-deformer/run.py
testsuite/example-deformer/vadd.osl
testsuite/example-deformer/vfBm3d.osl
testsuite/runtest.py

Many times, people can ask how they can use OSL to make more general
computational engines (not a classic renderer), and one use case that
comes up frequently is to use it to control deformations. This patch
includes a new testsuite example that does exactly this, for a test
case -- setting up a small shader network that operates on a series
of points.
It's a completely self-contained example of how to do this. There is a
lot of boilerplate for such a simple task, but I was really trying to
make sure to provide examples of all the little pieces you'd need to
do a more complex use use.
To make sure it builds, I added it to the testsuite itself, as
testsuite/example-deformer.
Interestingly, it is our first testsuite entry that needs compilation
and linking with OSL -- and not using OSL's …

Example of using OSL as a deformer

---

INSTALL.md
src/osltoy/osltoyapp.cpp

Critical fix to compile cleanly with Qt 5.15

Remove unused (and also deprecated) retrieval of pixmap

---

CMakeLists.txt
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
testsuite/userdata/ref/out.txt
testsuite/userdata/run.py
testsuite/userdata/test.osl

Shader params declared with lockgeom=0
surface foo (float bar = 0 [[ int lockgeom=0 ]]) { }
will generate code making underlying calls to RendererServices->get_userdata
to automatically bind userdata (a.k.a. interpolated "primitive variables")
that share the same name.
But, oddly, this was not true for output parameters:
surface foo (output float bar = 0 [[ int lockgeom=0 ]]) { }
This was tripping some people up, and in retrospect seems strange.
This patch removes this restriction, allowing both input and output
parameters tagged with lockgeom=0 to attempt to retrieve userdata to get
their initial values.
Add test of userdata retrieval to make sure this works.

Allow output params with lockgeom=0 to have auto userdata binding

---

src/include/OSL/oslnoise.h

For some reason this line doesn't compile on windows (at least with MSVC14) and throws the following error.
`
oslnoise.h(204): error C3520: 'ListT': parameter pack must be expanded in this context
`
The modification allows this to build and doesn't cause any issues in the testing I've done. I'm not entirely clear what the logic does so would be good if somebody could verify the new logic is correct.

"error: 'ListT': parameter pack must be expanded in this context" on windows

---

src/cmake/externalpackages.cmake

Spell out the exact requirements when building against LLVM 10,
which option to set to bump to C++14, which compiler versions are
necessary.
Closes #1205

Add a clearer and more prescriptive message for LLVM 10 error

---

src/include/OSL/llvm_util.h
src/include/OSL/platform.h
src/liboslexec/llvm_util.cpp
src/liboslexec/llvmutil_test.cpp

We don't use this quite yet, but are staging it for easy review.
Work by Alex Wells. Some refactoring and minor edits by LG.

Add LLVM_Util methods to detect appropriate ISA for the host CPU.

---

src/cmake/compiler.cmake
src/liboslexec/CMakeLists.txt

We had disabled RTTI throughout the OSL code base to avoid linkage
problems against LLVM, which builds with RTTI disabled by default.
But it's actually ok to mix code modules with differing RTTI status --
that's fine. It's just that you can't mix RTTI status within a class
inheritance hierarchy.
We observe that
* The only classes we inherit from RTTI-free LLVM are solely defined
and used within llvm_util.cpp.
* The only classes exposed in llvm_util.h have no virtual functions
and aren't designed to be subclassed.
So in fact, it appears that we can get by with only using no-rtti when
compiling that one module, and don't need to mess with rtti anywhere
else (including downstream users). This is an important step to
supporting python bindings, since pybind11 requires RTTI.
Signed-off-by: …

Re-enable RTTI

---

src/include/OSL/llvm_util.h
src/liboslexec/llvm_util.cpp

The execution engine does not take ownership of this object, so we need to be cleaning it up ourselves.
I discovered this when running address sanitizer on our renderer and noticed that every test using OSL was failing.

Fix memory leak when using the JIT Event listener

---

src/cmake/modules/FindPugiXML.cmake

CMake seems to cache **PUGIXML_INCLUDE_DIR** and on a reconfigure **PUGIXML_LIBRARY** may never be set.

[CMake] Move PUGIXML_LIBRARY outside PUGIXML_INCLUDE_DIR check.

---

.github/workflows/workflow.yml
INSTALL.md
src/build-scripts/install_homebrew_deps.bash
src/liboslquery/py_osl.h

* Fix template casting reference to work properly with the latest
pybind11 master.
* Mac CI: use Python 3.8 (easier for homebrew)

CI python touch-ups

---

src/liboslexec/llvm_util.cpp

We over-included fmath.h on the OIIO side in some places that it should not have been.
I would like to fix that soon. This preps OSL for the change -- this file actually needs it
and will no longer "accidentally" pick it up through other include files.

Adjust include

---

src/include/OSL/llvm_util.h
src/liboslexec/backendllvm.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/llvmutil_test.cpp
src/liboslexec/oslexec_pvt.h

Leaks are prevented now, though at the cost of a bit more housekeeping
on the part of the user of LLVM_Util.  Each thread must have its own
LLVM_Util::PerThreadInfo, which must outlive any LLVM_Util (and which
must be passed a reference of the PerThreadInfo). Also, there must
somewhere in the app exist a ScopedJitMemoryUser that must outlive all
of the LLVM_Utils.

Refactor jit mem manager and perthread to prevent leaks

---

src/include/OSL/llvm_util.h
src/include/OSL/oslexec.h
src/include/osl_pvt.h
src/liboslexec/constfold.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
src/liboslexec/shadingsys.cpp
src/testrender/testrender.cpp
src/testshade/testshade.cpp

Add support for generating debug information to track function call
stack, source file, and line number inside generated LLVM module.
When enabled, can debug with source and line numbers.  Also Intel(r)
VTune(tm) Profiler associated assembly to shader source and line
number.
The big upshot here is that when this debugging is enabled,
* gdb/lldb can debug a renderer app, all the way down to inside JITed
shaders.
* Stack dumps upon a crash will show you the full stack trace
including where you were in a shader.
* Profilers such as vtune can be used to accurately profile shaders.
The profiling only works if your LLVM was built with the option
`-DLLVM_USE_INTEL_JITEVENTS=ON`.
Due to some ABI changes on the LLVM side, the debugging symbols only
work properly if you are using LLVM >= 7.1.
Some …

Option to generate full debugging and profiling info.

---

site/spi/Makefile-bits
src/liboslexec/llvm_util.cpp

For the most part, standard innocuous LLVM-style API changes, but:
`llvm::ConstantVector` constructor has changed, and while looking into how to migrate I came across `llvm::ConstantDataVector` which according to the docs uses less memory.  The only difference being that `llvm::ConstantVector` has a `llvm::Value` for each element, but it doesn't look like those individual `llvm::Value`s are used/needed ?

Changes for LLVM-11.

---

src/liboslexec/shadingsys.cpp

In the case that an implementation designer wants to use the following pattern:
- Define "renderer_outputs" for a group to stop them from being optimized away
- compile the group
- collect the output parameters using ShadingSystem::find_symbol and store them somewhere in the renderer
- at runtime, after calling ShaderGlobals::execute, we call ShadingSystem::symbol_address for each output parameter to obtain our results
This being the case, we already know due to calling find_symbol that the symbols we later call symbol_address with are valid, so the overhead of a conditional for each and every call to symbol_address could be extremely high considering in this particular use case, the conditional will never be false, especially in a tight render loop where we collect a lot of results. …

Remove null check from symbol_address for performance

---

src/include/OSL/oslexec.h
src/liboslexec/context.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

Separate OSL optimization from JIT by adding optional parameter `bool do_jit = true` to all optimize_group* methods. This  will allow optimization without JIT'ing for the host, or optimizing once but JIT'ing for multiple back ends. It will be necessary if one will be JIT'ing only for batched execution, we  would not want to pay the cost of JIT'ing a scalar version as well (but still could if we wanted both scalar and batched versions simultaneously).

Split the opt and jit functionality of optimize_group

---

site/spi/Makefile-bits

No need to hold on to a reference to the RC.

Move spi-bits to llvm-11.0.0 release.

---

src/include/OSL/oslconfig.h.in

We used to disable fmt and fall back to tinyformat, when using Cuda.
The new OIIO 2.2 removes tinyformat and the OIIO_USE_FMT preprocessor
symbol. So make sure that we also tell fmt to avoid using the int128
type, not supported by Cuda. That seems to be enough to let it use
the rest of fmt without trouble.

Fix fmt vs Cuda incompatibility

---

CHANGES.md
src/doc/languagespec.tex

The implementation was always correct, but the description here was
super unclear and wrong.

Docs: Fix longstanding error in description of spline()

---

.git-blame-ignore-revs

This new file contains the hashes of commits whose only function was
to reformat large amounts of code.
Ordinarily, this would make for confusing 'git blame' output, by
making old code written by author A appear to have a new modification
date and authorship by B, when in fact we know that B just did some
reformatting. This can make it especially hard to discern code history
after after commits that establish the use of "clang-format".
A new git feature (requiring git >= 2.23) allows pointing to a file
containing hashes of commits to be ignored by git blame:
git blame --ignore-revs-file .git-blame-ignore-revs
To avoid having to remember this all the time, consider adding this to
your git config:
git config blame.ignoreRevsFile .git-blame-ignore-revs
Note that git supports this feature but …

Use .git-blame-ignore-revs

---

src/include/OSL/llvm_util.h
src/liboslexec/llvm_util.cpp

This will be used extensively by the SIMD batched shading.
* Added support for masked operations by managing a stack of masks
that were created by conditionals or control flow. Detailed
explanation of the Masking Strategy in llvm_util.h.
* Added support for logically masked functions (handling of masked
return from inside OSL functions)
* Added support for masked loops (handling of masked break and or
masked continue).
* Added support for masked exit (handling of masked exit from entire
shader).
* Added support for management of when masking is required with a
ScopedMasking object to allow nesting during code gen.
* op_store (and other store variations) respect the current masking
requirement and current top of the mask stack (not just the top
entry, but a combined …

LLVM_Util: add support for masked operations

---

src/include/OSL/oslexec.h
src/liboslexec/llvm_passes.h
src/liboslexec/llvm_util.cpp
src/testshade/testshade.cpp

Work of Alex Wells, Intel.
Added custom optimization passes to improve AVX/AVX2 code generation
which are automatically added when targeting the host:
* PrePromoteLogicalOpsOnBitMasks
* PreventBitMasksFromBeingLiveinsToBasicBlocks
Added support for experimental llvm_optimize: 10,11,12,13.  Optlevels
10, 11, 12, 13 explicitly create optimization passes.  They are
stripped down versions of clang's -O0, -O1, -O2, -O3.  They try to
provide similar results with improved optimization time by removing
some expensive passes that were repeated many times and omitting other
passes that are not applicable or not profitable.  Useful for
debugging, optlevel 10 adds next to no additional passes.

Custom opt levels and passes

---

src/testrender/optixraytracer.cpp
src/testshade/optixgridrender.cpp

`testrender` and `testshade` were both relying on the automatic pipeline stack size computation in OptiX 7. This was causing a handful of tests to fail for reasons that are still not clear. Computing and manually setting the required stack size clears up the failures.
I didn't add any tests, but all existing tests pass with this change.

Explicitly set the OptiX pipeline stack size.

---

src/cmake/flexbison.cmake
src/liboslexec/osolex.l

When two OSL distributions are loaded, they will both use the same `osoparse` and `osolex`functions.
Problematic because the OSOReader::parse_XXX function from _liboslexec_A.so_ will set the static variable `osoreader = this`, but then call `osoparse` in _liboslexec_B.so_, where the `osoreader` static is still NULL.
https://github.com/marsupial/OpenShadingLanguage/blob/62797a9032a73162a62e19d03261d7d8bd3a8ded/src/liboslexec/osolex.l#L263
https://github.com/marsupial/OpenShadingLanguage/blob/62797a9032a73162a62e19d03261d7d8bd3a8ded/src/liboslexec/osolex.l#L287

Fix osoparse & osolex from two independent liboslexec.so

---

src/liboslexec/llvm_instance.cpp

Work of Alex Wells.
Like we do already for "for" loops, when generating extra ops to test for
uninitialized values, "do-while" loops also need to skip testing of their
condition variable (which we know has not been written yet, under most
circumstances).

Fix false positive in uninit test involving do-while loops

---

src/liboslexec/llvm_instance.cpp

When generating the code to copy one layer's outputs to a downstream
layer's inputs, we can skip the copy entirely if we already know that
the downstream layer will not be run.

Optimization: Skip copying of output params to used layers.

---

src/liboslexec/shadingsys.cpp
src/testshade/testshade.cpp

testshade --help or --runstats now print additional info about the
dependency versions, hardware capabilities enabled at build time, and
hardware capabilities detected at runtime. This should help debugging
of user experiences as an easy way to find out what OSL thinks it's
working with in terms of its environment.

Print more build/runtime info in stats and help message

---

src/include/OSL/oslexec.h
src/liboslexec/CMakeLists.txt
src/liboslexec/shadingsys.cpp

Move things around -- add new SS::getattribute queries for the dependencies,
SIMD build flags and runtime capabilities, and Cuda/OptiX versions.
Then use these queries as the implementation for reporting them in the
statistics output.

Add Cuda+OptiX dependency reporting to testshade and stats

---

src/liboslcomp/ast.h
src/liboslcomp/symtab.h
src/liboslexec/accum_test.cpp
src/liboslexec/backendllvm.h
src/liboslexec/llvm_passes.h
src/liboslexec/llvm_util.cpp
src/liboslexec/loadshader.cpp
src/liboslexec/lpexp.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.h
src/liboslquery/oslquery.cpp
src/osl.imageio/oslinput.cpp
src/oslc/oslcmain.cpp
src/osltoy/codeeditor.h
src/osltoy/osltoyapp.cpp
src/osltoy/osltoyapp.h
src/osltoy/osltoyrenderer.h
src/osltoy/qtutils.h
src/testrender/optixraytracer.h
src/testrender/raytracer.h
src/testrender/shading.cpp
src/testrender/simpleraytracer.cpp
src/testshade/optixgridrender.h
testsuite/example-deformer/osldeformer.cpp

This is good for optimization, allowing "de-virtualization" of function
calls in cases when the compiler can be sure that there can be no further
subclassing.

Use 'final' liberally

---

src/include/OSL/llvm_util.h
src/liboslcomp/CMakeLists.txt
src/liboslexec/CMakeLists.txt
src/liboslexec/llvm_instance.cpp
src/liboslquery/CMakeLists.txt

This PR fixes various small issues when trying to build OSL on Windows (issue #1261).
- dllimport/export attributes should be defined on nested classes (prevent missing symbols)
- MSVC does not has cxxabi.h so do not try to import it (fixes compile error)
- oslcomp/oslquery were defining OSL_EXPORTS while they should import (prevent missing symbols)
- link with `Version.lib` (system library) to prevent missing symbols inside ClangDriver.
master now compiles better on MSVC.
Still not 100% clean for me (shaders is giving errors) but core is fully functional
- [ x] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/). <-- **send today (October 8th 2020)**
- [ x] My code …

Windows compile fixes

---

.github/workflows/ci.yml
src/build-scripts/build_pugixml.bash
src/build-scripts/ci-build-and-test.bash
src/build-scripts/ci-startup.bash
src/build-scripts/gh-installdeps-centos.bash
src/build-scripts/gh-installdeps.bash
src/cmake/externalpackages.cmake
src/cmake/modules/Findpugixml.cmake
src/liboslexec/CMakeLists.txt
src/liboslexec/dictionary.cpp
src/testrender/CMakeLists.txt

In OIIO land, some users pointed out deficiencies in our build
scripts and how they find (or fail to find) pugixml on some platforms and
circumstances. This is an OSL side copy of the approach that seems to
fix things.
* Bring back the idea of a Findpugixml.cmake file because it turns out
that (for pugixml <= 1.10) the exported config files are not reliable.
* Fix CI scripts to build PugiXML (with a few different versions). We
previously were relying on the embedded version for all CI tests, which
masked problems associated with using an external PugiXML.

pugixml build fixes

---

.github/workflows/ci.yml

Repeat of https://github.com/OpenImageIO/oiio/pull/2741
One of our CI matrix entries recently started failing due to changes
in something on GHCI's Ubuntu image. Fix by switching this matrix
to use the appropriate ASWF docker image.

Fix CI break (#2741)

---

src/liboslexec/runtimeoptimize.cpp

No symptoms ever reported, but surely this is a typo bug.

Bug fix: is_nonzero was only considering the first element

---

src/include/osl_pvt.h
src/liboslcomp/codegen.cpp
src/liboslcomp/oslcomp.cpp
src/liboslcomp/symtab.cpp
src/liboslcomp/symtab.h
src/liboslexec/backendllvm.cpp
src/liboslexec/constfold.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/master.cpp
src/liboslexec/runtimeoptimize.cpp

* Simplify implementation of TypeSpec::is_triple, more efficient.
* Add TypeSpec::is_triple_based(), analogous to all the other
is_X/is_X_based.
* Bug fix: Symbol::get_string()'s assertion was checking whether it was
a string, but should have checked if it was string_based.
* Add Symbol::get_vec3(), analogous to get_int/float/string.
* Add Symbol::coerce_float and coerce_vec3, like get but with some type
coercions.
* Add Symbol::dataptr() as synonym for data(). This is for "forward
compatibility", a future PR will make more widespread use of this.
* Lots and lots of places where error-prone and verbose casts are replaced
with the new methods, and some logic simplified.

Minor fixes/enhancements to TypeSpec & Symbol (OSL internal classes)

---

src/cmake/cuda_macros.cmake

Something changed in the CUDA headers between 8 and 9 and you now need the `__CUDADEVRT_INTERNAL__` define when compiling the gpu bitcode to avoid duplicate cudaMalloc symbol errors.

Fix duplicate cudaMalloc symbol error when compiling with CUDA9+

---

testsuite/gettextureinfo/ref/out-oiio2.2-opt.txt
testsuite/gettextureinfo/ref/out-oiio2.2.txt
testsuite/gettextureinfo/ref/out-opt.txt

A change in OIIO master eliminated some spurious newlines in certain
error messages.

Update ref output after recent OIIO change

---

src/include/OSL/batched_shaderglobals.h
src/include/OSL/oslexec.h
src/include/OSL/wide.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
src/osltoy/qtutils.h
src/testshade/testshade.cpp

Introduce template<int WidthT> struct BatchedShaderGlobals to store up to WidthT instances of ShaderGlobal data.  The data for a batch is divided into underlying uniform and varying data structures.  Uniform section contains a fixed set of shader global values that are shared between all instances.  Varying has Block<DataT, WidthT> members so each instance can hold a different value.  The Block data structure is specialized to hold the underlying data type in a SIMD friendly Structure of Arrays (SOA) data layout but provides an array subscript interface to a proxy that can import/export the DataT in its orignal data layout.
Introduce template<int WidthT> class ShadingSystem::BatchedExecutor as an interface to execute batches of shader globals through a shader network.  BatchedExecutor …

Add interface to  ShadingSystem for Batched Execution 

---

src/include/OSL/oslexec.h
src/include/OSL/rendererservices.h
src/liboslexec/oslexec_pvt.h
src/osl.imageio/oslinput.cpp
src/osltoy/osltoyapp.h
src/osltoy/osltoyrenderer.h
src/testrender/simpleraytracer.h
src/testshade/simplerend.h
src/testshade/testshade.cpp
testsuite/example-deformer/osldeformer.cpp

With just a few minor adjustments, we're able to eliminate these two
headers (and everything else they pull in) from every client of
oslexec.h.  For the purposes of oslexec.h's declarations, all uses are
either pointers or references, so we only need the names
forward-declared, but we don't need the implementations revealed to
everybody including oslexec.h.
In particular, this hides the RendererServices and BatchedShaderGlobals
from a lot of translation units, should cut down on compile time and
reduce exposure of certain semi-internals to only the modules that
need them.

Remove rendererservices.h and batched_shaderglobals.h from oslexec.h

---

.github/workflows/ci.yml

CI: Lock down on clang-format 10 for CI format check

---

.github/workflows/ci.yml
INSTALL.md
src/build-scripts/build_llvm.bash
src/include/OSL/llvm_util.h
src/liboslexec/llvm_passes.h
src/liboslexec/llvm_util.cpp

Change bleeding edge CI test to use LLVM 11.
A variety of changes were necessary to the code in LLVM_Util:
* `#if` guards for differing calls related to VectorType::get(),
CreateShuffleVector.
* constant-generating functions now return llvm::Constant* instead of
llvm::Value*.
* New wide_constant(width,value) functions for when you want a width other
than the default vector_width.
* Renamed llvmVectorGet -> llvm_vector_type to be more symmetric with
other methds we have.
* Simplified places that could have made calls to constant(),
constant_bool(), wide_constant(), llvm_vector_type(), and
call_function(), but instead did more complex llvm calls by hand.

Modifications to build against LLVM 11

---

.github/workflows/ci.yml
CMakeLists.txt
src/build-scripts/ci-build-and-test.bash
src/build-scripts/gh-installdeps-centos.bash
src/build-scripts/gh-win-installdeps.bash
src/cmake/externalpackages.cmake
src/cmake/modules/FindOptiX.cmake
src/liboslexec/CMakeLists.txt
src/liboslexec/llvm_util.cpp

It can't run the tests, because there is no GPU on the GHA
instance. But at least we can tell if a PR will breake the build
itself. Later we will find a way to execute these via ASWF's AWS
instances that are for this purpose.
Includes the following changes:
* Download optix headers when needed. The ASWF docker container we're
running on already has Cuda.
* Use CUDA_TARGET_ARCH CMake variable instead of hard coding in
llvm_util.cpp.
* Bump cuda target default to sm_50.
* Make CI failure artifacts include CMakeCache.txt for inspection.

Add GPU CI test to build with USE_OPTIX=1

---

src/include/OSL/platform.h

Bad cut and paste made this all wrong. Fix.
Also rename the template's AlignmentT -> Alignment to help reduce
confusion because we usually use the T end to indicate a template
parameter that's a type.

Fix OSL::assume_aligned for broken MSVS clause

---

.github/workflows/ci.yml

Also make the error artifact include CMake log files.

Let Mac CI use llvm 11

---

src/cmake/pythonutils.cmake

Fixes issues on Mac when there are several Homebrew python versions installed.

Build: Require exact version if PYTHON_VERSION is specified

---

.github/workflows/ci.yml
Makefile
src/build-scripts/install_homebrew_deps.bash
testsuite/python-oslquery/src/test_oslquery.py

The specific combination of Mac + Python 3.8/3.9 + the lastest
pybind11 release causes a crash in the testsuite/python-oslquery
test. It works on other platforms and with older versions of pybind11.
I've tried to understand exactly what's going wrong, and have come up
empty and can't justify spending more time on it. It's suspiciously
similar to several recently "fixed" pybind11+python interaction bugs,
I suspect there are a couple edge cases they missed and that it will
be fixed eventually in a future pybind11 release (or possibly a future
python patch, there does seem to be a problem that pybind11 uncovered
in the cpython code).
In the mean time, a slight rewrite of the loop avoids the problem for
the purposes of our CI tests.
Also a few adjustments to switch back to python 3.9 after …

CI/Mac: fix broken tests involving oslquery

---

CMakeLists.txt
src/liboslexec/runtimeoptimize.cpp
src/testshade/simplerend.cpp
src/testshade/simplerend.h
src/testshade/testshade.cpp
testsuite/debug-uninit/ref/out-opt2.txt
testsuite/debug-uninit/ref/out.txt
testsuite/userdata-passthrough/ref/out.txt
testsuite/userdata-passthrough/run.py
testsuite/userdata-passthrough/test.osl

There's a "pass-through parameter" idiom, where an output param gets
its initial value from an input, it gets modified by the shader, but
it's also an output.
If the modification is optimized away -- say, if it was originally
`theparam *= scale` and scale is 1 -- then it may be that you end up
with no ops in the shader that read from the parameter. If the
parameter was hooked up to userdata, then get_userdata will never be
called to retrieve the value (because it's usually lazy, only doing
the callback the first time it's needed), and so the output value of
parameter will be its parameter default value in the shader, NOT the
value of the interpolated variable, which was never retrieved and
copied into it.
This patch adjusts the logic somewhat so that if that output parameter
is connected …

Bug fix: optimizer interaction with output param that also is userdata

---

CMakeLists.txt
src/doc/languagespec.tex
src/liboslcomp/osllex.l
testsuite/oslc-pragma-warnerr/NOOPTIMIZE
testsuite/oslc-pragma-warnerr/NOOPTIX
testsuite/oslc-pragma-warnerr/ref/out.txt
testsuite/oslc-pragma-warnerr/run.py
testsuite/oslc-pragma-warnerr/test.osl

Add `#pragma error` and `warning` to OSL preprocessor

---

.github/workflows/ci.yml
src/cmake/Config.cmake.in
src/cmake/externalpackages.cmake
src/cmake/modules/FindOpenEXR.cmake
src/include/OSL/matrix22.h
src/include/OSL/oslconfig.h.in
src/include/OSL/sfmath.h
src/liboslcomp/CMakeLists.txt
src/liboslexec/CMakeLists.txt
src/liboslexec/llvm_ops.cpp
src/liboslnoise/gabornoise.h
src/liboslnoise/oslnoise_test.cpp
src/liboslquery/py_osl.h

As OpenEXR works toward their 3.0 release, which includes splitting
Imath (the vector, matrix, math, and 'half' stuff) out into a separate
repo, their top of tree master finally breaks our "bleeding edge"
build.
This is a little tricky, because now our support of this dependency is
attempting to span 3 eras: 3.0 with the full split of openexr from
imath, recent openexr+ilmbase 2.x that supplies reliable exported
cmake configs, and older 2.x that predates cmake configs. Eventually
we'll phase out older versions and clean up.
Fixes in this patch generally include:
* Add a new CI test of VFX2021 + openexr/imath master. (This will go away
when 3.0 is released and that's what we use for the main 2021 case.)
* For new enough versions of OpenEXR, use the exported config file and
targets, rather …

Build against OpenEXR 3.0 + Imath 3.0

---

src/liboslexec/loadshader.cpp

Most failures in this function returned false, but if it got as far as
parsing but failed that stage, it ended up returning true (success),
which is clearly wrong.

LoadMemoryCompiledShader: ensure return false on parse failure

---

src/liboslexec/instance.cpp

After talking this over with Luke Emrose it seems unwise to allow
merging of layers that produce renderer outputs.

Don't merge layers that produce renderer outputs.

---

src/include/OSL/platform.h
src/include/OSL/wide.h
src/include/osl_pvt.h
src/liboslexec/context.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

Add Symbol::wide_dataoffset() to track offset in heap to wide version of symbol's data
Add count to Context to track batch size of last execution 
Add template<int WidthT> ShadingContext::Batched interface to group together batched versions of execute_init, execute_layer, and execute methods.  Instantiate ShadingCOntext::Batched<8> and ShadingContext::Batched<16>.
Refactor std::vector<std::pair<ErrorHandler::ErrCode, std::string> m_buffered_errors to use proper ErrorItem class with optional Mask to identify which data lanes the Error message applies to.
Refactored ShadingContext::process_errors into a templated helper to serialize batched or non-batched errors up to the ShadingSystem.
Modify ShadingContext::symbol_data to use the symbol's wide_dataoffset() when last execution was batched. …

Add plumbing through ShadyingSystem into Context to support Batched Execution

---

src/liboslexec/constfold.cpp
src/liboslexec/runtimeoptimize.h

Some minor refactoring of the recently introduced get_vec3 introduced
a bug into the constant folding of + and - for mixed floats and
triples: the constant produced was of the type of the first operand,
instead of the result. This fixes.
Added handy helper to make vector constant (and disambiguate it from
the one that makes a color constant). Turns out I then edited more and
didn't use it in this PR, but I still want to keep it.

Fix bug introduced in 1267: botched constant folding.

---

src/cmake/checked_find_package.cmake
src/cmake/externalpackages.cmake

Upon reading cmake docs mre carefully, it's clear that when you pass a
version to find_package (which does much of the heavy lifting inside
checked_find_package), it DOESN'T MEAN you want that version or
later. It means you want to find a version that is "compatible" with
the named version. The meaning of "compatible" is up to the package.
Some packages define it as being >= the requested version. Others
define it as being the same major release, or same major AND minor
release, or exact.
But generally speaking, we only care about the minimum version (e.g.,
"I want FooBar 8.0 or later"). And it's not guaranteed that is what
the package's compatibility will do. In fact, FooBar may be using
compatibility mode "SameMajorVersion", which will make our find of
FooBar succeed for 8.0, 8.1, 8.2, …

Extend checked_find_package with VERSION_MIN and VERSION_MAX

---

CMakeLists.txt
src/cmake/packaging.cmake
src/cmake/testing.cmake

Modeled after recent similar changes in OIIO.
* Detect if OSL is being built as a subproject, and if so, set
`OSL_IS_SUBPROJECT` (a.k.a. `${PROJECT_NAME}_IS_SUBPROJECT`).
* Move all the testing logic out of the main CMakeLists.txt (and a few
testing-related macros from oiio_macros.cmake) and into a new
src/cmake/testing.cmake.
* Move all of the packaging logic out of the main CMakeLists.txt and
into a new src/cmake/packaging.cmake.
* Make all the testing and packaging inactive if this is being built
as a subproject. Also disable the clang-format target for subprojects.

CMake refactoring and subproject friendliness

---

src/liboslexec/llvm_util.cpp

Added missing implementations for LLVM_Util::assume_ptr_is_aligned(llvm::Value* ptr, unsigned alignment) and LLVM_Util::module_string()
These were in the llvm_util.h but not implemented, were missed in previous pull requests and are needed now.  Fixed linker error for upcoming PR's.

Added missing implementations for LLVM_Util methods

---

src/include/osl_pvt.h

During batched analysis we will be figuring out which symbols need to be varying and which can be uniform during batched execution, we will also be figuring out the minimum number of operations which require masking as well as storing/caching some other operation specific flags used later in batched code generation.  We choose to store these analysis results inside Symbol and Opcode directly so that they are efficiently accessible and stable under optimization passes than might invalidate OpcodeVec.

Symbol and Opcode changes to support batched analysis

---

ASWF/Technical-Charter.md

We've tended to have projects embed the mission statement in the charter lately, so pulling what was in the README to add here.
Signed-off-by: John Mertic <jmertic@linuxfoundation.org>

Added mission statement in the charter, pulled from README

---

GOVERNANCE.md

* Nicolas Guiard is a new TSC member representing Isotropix
* Chris Kulla has had a new affiliation for a while now
* Clean up a bit of language left over from when this document was
just a proposal.

Amend GOVERNANCE to list new member and changing affiliations

---

src/build-scripts/install_homebrew_deps.bash

CI Mac: the uninstall of openssl no longer needed, now causes problems

---

src/include/osl_pvt.h

Results of a compare_op and other ops with logically boolean
results under certain conditions could be forced to be represented
in llvm as a boolean <i1> vs. an integer <i32>.  This simplifies
code generation, and under batched execution is a requirement
to make efficient use of hardware masking registers by allowing a
vector of bools <16 x i1> vs. integers <16 x i32>.  However the
underlying OIIO::TypeDesc as well as OSL does not support bools,
therefore they need to be promoted to integers when interacting with
other integer op's.
The value of forced_llvm_bool() is currently only respected during
batched execution.  Forced bools should not be coalesced with regular
ints, only other forced bools.

Add storage to Symbol for analysis result bool forced_llvm_bool().

---

CMakeLists.txt

This PR fixes cmake setup when tests are explicitly disabled ( ```-DOSL_BUILD_TESTS=0``` on cmake cmd line).
The (recently introduced) testing cmake file is only included when that option is enabled yet adding the tests themselves is not checked (and so cmake does not know ```osl_add_all_tests```).
tested local with/without changes (with these changes it works as expected)

fixed cmake setup when tests are disabled

---

.github/workflows/ci.yml

OIIO removed "RB-2.1" branch marker because it's not expecting any
further development in the obsolete 2.1 branch. We still test against
it, though, so replace its designation in our CI with the specific
branch tag of the last OIIO 2.1 release.

Fix CI after OIIO branch markers disappeared

---

src/include/OSL/Imathx/Imathx.h
src/include/OSL/oslconfig.h.in

Also change some refs to std::abs rather than deprecated Imath functions.

Imath 3 support: ImathLimits.h no longer exists

---

src/liboslexec/pointcloud.cpp

Signed-off-by: sandip shukla <sandipshukla11@gmail.com>
Fix unnecessary error messages to stderr for broken point clouds by changing the 
verbose parameter of the Partio::read() calls to false.

Fix unnecessary error messages to stderr for broken point clouds

---

.github/workflows/ci.yml
src/build-scripts/ci-startup.bash

This speeds up CI builds by 50% or more, for PRs that are minor
changes by reusing the compiled results from previous runs.  Most of
the remaining time cannot be squeezed down -- it's the instantiation
of docker containers and running the testsuite itself. But the build
(including of dependencies we build from scratch) is dramatically
faster.
At the same time, remove some commented-out test matrix cases. When/if
we re-enable those tests, we can add those back.

CI: Use ccache + GitHub 'cache' action to greatly speed up CI runs

---

src/liboslcomp/CMakeLists.txt
src/liboslexec/CMakeLists.txt
src/liboslquery/CMakeLists.txt
src/osl.imageio/CMakeLists.txt

Typo prevented visibility hiding from happening properly

---

src/cmake/cuda_macros.cmake
src/cmake/externalpackages.cmake
src/liboslexec/CMakeLists.txt
src/liboslquery/CMakeLists.txt
testsuite/example-cuda/CMakeLists.txt

Minor change for smooth build against upcoming Imath 3.0

---

src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/shadeimage.cpp

The old ones will someday be deprecated, so just doing some opportunistic cleanup.

Update old Strutil::format to new fmt conventions

---

site/spi/Makefile-bits
src/cmake/compiler.cmake
src/cmake/cuda_macros.cmake
src/include/OSL/device_string.h
src/include/OSL/oslexec.h
src/include/OSL/strdecls.h
src/liboslexec/backendllvm.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/opcolor.cpp
src/liboslexec/opmatrix.cpp
src/liboslexec/opnoise.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/splineimpl.h
src/liboslexec/string_hash.h
src/testrender/cuda/optix_raytracer.cu
src/testrender/cuda/rend_lib.cu
src/testrender/cuda/rend_lib.h
src/testrender/cuda/wrapper.cu
src/testrender/optix_stringtable.cpp
src/testrender/optixraytracer.cpp
src/testrender/optixraytracer.h
src/testrender/render_params.h
src/testshade/cuda/optix_grid_renderer.cu
src/testshade/optixgridrender.cpp
src/testshade/optixgridrender.h
src/testshade/render_params.h

This patch changes how strings are handled in the OptiX 7 codepath.  Strings are now handled as hashes which are computed at compile time.  This means a few things:
* strings are no longer copied to the GPU
* we no longer have to create a special CUDA file that contains string pointers (which removes the libnvrtc dependency -- hooray!)
* strings are now hashed with a `constexpr` hash function which requires c++14.  Because we don't have CUDA programs that depend on runtime values (ie. pointers to GPU memory),  I'm hoping compilation should be smoother overall.
* `osl_printf()` output is now handled by the CPU.  `osl_printf()` copies shaders' `printf()` output to a GPU buffer.  After rendering, the CPU reads this buffer and handles all the output.  This means that all strings in the GPU …

change how strings are handled n OptiX 7

---

src/liboslexec/CMakeLists.txt

liboslquery and liboslnoise exist as separate libraries for apps that
only need to query shader parameters or use OSL's noise functions,
respectively, but dont want to pull in the rest of OSL and all its
heavy dependencies (including LLVM). But liboslexec also needs that
functionality and so separately put the individual modules inside.
This was causing some problems for a tricky use case, and I can't
think of a good reason for it to be done this way now. So in this
patch I remove the redundant modules and just make liboslquery and
liboslnoise into *link dependencies* of liboslexec. None of this
should affect downstream projects, I don't think; linking against
liboslexec ought to just automatically pull in those other libs.

Fully split oslquery and oslnoise libraries from oslexec

---

src/liboslexec/shadeimage.cpp

Fix guard so errorfmt is not used with too early an OIIO version

---

INSTALL.md
Makefile

CMake 3.20 compatibility

---

src/liboslexec/llvm_passes.h
src/liboslexec/llvm_util.cpp

Removed use of options.PrintMachineCode since this has been removed as
of llvm 12. Converted uses of DebugLoc::get to DILocation::get since
it has been deprecated and removed as of llvm 12.
PrintMachine code will only be used if llvm is lower than version 12
Pass adjustment as various things have been deprecated or changed
names. (LG)
Signed-off-by: Euan Haahr <euanhaahrmail2@gmail.com>

Various fixes for LLVM 12 compatibility

---

src/build-scripts/build_cmake.bash
src/build-scripts/build_llvm.bash
src/build-scripts/build_opencolorio.bash
src/build-scripts/build_openexr.bash
src/build-scripts/build_pugixml.bash
src/build-scripts/build_pybind11.bash
testsuite/example-cuda/run.py
testsuite/example-deformer/osldeformer.cpp
testsuite/example-deformer/run.py

It seems that our liberal use of cmake argument `--config` should only
be used in conjunction with the `--build` flag, not for the initial
configuration step. Apparently this was just silently ignored for a
long time, but for CMake 3.20, it is an error and breaks a lot of our
CI cases and our build_blah.bash scripts.
A couple of other minor cosmetic fixes in those scripts as well.

CMake 3.20 safety

---

.github/workflows/ci.yml
src/cmake/Config.cmake.in
src/cmake/cuda_macros.cmake
src/cmake/externalpackages.cmake
src/cmake/modules/FindOpenEXR.cmake
src/include/OSL/oslconfig.h.in
src/liboslexec/CMakeLists.txt
src/liboslnoise/CMakeLists.txt
src/liboslquery/CMakeLists.txt

Ever since adding OpenEXR 3.0 support, we had some cases where
installations that built the 2.x IlmBase and OpenEXR portions
separately and installing to separate areas, had trouble being found
properly.
Remove the need to include OpenEXR/OpenEXRConfig.h
Also make some minor changes to ci.yml to make sure we are documenting
the right openexr versions used for each test.

Build: be robust to certain OpenEXR 2.x config files

---

src/liboslcomp/oslcomp.cpp

This fixes #1352 by checking for write errors after writing the `.oso` file. Without it, empty files could be written without error after running out of disk space.
I have not added any new tests, although in #1352 I did provide an example script to demonstrate the problem. I've been unable to find a way of simulating an empty disk without requiring root privilege, which I presume makes it unsuitable as a test.

OSLCompiler : Check for write errors

---

src/liboslexec/llvm_util.cpp

Generating code for calling `prepare_closure` and `gen_closure` was crashing in Blender, with macOS arm64 and LLVM 11.
The code now matches the implementation of the removed LLVM function. For reference:
https://github.com/llvm/llvm-project/commit/836ce9db7f13f15bd8e4c00ab7a07d2b9f946b5e
Existing OSL tests were already crashing, so this is covered.

Fix crash generating closure functions calls with LLVM 11

---

src/cmake/compiler.cmake

This leaves the minimum C++ at 11, but bumps the default (if not set by
the user via CMAKE_CXX_STANDARD) from 11 to 14.
This is meant to start identifying any problems people have switching
to 14. We anticipate a hard switch to 14 minimum before the next OSL
major release. This change is in master only (i.e. future OSL), we would
never change minimum or default C++ standard in the supported release
branches (currently OSL 1.11.x).

Bump the default C++ mode to 14

---

src/liboslcomp/CMakeLists.txt
src/liboslnoise/CMakeLists.txt
src/liboslquery/CMakeLists.txt

* Left out some imath targets in liboslnoise
* Conform a couple libraries to conventions of the ${local_lib} notation
we use in the othe rlibraries.

Some minor cmake touch-ups

---

src/build-scripts/ci-startup.bash

CI script typo kept mac from recognizing ARCH properly

---

src/include/OSL/llvm_util.h
src/include/OSL/oslconfig.h.in
src/include/OSL/oslexec.h
src/include/osl_pvt.h
src/liboslcomp/symtab.cpp
src/liboslcomp/symtab.h
src/liboslexec/backendllvm.h
src/liboslexec/context.cpp
src/liboslexec/instance.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/master.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp
src/testrender/cuda/wrapper.cu
src/testshade/cuda/optix_grid_renderer.cu
src/testshade/optixgridrender.cpp
src/testshade/simplerend.cpp
src/testshade/simplerend.h
src/testshade/testshade.cpp
testsuite/example-deformer/osldeformer.cpp
testsuite/example-deformer/ref/out.txt
testsuite/group-outputs/ref/out.txt
testsuite/layers-entry/ref/out.txt

Up until now, client apps declare which output variables are "renderer
outputs" before shader groups are compiled, and also after a shader is
executed, it is up to the app to extract the individual output values
and do with them what it needs to do. Those outputs live on the shader
heap (the temp storage used to run the shader), and information about
where it lives on the heap can be retrieved via find_symbol() and
symbol_address().
New paradigm:
Various inputs and outputs of shaders live in different memory arenas,
and for those inputs/outputs, the app declares (prior to shader group
compilation) which arena it lives in, its offset within the arena, and
the stride between entries (for different shades, such as different
rays in flight, different points on a mesh, pixels in an image, …

Output variable placement (draft)

---

src/shaders/stdosl.h

This PR adds closure declarations for the MaterialX PBS nodes. A discussion of their design has been ongoing in a thread at the MaterialX GitHub repo. The full history of this discussion can be found here: https://github.com/materialx/MaterialX/pull/614
This is still a draft and additional details will be worked out when reference implementations for these closures are added to `testrender` later. The code is wrapped in ifdefs and no docs or tests has thus been added yet.
@lgritz I assume Autodesk has a corporate CLA signed already, but if not just let me know and we will fix that.

Add declarations of MaterialX closures

---

src/cmake/compiler.cmake
src/cmake/externalpackages.cmake
src/liboslexec/constfold.cpp
src/liboslexec/context.cpp
src/liboslexec/opstring.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/wide/wide_opstring.cpp

Now that gcc minimum is gcc6, remove use of boost::regex

---

.github/workflows/ci.yml
INSTALL.md
src/build-scripts/build_llvm.bash
src/build-scripts/gh-installdeps.bash

* Update the "bleeding edge" CI test to gcc-11, and also LLVM 12,
which we hadn't tested before (in CI).
* Split out a "latest releases" CI test uses gcc10 and LLVM 11.
* Turns out that nothing else on the OSL side needed to be fixed to
accommodate gcc 11 (though you need a very up-to-date OIIO if you
want to compile it with gcc11 unless you turn warnings off).

CI gcc and llvm testing changes

---

src/liboslexec/osogram.y
src/liboslexec/osolex.l
src/osl.imageio/oslinput.cpp
src/testrender/optixraytracer.cpp
src/testrender/simpleraytracer.cpp
src/testrender/testrender.cpp
src/testshade/optixgridrender.cpp

Background: OIIO now has errorf that are explicitly printf-like, and
errorfmt that are explicitly std::format-like, and also an old style
error() that is ambiguous.  The ambiguous calls are (at this moment)
aliases to the printf ones, but will be deprecated at some point (and
may, later when it seems safe, get reborn as the std::format compliant
behavior).
This roots out and removes the last few calls to the old ambiguous
ones from the OSL codebase.

Remove last calls to ambiguous OIIO format functions

---

src/liboslexec/shadingsys.cpp

This feature (used, very possibly, only by me, for debugging)
forces OSL to write an archive that contains the oso files and a
serialized version of the shader network.
If no explicit name is given (by the "archive_filename" attribute), it
picks a name based on the shader group name. But that may not be a
safe string for a valid filename. We already eliminated anything
before the last slash, but it turns out that a colon (':') can also
really mess things up. So this small change protects against that.

Sanitize filenames when using "archive_groupname"

---

src/testshade/testshade.cpp

OIIO 2.3 will rearrange some header files slightly. If you need to use
ImageCache, you must include imagecache.h (duh!). We were accidentally
relying on some leaked definitions in other header files, which will
soon be removed.

Add include to prepare for upcoming OIIO change

---

src/cmake/testing.cmake

Well intentioned attempt to ensure that Cuda runtime library was in
the library path when tests were run, but it clobbered the existing
LD_LIBRARY_PATH.

Test: don't clobber LD_LIBRARY_PATH for optix tests

---

src/include/OSL/oslconfig.h.in
src/include/OSL/oslexec.h
src/liboslexec/backendllvm.h
src/liboslexec/context.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
src/testrender/cuda/wrapper.cu
src/testshade/cuda/optix_grid_renderer.cu
src/testshade/testshade.cpp
testsuite/example-deformer/osldeformer.cpp

This is analogous to the "output placement" that we added recently, but
for input of userdata.
Reminder: "userdata" means shader parameters marked as lockgeom=0 that
are expected to be supplied on a per-shade basis, such as interpolated
vertex data on geometric primitives. The primitive data binds by name to
matching shader parameters.
This patch concerns how the shader gets this per-point data.
Old school: in the middle of the shader, when userdata is needed, the
shader calls osl_bind_interpolated_param(), which makes a callback to
RendererServices::get_userdata(), which... does something magical and
renderer-specific to retrieve the data by name.  This is expensive and
also challenging to implement on the GPU (which is why it remains
unimplemented).
This patch changes the methodology to …

Userdata input placement

---

.github/workflows/ci.yml
INSTALL.md
src/build-scripts/gh-installdeps.bash

Most important: make sure we have a proper VFXPlatfom-2022 like test,
with Python 3.9 and OpenEXR/Imath 3.1.
Fix a few of the "name" entries for tests to match the set of versions
actually present on those images.
Remove apt-get install of libboost-regex-dev, since we use only
std::regex now that we're no longer using gcc4.8.

Bump some CI dependency versions

---

src/liboslexec/opcolor.cpp

functions on the GPU (ie. osl_printf()).

fix problem with unresolved symbols when multiple shaders call certain

---

src/liboslexec/builtindecl.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/shadingsys.cpp

Changed the prototype of osl_get_attribute callback in liboslexec in
order it takes a copy of the attribute TypeDesc casted into a long long
instead of taking a pointer to it. This allows to make it work properly
on GPU else we have an invalid pointer.

Fixed an invalid memory access on GPU while trying to access to the attribute TypeDesc in osl_get_attribute

---

src/include/OSL/Imathx/ImathMatrix.h

Four of the matrix operators were missing the IMATH_HOSTDEVICE modifer and were thus not compiling in device code.
This is just a simple compilation fix, so no tests other than compiling it in cuda, which we did on all supported platforms.

Fix missing hostdevice modifier on some matrix operators

---

src/liboslexec/llvm_instance.cpp
src/testrender/CMakeLists.txt
src/testrender/cuda/rend_lib.cu
src/testrender/optixraytracer.cpp
src/testshade/CMakeLists.txt
src/testshade/optixgridrender.cpp

This removes a race condition when compiling PTX device code in a multithreaded environment.
The problems stems from OptiX6 requiring the `rend_lib.cu` device bitcode to be linked to each compiled shadergroup whereas we only need to link the `rend_lib.cu` device bitcode to one shadergroup in OptiX7.  When I added OptiX7 support, I put a static/global in OSL to ensure that we don't get multiple definitions from `rend_lib.cu` in the device code for OptiX7.  But that's a poor solution for a couple of reasons:
- it's not thread-safe
- it doesn't support recompiling shaders in an interactive environment.
This removes the requirement to supply the `rend_lib.cu` device code when using OptiX7.  But that also means  the renderer now needs to manually link it in.  Both `testshade` and `testrender` …

Removing race condition when compiling for OptiX 7

---

src/liboslexec/llvm_util.cpp

This pull request addresses a compatibility with LLVM 12 due to the change within [LLVM itself](https://reviews.llvm.org/D101650). Additionally, this also fix the merge from release to master on #1402 
N/A See https://reviews.llvm.org/D101650

Fix compatibility with LLVM 12 and up

---

src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/typecheck.cpp
testsuite/oslc-err-write-nonoutput/ref/out.txt
testsuite/oslc-err-write-nonoutput/test.osl

Fixes #1416
In OSL, function parameters must be marked as `output` or they are not
supposed to be writable. In issuing errors when a write is performed on
something not writable, we missed an interesting case:
```
void g(output float b) {
b = 1;  // ok, since b is marked as output
}
void f(float a) {
g(a);  // <--- should be disallowed, g is writing to f's non-output param
}
float x;
f(x);
```
This patch catches cases like these. The new error looks like this:
`test.osl:22: error: cannot write to non-output parameter "a", as passed to function g() as arg 1 (output parameter "b")`

Fix oslc missing a write error on function parameter

---

ASWF/Technical-Charter.md
README.md
src/cmake/check_is_enabled.cmake
src/cmake/colors.cmake

Renaming the master branch to main is imminent. Here are the few
places where we refer directly to branch names that will no longer
exist.
While searching for "master/", I also noticed a couple files that
had the wrong project's copyright boilerplate on it (a lot of the
cmake scripts I write and submit to both projects simultaneously).

Minor docs changes for changing master branch name to main

---

src/liboslexec/llvm_gen.cpp

OSL will call `osl_get_attribute()` with device strings (ustring hashes) when compiling for the GPU (like `osl_printf()`).
No changes to testsuite.  Works locally in our renderer.

osl_get_attribute() should use device strings when compiling for OptiX.

---

.github/workflows/ci.yml
src/build-scripts/ci-test.bash

* Increase testing timeout, some of the batch shading regression tests
seem to take longer than the prior 240s limit.
* Turn off OpenVDB when using the osl:2021 in combination with OpenEXR
3.x -- the version of OpenVDB in the 2021 container is too old to
understand OpenEXR 3.

Fix minor CI issues

---

src/build-scripts/ci-test.bash
src/cmake/testing.cmake

I recently bumped the ctest per-test timeout to 300s because one of the
batched shading regression tests was occasionally taking longer than the
prior limit of 240s.
But there is a better way: Individual tests can have their timeouts
set individually via set_tests_properties(TIMEOUT), so I raised the
timeout to 300s for all tests whose names contain "-reg", also kept it
rather long (the old 240s) for the long render tests that are all named
"render-". Then for everything else, we can actually lower the default
to 60s, since no other tests should be long-running.
(For the curious, the reason these batched regression tests are so
expensive is that they test a bunch of combinations, and they first
run the test in the non-batch scalar mode, then again in batched mode,
and compare the results …

Testing: Adjust timeout strategy

---

src/build-scripts/ci-startup.bash
src/cmake/compiler.cmake

Maybe somebody else is building this as a subproject or has a variable
called "CI"?
* For our CI runs, set an env variable "OSL_CI" (not just generic "CI").
* Default STOP_ON_WARNING to be off for supported releases, only on by
default for main branch where we're actively developing. Because you
want downstream users who are building supported releases to not get
tripped up when their compiler upgrades and there's a new warning.
* Make sure STOP_ON_WARNING is true for our CI runs, even for release
branches -- but now check OSL_CI, not CI, in case somebody else has
set that.
Fixes #1428

Use a project-specific var for whether we're running in CI

---

src/liboslexec/runtimeoptimize.cpp

Alex Wells pointed out that they were never explicitly initialized.

RuntimeOptimizer: Fix messages & unknown_message_sent initialization

---

.github/workflows/ci.yml
INSTALL.md
src/build-scripts/build_pybind11.bash
src/cmake/externalpackages.cmake

* pybind11 2.9.0 release -- bump the vfx2022 and "latest" CI tests to
use it.
* Adjust other CI test pybind11 versions to get good coverage across all
the pybind11 releases, and to synchronize the vfx platfom tests with
the pybind11 release that was current for its respective year.
* Sync build_scripts/build_pybind11.bash with the latest in OIIO, including
bumping the default pybind11 version we download to 2.8.1.
* Opportunistic touch-up of warnings about llvm version to bring
into sync with our actual current requirements.

CI: pybind11 adjustments

---

src/cmake/testing.cmake
src/include/osl_pvt.h
src/liboslcomp/ast.cpp
src/liboslcomp/symtab.cpp
testsuite/oslc-err-struct-print/test.osl
testsuite/oslc-err-type-as-variable/NOOPTIMIZE
testsuite/oslc-err-type-as-variable/NOOPTIX
testsuite/oslc-err-type-as-variable/ref/out.txt
testsuite/oslc-err-type-as-variable/run.py
testsuite/oslc-err-type-as-variable/test.osl

Here was the construct it was confused by:
struct Data {
float height;
};
Data foo(Data a, float b)
{
return Data;   // <----- what's this madness?
}
Curiously, this revealed a source code error in one of our other tests,
oslc-err-struct-print, which had not been detected previously!

oslc: detect using type name as an variable identifier

---

src/include/OSL/oslexec.h
src/liboslcomp/codegen.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
src/testrender/simpleraytracer.h
src/testshade/simplerend.h
src/testshade/testshade.cpp

OIIO's string_view::c_str() was cute, but it's a little dicey and it's
not present in the C++20 std::string_view. We didn't use it in a ton
of places, so replace with other idioms so that in the future we are
better able to interchange with or switch to std::string_view (when
our minimum supported C++ standard is high enough).

Wean ourselves off of OIIO::string_view::c_str()

---

src/include/OSL/oslconfig.h.in
src/include/OSL/oslnoise.h
src/liboslexec/shadeimage.cpp
src/testrender/testrender.cpp
src/testshade/testshade.cpp

New changes in OIIO guards the contents of its Imath.h with the
`OIIO_IMATH_H_INCLUDED` preprocessor symbol. This lets us in OSL
pre-define it to absolutely ensure that OSL headers are including
exactly the Imath headers they want, not accidentally getting the ones
that OIIO includes.
See https://github.com/OpenImageIO/oiio/pull/3322
This present PR is harmless for versions of OIIO prior to that PR being
integrated.

Favor our choice of Imath includes over OIIO's.

---

src/cmake/testing.cmake
src/liboslexec/runtimeoptimize.cpp
testsuite/globals-needed/printbackfacing.osl
testsuite/globals-needed/ref/out.txt
testsuite/globals-needed/run.py
testsuite/runtest.py

Fix a bug where utilizing the backfacing() shadeop would not mark the N and I globals as needed.
During the OSL runtime optimizations, if we find a backfacing() shadeop, we now add both N and I
to the list of needed globals, as the underlying implementation of that shadeop relies on them.
This is tested by the globals-needed test.  Additionally it adds the ability to filter
out.txt in a test before diff'ing by including a regular expression for the filter in the filter_re variable.
This was so that the output from the debug mode of testshade could be limited to only
the line of interest to this test.
- [ x] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [ x] I …

Add N/I to globals needed list when backfacing() shadeop is used

---

src/liboslexec/shadingsys.cpp

The str() method was not part of the final C++17 std::string_view.
To ensure future interchangeability with std::string_view, change the
few places where we call str() in the OSL code base.

Avoid OIIO::string_view::str()

---

src/cmake/externalpackages.cmake
src/liboslexec/batched_llvm_gen.cpp
src/testrender/optixraytracer.cpp
src/testshade/optixgridrender.cpp

Turn on warnings about OIIO::Strutil::format and ustring::format
We should be using Strutil::sprintf / ustring::sprintf, or upgrading
entirely to Strutil::fmt::format / ustring::fmtformat.
Some day, the plain "format" will be deprecated, then disappear, then
reappear as compatible with std::format (as are fmt::format/fmtformat now).

Start switching over from sprintf to fmt

---

src/cmake/Config.cmake.in

Make exported cmake configs relocatable by using relative paths

---

testsuite/runtest.py

Additionally, allow custom command line arguments to run after each
image is loaded, but before the comparison.

Testsuite: allow using oiiotool for image diffs instead of idiff

---

src/cmake/compiler.cmake

Slight reworking of -Werror logic to let the default behavior be
changed by setting a cmake variable. In particular, this allows us to
make a CI build disable -Werror when we need to.
Previously, having the "OSL_CI" env variable set trumped all else and
forced -Werror. Now it just contributes to the default behavior, but
setting `-DSTOP_ON_WARNING=OFF` and cmake config time can still
disable it.

Build: allow -Werror to be disabled even on CI branches

---

.github/workflows/ci.yml

This eliminates a huge amount of redundancy in our CI descriptions --
instead of the entire CI logic replicated for each test in its own
universe, we group tests into (a) all the ones based on ASWF VFX
Platform containers, (b) non-VFXP-year oddballs run on Ubuntu, (c) Mac
tests, (d) clang-format verification. Each has the build logic
expressed once, and a short list of variables that change for each
individual test of that category.
This organization is much easier to read, maintain, modify tests, or
add new test variants, and cuts the size of the ci.yml file by over 50%.

CI: refactor ci.yml to use strategy matrix

---

src/liboslexec/wide/wide_optexture.cpp

Changed a function signature in OIIO master that threw us off here
just a tad, as there was no direct type conversion the compiler could
figure out on its own. Easy adjustment gives it the right hint.

Fixes for recent OIIO TextureSystem API changes

---

src/liboslexec/backendllvm.cpp

llvm_load_device_string wasn't considering temporary string variables,
only declared local variables.

Fix GPU codegen crash

---

src/include/OSL/Imathx/Imathx.h
src/include/OSL/matrix22.h
src/include/OSL/oslconfig.h.in

Also change the one exception mentioned to a std one, matching
Imath 3.x and insulating us from any of the old Iex custom exceptions
from Imath 2.x.

Hide Matrix22 definition better -- it's not part of any public API

---

src/liboslexec/accum_test.cpp
src/liboslexec/automata.cpp

MSVC defines `long` as a 32-bit type even on 64-bit machines, so switch to `size_t` instead.
For formatting, print pointers as pointers instead of casting to `long`.

Fix minor warnings about pointer casts on windows

---

CMakeLists.txt
src/include/OSL/oslconfig.h.in
src/liboslcomp/oslcomp_pvt.h
src/liboslcomp/osllex.l
src/liboslexec/osogram.y
src/liboslexec/osolex.l
src/testrender/simpleraytracer.cpp
src/testrender/testrender.cpp
src/testshade/optixgridrender.cpp

A small instalment on the long-term shift from printf-style formatting
to std::format style formatting.
Define preprocessor OSL_INTERNAL, which is defined when compiling OSL
itself, but will not be defined for downstream projects using the OSL
headers.
When building OSL, enable the symbol OIIO_ERRORHANDLER_HIDE_PRINTF,
which causes ErrorHandler methods using the old conventions to be
marked as deprecated and generate warnings.
Clean up all the calls revealed by those warnings. (And
opportunistically clean up some other things that happened to be in
the same files.)

Some fmt conversion

---

.github/workflows/ci.yml

CI: bump 'latest' openexr and pybind11 versions

---

src/cmake/Config.cmake.in

In our generated OSLConfig.cmake, we inserted a find_dependency(Imath)
that accidentally demanded the OpenEXR_VERSION (should have been
Imath_VERSION). That works fine as long as Imath version is the same
(or higher) than the OpenEXR version. But if the installed OpenEXR
version is somehow ahead of the Imath version, it will fail.

Fix generated OSLConfig.cmake -- wrong Imath version

---

src/cmake/cuda_macros.cmake
src/liboslexec/llvm_gen.cpp
src/testrender/CMakeLists.txt
src/testrender/cuda/rend_lib.cu
src/testrender/cuda/rend_lib.h
src/testrender/cuda/wrapper.cu
src/testrender/render_params.h
src/testshade/CMakeLists.txt
src/testshade/cuda/optix_grid_renderer.cu
src/testshade/optixgridrender.cpp
src/testshade/optixgridrender.h
src/testshade/render_params.h
src/testshade/testshade.cpp

This PR adds very basic support for named transforms to testrender and testshade. It's a linear scan through a list of transform names to find the corresponding matrix. Although this is a far-from-ideal solution for real world scenarios with many named transforms, it is sufficient to enable further testing and development.
No new tests have been added, but all previously-passing tests still pass. It would be possible to enable the matrix tests in the testsuite if not for some small differences in error reporting:
CPU:
```
Testing getmatrix for unknown space name:
ERROR: Unknown transformation "foobar"
'foobar' matrix not found, as expected
```
GPU:
```
Testing getmatrix for unknown space name:
'foobar' matrix not found, as expected
```

OptiX matrix fixes

---

.github/workflows/ci.yml
src/cmake/checked_find_package.cmake
src/cmake/compiler.cmake
src/cmake/fancy_add_executable.cmake

checked_find_package:
* Optional SETVARIABLES gives a list of vars to set to TRUE if the package
is found.
* Optional DEBUG flag turns on extra debugging information about how the
package is found.
* Optional PREFER_CONFIG uses a dependency's exported config, if available,
rather than our Find module.
* Global ALWAYS_PREFER_CONFIG option can be set to ON to always prefer
config over Find modules for all dependencies.
fancy_add_executable:
* `-DENABLE_INSTALL_<executable>=OFF` lets you turn off the installation
of an executable.
other:
* Change the target name for doing the clang-format over the code to
"run-clang-format", because "clang-format" is an imported target name
of the libclang exported cmake (which we may wish to use soon).

Build: cmake improvements (ported from OIIO)

---

src/include/OSL/oslconfig.h.in
src/include/OSL/oslexec.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
src/liboslexec/shadingsys.cpp
testsuite/opt-warnings/ref/out.txt
testsuite/opt-warnings/test.osl

New classes of warnings triggered when enabling option "opt_warnings":
* Creation of new strings mid-shader.
* Access to the characters of strings mid-shader.
We already warned about texture access by name that could not be
turned into a handle.
In all of these cases, we only warn *after* runtime optimization, so that shader
idioms in the source code that appear to do these forbidden things will not warn
as long as they can be reduced to safe operations in the course of the runtime
optimization step.

More comprehensive warnings about things that don't optimize away

---

src/cmake/cuda_macros.cmake
src/cmake/llvm_macros.cmake
src/include/OSL/oslexec.h
src/liboslcomp/osllex.l
src/liboslexec/CMakeLists.txt
src/liboslexec/osolex.l

The latest changes to leverage llvm-bitcode for renderer services did not build properly on windows. This set of patches should fix this along with a few other minor things.
I have a feeling there is probably a more "Cmake native" way of getting the path to the llvm-as and llvm-link binaries. I'm definitely open to suggestions here.

Windows build fixes for recent free function render services

---

src/cmake/compiler.cmake
src/include/OSL/platform.h

The Intel OneAPI LLVM-based C++ compiler, as we download it from Intel
for our CI, bumped from 2022.0.0 to 2022.1.0.
New warning popped up -- newest Intel LLVM-based compiler warns about
overriding certain floating point math flags.

CI: adjust to upgrading Intel Clang compiler to 2022.1.0

---

src/include/OSL/batched_shaderglobals.h
src/include/OSL/llvm_util.h
src/include/OSL/oslclosure.h
src/include/OSL/wide.h
src/liboslexec/CMakeLists.txt
src/liboslexec/batched_analysis.cpp
src/liboslexec/batched_backendllvm.cpp
src/liboslexec/batched_backendllvm.h
src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/batched_llvm_instance.cpp
src/liboslexec/builtindecl_wide_xmacro.h
src/liboslexec/context.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/wide/wide_opclosure.cpp

- [ X] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [ X] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [ X] I have updated the documentation, if applicable.
- [ X] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [ X] My code follows the prevailing code style of this project.

Batched closures

---

src/liboslexec/constfold.cpp
src/liboslexec/shadingsys.cpp

We have constant folded endswith() for a long time. Dunno why we
overlooked startswith, but here it is.
Also simplified endswith to use Strutil::ends_with instead of replicating
the logic here for no good reason.

Constant folding of startswith()

---

src/liboslexec/backendllvm.cpp
src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/instance.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/shadingsys.cpp
src/liboslexec/typespec.cpp

Banish the last of the sprintf calls (except the handful that need
to be there, because such formatting is still supported in shaders
themselves, so something needs to understand them).

More printf -> fmt conversion

---

src/cmake/compiler.cmake
src/include/OSL/batched_shaderglobals.h
src/include/OSL/llvm_util.h
src/include/OSL/oslclosure.h
src/liboslcomp/ast.cpp
src/liboslcomp/typecheck.cpp
src/osl.imageio/oslinput.cpp
src/osltoy/osltoyrenderer.cpp
src/testrender/cuda/optix_raytracer.cu
src/testrender/cuda/quad.cu
src/testrender/cuda/rend_lib.cu
src/testrender/cuda/sphere.cu
src/testrender/cuda/wrapper.cu
src/testshade/batched_simplerend.cpp
src/testshade/batched_simplerend.h
src/testshade/cuda/optix_grid_renderer.cu
src/testshade/optixgridrender.cpp
src/testshade/optixgridrender.h
src/testshade/render_params.h
src/testshade/simplerend.cpp
src/testshade/simplerend.h
src/testshade/testshade.cpp
src/testshade/testshade_dso.cpp
src/testshade/testshademain.cpp

The next round of adding files to the clang-format regime.
Like last time, I've broken it into a few distinct commits so that I can attribute
the changes to whomever was the dominant contributor to the changed files,
rather than make it seem like I touched everything. So there are commits here
for each of Cliff, Alex, and Tim. (And also a bunch legitimately for me, in a
separate commit -- for those files that either I was the primary author of, or
which had sufficiently mixed authorship already.)

clang-format

---

src/shaders/vector4.h

I think we were multiplying by the transpose. Can people please check my
math? This is obviously easy to get confused about. Remember that by
our conventions, points are column vectors and matrices have the
bottom row containing the translation (like RenderMan, not like math/physics),
and they are stored in memory in row-major order (like C, not like Fortran).

Fix incorrect transform(m44,v4) in vector4.h

---

src/cmake/compiler.cmake
src/liboslexec/accum.cpp
src/liboslexec/accum_test.cpp
src/liboslexec/automata.cpp
src/liboslexec/backendllvm.cpp
src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/closure.cpp
src/liboslexec/constfold.cpp
src/liboslexec/dictionary.cpp
src/liboslexec/loadshader.cpp
src/liboslexec/lpexp.cpp
src/liboslexec/opclosure.cpp
src/liboslexec/opmatrix.cpp
src/liboslexec/opmessage.cpp
src/liboslexec/opstring.cpp
src/liboslexec/oslexec.cpp
src/liboslexec/pointcloud.cpp
src/liboslexec/shadeimage.cpp
src/liboslexec/typespec.cpp
src/liboslexec/wide/wide_opmessage.cpp

More clang-format

---

src/liboslexec/llvmutil_test.cpp
src/liboslnoise/oslnoise_test.cpp
src/oslinfo/oslinfo.cpp
src/osltoy/osltoymain.cpp
src/testrender/testrender.cpp
src/testshade/testshade.cpp

In a few of my big clang-format revisions, I was over-zealous, and did
not realize that I was making the command line option parsing unreadable.
Revert those sections.

Revert some formatting

---

src/liboslexec/llvmutil_test.cpp
src/liboslnoise/oslnoise_test.cpp
src/oslinfo/oslinfo.cpp
src/osltoy/osltoymain.cpp
src/testrender/testrender.cpp
src/testshade/testshade.cpp

We'd been waiting until the minimum OIIO requirement was high enough
to include support for the newer syntax.

Change OSL's ArgParse use to the modern syntax

---

CHANGES.md
CMakeLists.txt
INSTALL.md

Aiming to declare a stable beta soon and release circa SIGGRAPH.
Primarily, this branch is to allow us to continue changing main in
ways that would be destabilizing before the release.

Branch for eventual release, call it alpha

---

src/shaders/stdosl.h

Running oslc -DMATERIALX_CLOSURES causes the following error due to unsupported characters in the header file : 
`error: No shader function defined`
- [ x] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [ x] I have updated the documentation, if applicable.
- [ x] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [ x] My code follows the prevailing code style of this project.

Unwanted characters in stdosl

---

src/include/OSL/llvm_util.h
src/liboslexec/backendllvm.cpp
src/liboslexec/backendllvm.h
src/liboslexec/llvm_util.cpp

Most LLVM API IR calls that generate ops allow an optional name of the
llvm symbol that will hold the result of the operation. By default, it
will make one up, such as "%37", "%38", etc. Needless to say, these
are difficult to understand when reading volumes of IR dumped for
debugging purposes.
So in this patch, I'm starting to expose the ability for our own code
to pass names through our wrapper functions. I needed this for some
deep debugging.
I haven't instrumented the entire set, just trying it on for some of
the specific areas I needed to debug. But this is a useful first step.

Allow naming of llvm symbols for many ops

---

.github/workflows/ci.yml
.github/workflows/scorecards.yml
SECURITY.md

* Set up a SECURITY.md explaining how to confidentially report
vulnerabilities.
* Create scorecards.yml workflow to run OSSF scorecard to check supply
chain security issues.
* Use exact SHA's for actions versions to guard against hijacked
actions repos that might try to substutite something else at the
version tag we use.
* Make sure actions we use don't get write perms on our repo.
* Tried to use harden-runner action to ensure no actions on the runner
overwrite source code or have unauthorized outgoing net connections
during the GHA run, but currently leaving it disabled because of too
many false positives -- it flags every dependency download as a case
of altering source code. Which it technically is, but it doesn't
matter for any jobs that aren't producing any artifacts that will be …

Security policy fixes

---

src/build-scripts/serialize-bc.py

Signed-off-by: Adrien Herubel <adrien.herubel@autodesk.com>
This PR fixes the following two issues I encountered while building the head of the main branch on Linux (Centos 7)
`/bin/sh: /home/herubea/dev/vanilla_osl/OpenShadingLanguage/src/build-scripts/serialize-bc.py: Permission denied
`
It looks like the serialize-bc.py script is missing the execution permission, and a shebang declaration for running the script as python.

Fix permission error and build errors when running serialize-bc.py on Linux

---

src/include/OSL/llvm_util.h
src/include/OSL/rendererservices.h
src/liboslexec/backendllvm.cpp
src/liboslexec/backendllvm.h
src/liboslexec/batched_backendllvm.cpp
src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/batched_llvm_instance.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/testrender/optixraytracer.cpp
src/testrender/optixraytracer.h
src/testshade/optixgridrender.cpp
src/testshade/optixgridrender.h
testsuite/example-cuda/cuda_grid_renderer.h

Big string cleanup, yet again, for GPU. We still had this tricky
double indirection happening with strings for OptiX -- the string was
a pointer to a "global", which in turn held the hash. No, throw all
that out.  Just directly store strings as the ustring hash on
OptiX. No extra indirection. Many fewer differences between how things
are handled on OptiX versus CPU (except for the fact itself that the
"string" holds the hash rather than the char*).
Some details worth noting:
* LLVM_Util loses "type_string()" and calls it "type_ustring()" to
emphasize it's the type we're using to represent a ustring, and
definitely not a C or C++std string. Also, LLVM_Util itself now lets
the caller tell it whether it prefers that the representation of a
ustring be the charptr or the hash, and then handles …

GPU string overhaul

---

testsuite/texture-errormsg/ref/out-travis.txt
testsuite/texture-errormsg/ref/out.txt
testsuite/texture-errormsg/test.osl

It printed the u,v coordinates where the error was first discovered.
This is not necessarily deterministic, of course!

Fix error message for texture-errormsg test

---

.github/workflows/ci.yml

This was resulting in confusing artifact names for the Intel compiler
cases.

Label ci jobs better

---

src/liboslcomp/typecheck.cpp

Didn't properly detect the disallowed use of arrays for the false
clause because we checked `t` twice.
Yay for static analysis!

Fix typo error that prevented correct typecheck of ternary

---

src/liboslexec/backendllvm.cpp

Fix slightly incorrect code generation when getting a string address
for GPU.

GPU string fix -- needed missing cast

---

.github/workflows/ci.yml
src/build-scripts/install_homebrew_deps.bash

This cleans up some recently-failing CI tests.

CI: For Mac, test python 3.9 for MacOS11, and 3.10 for MacOS12

---

src/testrender/optics.h
src/testrender/shading.cpp

This allows the refraction index to be detected even if a medium closure
is not present. Additionally, the medium detection now traverses layer()
closures.

Add missing cases for MaterilaX closure refraction index detection

---

src/liboslexec/opcolor.cpp
src/liboslexec/opcolor_impl.h
src/liboslexec/splineimpl.h
src/liboslnoise/simplexnoise.cpp

We had been using clang/llvm 12 and when trying out 14 I started
getting test failures with OptiX compliaining about duplicate
symbols. They all seemed to be the things we declared as
OSL_CONSTANT_DATA. It looks like there's a difference in llvm 12 vs 14
in how the generated PTX marks its symbol visibility.
The solution (thanks to a clever suggestion by Alex Conty) was just to
enclose those declarations in anonymous namespaces. Works like a
charm!

Fix OptiX + clang14 issue with duplicate symbols

---

.github/workflows/analysis.yml
src/build-scripts/ci-build.bash
src/cmake/compiler.cmake
src/liboslexec/llvm_util.cpp
src/liboslexec/oslexec_pvt.h
src/testrender/testrender.cpp
testsuite/runtest.py

* Minor changes to fix a couple more warnings given by SonarCloud
static analysis.
* Get the code coverage enabled, it wasn't running properly.
* testrender: allow secret TESTRENDER_AA to override command line --aa
* runtest.py: allow secret OSL_TESTSUITE_SKIP_DIFF to force skipping
the reference comparison step.
* For analysis run, set TESTRENDER_AA=1 to keep the tests from being
prohibitively expensive, and OSL_TESTSUITE_SKIP_DIFF=1 to keep it
from failing because the aa=1 images are different.

Sonar warning fixes and improvements

---

src/cmake/compiler.cmake

Simplify clang-format call now that we include virtually everything

---

src/liboslexec/backendllvm.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

In multithreaded environments, use of global counter ids inside function and variable identifiers in generated ptx code leads to cache misses during OptiX module compilation.
With this change we assume unique shadergroup names, and remove the non-deterministic ids. In my testing, everything is still OptiX-compatible even with duplicate shadergroup names, but I'm not sure I've considered all the valid cases.
Existing tests pass; I can add tests that run shaders twice and grep the logs for cache misses if desired.

Generate deterministic ptx for OptiX cache hits

---

src/doc/languagespec.tex
src/shaders/stdosl.h
testsuite/runtest.py

* Change the languagespec to document the new MaterialX-synchronized
closures.
* Document the old ones as "deprecated" -- still supported for 1.x but
assumed to be on the slate for removal in OSL 2.x.
* Change stdosl.h so that the new closures, instead of being seen only
if MATERIALX_CLOSURES is defined, to being enabled by default, but
(for now) can be disabled if NO_MATERIALX_CLOSURES is defined.

New closure docs

---

.github/workflows/analysis.yml
src/build-scripts/ci-coverage.bash
src/liboslexec/llvm_gen.cpp

* Exclude osltoy from coverage analysis, since we don't have a way to
run it from CI
* Run batch shading for analysis to get better code coverage
* llvm_gen_select: extra check that we can't overrun memory of cond[]

Sonar static analysis improvements

---

src/include/OSL/oslnoise.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/wide/wide_ophash.cpp

Today's branching of OIIO 2.4 and subsequent changing of its master
branch to think it's "2.5" seems to have triggered an automatic fuse
that annotates a particular function in OIIO as deprecated for version
2.5 and beyond. OSL was still calling the old version, so some
immediate changes are necessary to call the correct new name when
using a new OIIO.

Deal with deprecated bit_cast function in OIIO 2.5

---

src/liboslexec/runtimeoptimize.cpp

In the course of our runtime optimization of shader networks, we
generate lots of new constant symbols (for example, as we optimize an
"a = b + c" into "a = newconst" if b and c can be determined to be
constants). The new constants are named with a numerical suffix doled
out in a sequental manner.
I've always thought that maybe it would be helpful for me when
debugging optimizer output if the name of the symbol also revealed the
value of the constant it held (when possible). Never did anything
about it.
Now it turns out that this has an application for JIT to PTX, where
the PTX cache can save compilation-to-PTX time if it encounters LLVM
IR that is exactly the same as it has seen before and is cache.  If
the constants are generated in a different order, it generates
non-functional, purely …

Rename compiler-generated constants non-sequentially

---

.github/workflows/analysis.yml
src/build-scripts/ci-test.bash
src/cmake/testing.cmake

We had hard-coded longer allowable timeouts for particular testsuite
tests. But for the static analysis runs, it takes extra long and we
need a way to tell it to increase the timeouts even more, and to
exclude the longest running tests from the analysis coverage run (it's
not necessary to run those tests, they don't increase coverage enough
to justify being an hours long run).

Build/test: parameterize the timeout for expensive tests

---

src/testshade/testshade.cpp

In testshade, there was a "loop" that wasn't really a loop, and it
was getting flagged by static analysis as being fishy. This patch
rewrites it as an "if".
Also take the opportunity to change from stream output to OSL::print
formatted output.

Rewrite confusing loop in testshade for clarity

---

src/liboslexec/batched_analysis.cpp

The little ReadEvent class had two members that are never set when
OSL_DEV is not defined, nor are they accessible (the accessor
functions also are disabled based on OSL_DEV). It looked to the static
analyzer like the data members were uninitialized, which they were. Add
OSL_DEV guards around the declarations of those members as well, so
they aren't even present in the struct when not needed for this
debugging mode.
Food for thought: another alternative is to keep the members but just
remove the OSL_DEV guards entirely -- just let the two int data
members be used all the time, not just for OSL_DEV. It's too small to
have any perf penalty, and it unclutters the declaration by removing
all those `#ifdef` lines.
For that matter, I also wonder if there's any real point to having
private …

Batched analysis: ReadEvent remove uninitialized members

---

src/cmake/testing.cmake
src/liboslexec/instance.cpp
testsuite/initops-instance-clash/ref/out.txt
testsuite/initops-instance-clash/run.py
testsuite/initops-instance-clash/test.osl

This is a tricky situation to describe. Consider this shader:
shader test (float A = 0.5,
float B = A)
{
printf("A = %g, B = %g\n", A, B);
}
By default, A is 0.5 and B gets A's value, also 0.5. If you give A a different instance value, like 1.0, then B will also get the same value, they'll both be 1.0.  If you give B an instance value, that will be used for B rather than copying A's value, like this:
$ testshade  -param B 1.0 -shader test test
A = 0.5, B = 1
But there is a corner case bug: if we assign B an instance value of 0.0, it will incorrectly fall into a special case where it thinks it gets a default value, only coincidentally because 0.0 is in an unused slot for the default value (unused because it has no default -- its default comes from "init ops", that assignment).
$ testshade …

Bug fix: assigning init-op param its default value as instance got lost

---

CMakeLists.txt

Rather than specify the version in the usual project() statement,
project (OSL VERSION 1.13.0.0 ...)
this patch decouples it
set (OSL_VERSION "1.13.0.0" CACHE STRING "Version")
project (OSL VERSION ${OSLVERSION} ...)
thus allowing the possibility of overriding the version number at build confuguration time (`cmake -DOSL_VERSION=3.1.4.1`).
This should be used with extreme caution. Probably never used by most people. I don't need to describe all the ways that things can go sideways if you make your build of x.y.z.w actually be arbitrarily different from the x.y.z.w that everyone else uses and that is documented.
That said, there are two scenarios I have in mind for which this ability is very useful:
1. Sometimes, we add or deprecate API features "in advance" by having an `#if` enable or …

Build: Make the version number be a cmake cache variable

---

src/doc/languagespec.tex

Makes a few fixes to osl-languagespec.pdf

Docs: Minor spec typos

---

.gitignore

direnv (https://github.com/direnv/direnv) can be used for local developer workflow enhancements.  direnv uses .envrc file for configuration.  Because .envrc is usually specific to a developer workflow, it is generally not committed.
None
*just emailed my signed CLA today*
Signed-off-by: Mark Sisson <5761292+marksisson@users.noreply.github.com>

add .envrc to .gitignore

---

src/testshade/testshade.cpp

This was meant to work all along, which is why this patch is so small!
But a tiny detail -- not explicitly passing info about the `--help` argument -- made ArgParse substitute its own default, which exits after printing the usage info. But, as I apparently meant to do all along, if you specify it explicitly, you get to handle it, and the way we handled it also printed the extra information.
Anyway, with this patch, `testshade --help` not only prints all the testshade command options, but also it prints some information at the end about some of the build settings of OSL, versions of key dependencies, hardware info, and a run-down of the ShadingSystem options. This can be helpful for debugging.

Make `testshade --help` print texturesystem options and hardware info

---

src/include/OSL/platform.h
src/liboslexec/batched_analysis.cpp
src/liboslexec/constfold.cpp
src/liboslexec/pointcloud.cpp
src/liboslexec/shadeimage.cpp
src/liboslexec/wide/wide_oppointcloud.cpp
src/testshade/testshade.cpp

We use OIIO_ALLOCA in many places. Make an OSL version and put it in platform.h.

OSL_ALLOCA

---

src/liboslexec/lpeparse.cpp

Several places in leparse.cpp were found by static analysis to have memory leaks -- results of calling _parse() that, in the case of early exists in error conditions, never got deleted.
I also did some other modernization: changed NULL to nullptr, changed some loops to more compact range-for, utilize some Strutil helpers that will be more efficient than the alternative std::string manipulation.

Fix memory leaks found by static analysis in leparse.cpp

---

src/liboslexec/lpeparse.cpp

Fix LPE leak in error condition

---

.github/workflows/ci.yml
INSTALL.md
src/cmake/externalpackages.cmake
src/liboslexec/batched_rendservices.cpp
src/liboslexec/rendservices.cpp

Traditionally, OSL has supported building against the current and also the previous supported version of OIIO, but not necessarily any older.
With OIIO 2.4 released (any day now), and OSL "main" is actually going to be next year's supported release, it seems reasonable to change the forward-looking development of OSL to have a minimum of OIIO 2.3, which means that OSL-next will support OIIO 2.3, 2.4, and the currently-in-progress 2.5 (or whatever it's called by that point).
The main reason to do this bump is because we'd like to depend on the ustringhash class, and possibly other things we will probably be able to easily backport to 2.3 but not to 2.2.

Raise OIIO minimum to 2.3

---

.github/workflows/analysis.yml
sonar-project.properties

* For analysis, USE_QT=0 will disable osltoy from building (since we don't/can't test it in the testsuite, it's unexecuted but really shouldn't count against our code coverage metric).
* Exclude Imath duplicate headers from Sonar analysis.

CI: Improvements to the coverage analysis

---

src/include/OSL/oslconfig.h.in
src/liboslcomp/oslcomp_pvt.h
src/liboslcomp/symtab.h
src/liboslexec/automata.h
src/liboslexec/batched_analysis.cpp
src/liboslexec/dictionary.cpp
src/liboslexec/loadshader.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/pointcloud.cpp
src/liboslexec/pointcloud.h
src/liboslexec/runtimeoptimize.h
src/osltoy/osltoyrenderer.h
src/testrender/optixraytracer.h
src/testrender/simpleraytracer.h
src/testshade/batched_simplerend.h
src/testshade/optixgridrender.h
src/testshade/simplerend.h
testsuite/example-cuda/cuda_grid_renderer.h

Define std::hash for ustring and ustringhash, when not using an OIIO new enough to do so.
Define std::less for ustringhash, when not using an OIIO new enough to have operator< defined for ustringhash (will be fixed separately).
No need now for ustringHash, which is also unwisely similar to ustringhash, just use std::hash instead.

Hashing cleanup for ustrings

---

sonar-project.properties
src/testshade/CMakeLists.txt

We compile testshade.cpp twice -- one for a special "does it compile as a DSO" check but that isn't run from the testsuite. This was causing the coverage analysis to think nothing in testshade.cpp (at least one copy of it) was getting run, which is technically true, and counting all of its lines as untested for the coverage analysis. Just exclude that funny dso build from the coverage case.
Also exclude anything in src/build-scripts from coverage analysis, that's not code that ships, so to speak.
We're trying to chip away at untested code bit by bit to get our coverage to over 80% of lines. We're getting close.

CI: Disabling dso testshade to fix coverage missing testshade.cpp

---

src/include/OSL/mask.h

The immintrin.h header is required for the implementation of the popcount and coutr_zero functions only when the Intel compiler is used. Move the inclusion accordingly. The current state breaks build on platforms that don't provide the header, but provide the alternative means (gcc/clang built-ins, etc).
N/A
This is not a copyrightable work.

include the immintrin.h header only when needed

---

src/include/OSL/llvm_util.h
src/include/OSL/oslexec.h
src/liboslexec/batched_llvm_instance.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp

Fully deprecate LLVM_Util::internalize_module_functions

---

.github/workflows/analysis.yml
src/include/OSL/llvm_util.h
src/liboslexec/llvm_util.cpp
src/testrender/testrender.cpp
testsuite/render-bumptest/run.py
testsuite/render-cornell/run.py

Looking at the code coverage report and trying to get a higher coverage amount, employing two strategies: (a) remove unused code that is not covered because it's... unused; and (b) test things that are used but aren't in the test run. Details follow.
Remove deprecated version of LLVM_Util::make_function.
Disable contents of dump_struct_data_layout when OSL_DEV is not defined, it will never be called in any other circumstances -- it's strictly a debugging tool, not part of the shipping library.
When OSL_USE_OPTIX is not enabled, exclude compiling contents of ptx_compile_group.
get_alignment can also be OSL_DEV only as well as simplified
Arbitrarily pick a couple of render tests to use llvm_opt levels 12 and 13 to verify that they work correctly. (That's a couple hundred lines of pass setup …

Improve testing coverage

---

CMakeLists.txt
src/include/OSL/batched_rendererservices.h
src/include/OSL/oslconfig.h.in
src/include/OSL/rendererservices.h
src/include/OSL/wide.h
src/liboslexec/batched_rendservices.cpp
src/liboslexec/constfold.cpp
src/liboslexec/optexture.cpp
src/liboslexec/pointcloud.cpp
src/liboslexec/pointcloud.h
src/liboslexec/rendservices.cpp
src/liboslexec/wide/wide_opmatrix.cpp
src/liboslexec/wide/wide_oppointcloud.cpp
src/testrender/optixraytracer.cpp
src/testrender/optixraytracer.h
src/testrender/simpleraytracer.cpp
src/testrender/simpleraytracer.h
src/testshade/batched_simplerend.cpp
src/testshade/batched_simplerend.h
src/testshade/optixgridrender.cpp
src/testshade/optixgridrender.h
src/testshade/simplerend.cpp
src/testshade/simplerend.h
testsuite/example-cuda/cuda_grid_renderer.cpp
testsuite/example-cuda/cuda_grid_renderer.h

The first step of the great ustringhash conversion: This changes all RendererServices methods (i.e., callbacks to the renderer from the shader JITed code) that used to take ustring parameters, switched to take ustringhash instead.
The second step -- which I will tackle after this part is merged -- will be to fully switch the in-memory representation of strings during shading execution to ustringhash on the CPU (thus matching how we've been doing it on GPU and making a number of data stuctures and representations identical/shared for CPU and GPU).
But in the mean time, this lets renderers get started changing their RendererServices specializations. Just like with OSL's internal implementation, it may be easier for renderers to break the job into phase I (rendererservices) and phase II …

Move string representation entirely to ustringhash -- phase I

---

src/liboslexec/opcolor.cpp
src/liboslexec/opcolor_impl.h
src/liboslexec/splineimpl.h
src/liboslnoise/simplexnoise.cpp
src/testrender/optixraytracer.h
src/testshade/optixgridrender.h

LLVM 14 introduced two ptx regressions to our file-scoped static variables:
1) They gained the .visible directive
2) They stopped being optimized out when unused
This lead to duplicate symbol errors when building an OptiX pipeline with multiple shaders.
We attempted a fix using anonymous namespaces in #1561, but kept the static keyword, resulting in a partial solution.
Removing static generates ptx that matches LLVM 12 for the affected variable definitions.
-----
Here's a section of `group_0.ptx` from `testoptix-noise`, before and after:
```
Before:
.visible .const .align 4 .b8 _ZN11OSL_v1_13_23pvt6Spline12_GLOBAL__N_19gBasisSetE[408] = {...};
.visible .const .align 64 .b8 _ZN11OSL_v1_13_23pvt12_GLOBAL__N_112_GLOBAL__N_116cie_colour_matchE[972] = {...};
.visible .const .align 4 .b8 …
```

Fix ptx symbol visibility regression

---

src/cmake/testing.cmake

Wow, this has been lurking for a while. Our Findpartio.cmake tries looking for a partio exported config, but if not found, falls back to a simple code to find it manually.
All was fine with the fallback code, which if found would set both "partio_FOUND" and "PARTIO_FOUND". But the config file, if found -- only for the newer partio versions -- only set partio_FOUND. And in that circumstance, we were not seting up the pointcloud tests!
Although the partio tests were running in CI (thankfully), I was not running them locally on my machine with a new-ish partio.

Testing: run pointcloud tests when partio is found

---

src/cmake/modules/FindLLVM.cmake

This PR fixes a linker error that happens when building for windows
Linker errors where (similar to):
```
clangSema.lib(SemaRISCVVectorLookup.obj) : error LNK2019: unresolved external symbol "public: static class llvm::Optio
nal<class std::vector<class clang::RISCV::RVVType *,class std::allocator<class clang::RISCV::RVVType *> > > __cdecl cl
ang::RISCV::RVVType::computeTypes(enum clang::RISCV::BasicType,int,unsigned int,class llvm::ArrayRef<struct clang::RIS
CV::PrototypeDescriptor>)" (?computeTypes@RVVType@RISCV@clang@@SA?AV?$Optional@V?$vector@PEAVRVVType@RISCV@clang@@V?$a
llocator@PEAVRVVType@RISCV@clang@@@std@@@std@@@llvm@@W4BasicType@23@HIV?$ArrayRef@UPrototypeDescriptor@RISCV@clang@@@5
@@Z) referenced in function "private: void __cdecl `anonymous …
```

Add clangSupport as dependency to fix linker error

---

.github/workflows/analysis.yml
.github/workflows/ci.yml
.github/workflows/scorecards.yml

Changes:
* Scorecards and analysis -- allow new submissions to cancel running old jobs
* Scorecard only runs on main repo, no need to run on forks
* Nightly CI only runs on main repo, no need to run on forks

CI: Adjust when jobs are run to cut needless CI

---

src/include/OSL/oslconfig.h.in
src/liboslexec/builtindecl.h
src/liboslexec/builtindecl_wide_xmacro.h
src/liboslexec/context.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_ops.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/opmessage.cpp
src/liboslexec/optexture.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/pointcloud.cpp
src/liboslexec/shadingsys.cpp
src/liboslexec/wide/wide_opmatrix.cpp
src/liboslexec/wide/wide_opmessage.cpp
src/liboslexec/wide/wide_oppointcloud.cpp
src/liboslexec/wide/wide_opspline.cpp
src/liboslexec/wide/wide_opstring.cpp
src/liboslexec/wide/wide_shadingsys.cpp
src/testrender/cuda/rend_lib.cu
testsuite/example-cuda/rend_lib.cu

Reminder: phase 1 changed the RendererServices APIs to be based completely on ustringhash for public method calls, not ustring.
This PR starts along the path of phase 2.
In oslconfig.h, I define a new type `ustringrep` which is the in-memory/in-shader CPU-side representation of a ustring. Currently, it's still equivalent to a ustring.
I also define a type called `ustring_pod`, which is the "plain old data" representation inside a ustringrep (i.e., a const char* when it's a ustring, and a uint64_t when it's a ustringhash). For reasons not important, it's exceedingly hard to pass a true ustring/ustringhash as parameters to or from LLVM-jitted code without running afoul of LLVM's type checking, so it's just easier to pass the underlying data type.
So the main work of phase 2 is to change …

Checkpoint to phase 2 of the great ustringhash conversion

---

src/build-scripts/gh-installdeps.bash

Lately, it has been experiencing intermittent availability problems that causes our CI to fail while setting up dependencies.
What happens if we don't use the problematic ubuntu-toolchain-r at all?
Nothing, it seems. So eliminate it.
I think that once upon a time, it was necessary to add this repo to get certain new packages? But maybe they are mainstream enough now that it's not necessary to add this repo? In any case, it doesn't seem to hurt anything, it's one less moving part that can't fail if it's not there.

CI: No longer add the ppa:ubuntu-toolchain-r/test repository

---

src/cmake/testing.cmake
src/liboslexec/batched_analysis.cpp
src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/batched_llvm_instance.cpp
testsuite/closure-zero/a.osl
testsuite/closure-zero/b.osl
testsuite/closure-zero/ref/out.txt
testsuite/closure-zero/run.py

This is another fix I'm attempting without really understanding all this LLVM stuff.
I started by adding a simple test case that attempts to add two closure parameters, where one has not been set.  This crashes or returns random values from uninitialized memory, matching a problem I ran into while trying to get batched mode working in Gaffer.
I investigated some, and found that add_closure_closure is assuming closure pointers are stored with the width of the current batch, but build_llvm_init is creating uniform closures.  I checked with @sfriedmapixar, who confirmed that all the batched closure code is assuming wide closures, so it seems build_llvm_init is what needs fixing.
Adding a `sym.make_varying();` to build_llvm_init appears to fix the problem ... I really don't know enough about …

Fix Batched Mode Crash When Adding A Default Initialized Closure

---

CMakeLists.txt

Related to https://github.com/OpenImageIO/oiio/pull/3653
Kai Pastor (@dg0yt) points out that the recent change I made both in OIIO and OSL to make the version a cache variable has some unexpected side effects that can lead to unexpeted behavior by inadvertently retaining a version number upon recompiles if the cache itself was not cleared, and this can happen unexpectedly even when the user isn't trying to override the version.
This patch changes the behavior as follows:
You must use the special `-DOSL_VERSION_OVERRIDE=...` to override the version.
* if you do so, you are playing with fire and get what you deserve if you misuse it or change branches and don't remember to clear the cache.
If you do a normal build (without trying to override the version),
* you will get the real version …

CMake: Adjust how version overrides work

---

src/cmake/externalpackages.cmake
src/include/OSL/device_string.h
src/liboslexec/backendllvm.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/opcolor.cpp
src/liboslexec/oslexec_pvt.h

OSL currently includes the OptiX header in several places, but without actually making any use of its contents. OptiX support is implemented soly using LLVM and its NVPTX backend, without any types or functions used from the OptiX SDK, making these includes superfluous. The only part of the codebase that does need them are the tests, so this patch makes finding the SDK dependent on whether tests are enabled or not.
Avoiding including the OptiX headers in the core makes it possible still to build OSL with OptiX support (`USE_OPTIX=ON;OSL_BUILD_TESTS=OFF;`), but without needing the OptiX SDK in the process, simplifying the build process on build systems where having the OptiX SDK installed is a challenge.
Additionally this patch also makes it possible to use OSL in OptiX without pre-built …

Remove dependency on OptiX SDK for building core OSL with OptiX support

---

.github/workflows/ci.yml

To save build time, we had OSL's Mac CI tests use the homebrew installation of openimageio. But... Homebrew recently switched its default python to 3.11, which didn't match the versions we're testing OSL against here and broke the python bindings, so need to make a few adjustments so it builds OIIO from scratch against the same python dependencies that OSL is using in these tests.

CI: Fix Mac CI breakage

---

.github/workflows/ci.yml
src/build-scripts/gh-installdeps.bash

It seems something in the latest builds of the aswftesting/ci-osl:2022 containers has changed, and explicitly running /usr/bin/yum (instead of the broken /usr/local/bin/yum) fixes it for now. This was completely breaking the icc & icx tests, which require yum to install the Intel compilers.
Also, bump up to the -clang14 containers for those tests, just to get to a more recent LLVM.

Temp workaround for botched aswftesting container yum

---

src/liboslcomp/osllex.l
src/liboslexec/osolex.l

We used to need to set the global locale before calling something that used OIIO parsing functions.  This is no longer the case ( as of OIIO-1.9, and we now require 2.3 ), so we can now remove these calls.
It came up for me because this code seems to interact strangely with locale in Python - I think this is because something synchs the C++ locale across to Python, but if locale::global hasn't been called in C++ yet, and the locale has only been set in Python, oldlocale doesn't get set to the Python locale ... I could try to figure out more of what's going on, but the simple answer is just to remove this code that is no longer needed.  LG though it was reasonable when I asked on the dev list: https://lists.aswf.io/g/osl-dev/message/5081
A potential follow-up would be to move the …

Remove unnecessary setting of locale::global

---

src/include/OSL/oslnoise.h
src/include/OSL/platform.h
src/include/OSL/wide.h
src/liboslexec/wide/wide_ophash.cpp

Ported from OIIO. This lets us not have to depend on the specific definition in OIIO's fmath.h, and in particular not worry about whether it's a new enough version of OIIO that the old bit_cast is now marked as deprecated.

platform.h: fully define bitcast template

---

src/cmake/testing.cmake
src/liboslexec/batched_llvm_gen.cpp
testsuite/closure-conditional/ref/out.txt
testsuite/closure-conditional/run.py
testsuite/closure-conditional/test.osl

I might need some help again to actually fix this one.
I've added a test where Ci is set to an emission closure with a varying weight on one side of a conditional, and a uniform weight on the other.  In batched execution with optimization on, this results in corrupted closure pointers.
I've tracked the trigger down to the final case in RuntimeOptimizer::peephole2, which converts from a closure multiplied to a weight to a closure-with-scale constructor.  If I comment out this one optimization, the tests pass, but I don't think the bug is in this function ... as far as I can tell, this optimization is the only way to call the closure-with-scale constructor, so the optimization is probably fine, but something else is failing to handle the closure-with-scale constructor - or the resulting …

Batched Mode : Issue with Conditional Assignment of Closure With Varying Weight

---

src/include/osl_pvt.h
src/liboslexec/instance.cpp
src/liboslexec/shadingsys.cpp
src/liboslexec/typespec.cpp

Signed-off-by: Clifford Stein <cstein@imageworks.com>
Allows ShadingSystem->ReParameter() to use the same relaxed rules as SS->Parameter()
no changes in tests

adding relaxed type-equivalency to ReParameter()

---

src/testrender/optixraytracer.cpp
src/testshade/optixgridrender.cpp

Signed-off-by: Peter Ellerington <elleringtonp@gmail.com>
When building OSL my compiler (GCC 11.3 on Ubuntu) was complaining about these snprintfs format strings not being a string literal.
Writing them to a "%s" seems to satisfy it and should produce the same result.
no changes in tests

Changed snprintf formatting to satisfy some compilers.

---

src/cmake/externalpackages.cmake
src/liboslexec/opcolor_impl.h

This PR fixes a couple of build failures when building `USE_OPTIX=true` on windows. Firstly, I added some search paths to correctly find the CUDA toolkit libs on windows. Secondly, this align on the array, doesn't seem to compile on windows, which is weird.
```
OSL_CONSTANT_DATA const float cie_colour_match[81 * 3] OSL_ALIGNAS(64) =
```
I get the following error when generating `opcolor_cuda.bc`
```
src/liboslexec/opcolor_impl.h(51,54): error G9BCB7FFB: 'alignas' attribute cannot be applied to types
```
Therefore, I have just ifdef'ed out the align when compiling for GPU. Correct me if I am wrong, but as I understand it the align is not really important for GPU anyway and is mainly for SIMD access on the CPU?

Fix some windows GPU build errors

---

src/include/OSL/oslexec.h
src/liboslexec/shadingsys.cpp

Signed-off-by: Chris Hellmuth <chellmuth@gmail.com>
Adds the `llvm_groupdata_size` attribute so the renderer can inspect a shader group's GroupData struct size. On GPU this lets us reserve memory more efficiently.
No changes.

Expose llvm groupdata size as a shadergroup attribute

---

CMakeLists.txt
src/include/OSL/rendererservices.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/rendservices.cpp
src/testrender/optixraytracer.cpp
src/testrender/optixraytracer.h
src/testshade/optixgridrender.cpp
src/testshade/optixgridrender.h
testsuite/example-cuda/cuda_grid_renderer.cpp
testsuite/example-cuda/cuda_grid_renderer.h

This makes some minor changes to the RS APIs to add an additional optional parameter to get_texture_handle so it takes a `TextureOpt*` to accommodate a similar change on the OIIO TextureSystem side from https://github.com/OpenImageIO/oiio/pull/3761
The purpose here is to add color management options to texture calls. However, please note that this PR only reserves a public API change we know we'll want, but it does not fully implement the color management. Further work will be needed, as follows:
* Current calls to RS::get_texture_handle should be updated to pass the TextureOpt*. (This is a formality for future-proofing in case future TS or alternate TS implementations want to bake the color space choice into the texture handle itself. But the OIIO change doesn't currently rely on that at …

RendererServices API for letting get_texture_handle consider colorspace

---

src/cmake/modules/FindLLVM.cmake

Make sure LLVM_ROOT/bin (either as a cmake var or as an env var) end up in the hints list when searching for llvm-config.
Without this, one of our Mac CI jobs was ending up with clang 14 and llvm 15, and that was causing problems. The particular test was supposed to be using 14 for both.

ci: Fix broken Mac CI

---

src/liboslexec/shadingsys.cpp

We were getting an exception thrown on the OCIO side, because we were passing 0 for the y stride (which, us humans know, should have been fine since there was only one row, so the stride shouldn't have mattered). Now pass the right stride even though we don't need to step from row to row.

Fix mismatched strides when calling OCIO for transformc with derivs

---

src/testrender/simpleraytracer.cpp
src/testrender/simpleraytracer.h

This lets users customize the behavior of the background for camera rays (requested by the MaterialX team). Without this, you always get the cached copy which is only valid for one raytype (and has limited resolution) or you don't get any importance sampling of the environment.

testrender: Don't use the cached background map on the first bounce

---

src/liboslcomp/ast.cpp

We had turned it off in one function to preserve formatting, but failed to turn it on at the end of the function. This led to several small functions not being clang-formatted, now fixed.

style: Fix missing `// clang-format on` in oslc.c

---

.github/workflows/ci.yml
INSTALL.md

* Stop using the deprecated, soon to be removed, ubuntu-18.04 runners and switch to 20.04.
* Bump the "latest" test openexr to 3.1.6
* Update INSTALL.md to document some things we're already testing and are known to work.

ci: update runners

---

src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp

In particular, 1 prints a short version of the compile report (just the fact that it happened and the time), >1 prints more verbose info.

Make compile_report attribute an int instead of just 0/1

---

src/cmake/modules/FindLLVM.cmake

In particular, `${LLVM_ROOT}/bin` will end up being (incorrectly!) `/bin` if LLVM_ROOT is empty. That is bad if some other llvm-config happens to be in /bin.

Be more careful about paths to look for llvm

---

src/liboslexec/llvm_instance.cpp

Enable userdata derivatives for interpolated parameters on the GPU.
When generating calls to `osl_bind_interpolated_param` in llvm_instance.cpp, the `userdata_has_derivs` field is set to true if the parameter's derivatives are needed, but the code does not take into account that on gpu there is no space allocated for these derivatives.
This leads to an incorrect derivatives pointer getting passed into the renderer, which the renderer will use to write into unrelated groupdata fields.
For our renders, getting the correct image was worth the 1-2% inflation of groupdata struct size that we observed by simply re-enabling gpu userdata derivatives. If desired, adding an option to turn them on/off is straightforward, but I didn't want to preemptively bloat the code if it's not necessary.

Enable userdata derivatives for interpolated params on GPU

---

INSTALL.md
src/cmake/externalpackages.cmake

LLVM 16 was just released. I'm pretty sure we won't build properly against it because of the phase-out of typed pointers in LLVM IR, so warn prominently so that anybody building against it who has problems will know why.
Also, LLVM itself has bumped their toolchain requirements with the release of 16. Technically, I'm not sure if that extends to projects using the LLVM APIs, but warn anyway and hope for the best. If it fails, at least the warning will supply an explanation.
At a later time, we'll need to upgrade the code on our side to have the option of using opaque pointers so we can run with LLVM 16+.

build: proper warnings about LLVM 16

---

src/cmake/cuda_macros.cmake

For LLVM 15+, we need to disable opaque pointers. We did this for regular bitcode generation in llvm_macros.cmake, but neglected to make the corresponding change for compiling to ptx in cuda_macros.cmake.

Build: Fix cuda compilation flags for LLVM 15

---

sonar-project.properties

No need to configure the cache anymore, SonarCloud now has an automatic analysis caching. See https://docs.sonarcloud.io/advanced-setup/languages/c-c-objective-c/#analysis-cache.

Remove SonarCloud cache setup as it is now offered by default

---

INSTALL.md
site/spi/Makefile-bits
src/build-scripts/build_llvm.bash

But note: OSL does not yet work with LLVM 16.
Because homebrew recently upgraded its default llvm to 16.0, there may be users for whom builds now break. The solution is:
brew install llvm@14
cmake ... -DLLVM_ROOT=/usr/local/opt/llvm@14

Build: verify that OSL can build with clang16

---

src/liboslexec/backendllvm.h
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

This patch is a very simple part one of work to optimize the number of conditional run layer calls that OSL makes, which take the form:
```
if (!groupdata->run[parentlayer])
parent_layer([...]);
```
After examining our slowest JIT’ing shaders on gpu, @tgrant-nv showed us that these run layer calls were significantly bloating our ptx and slowing down their compilation. Many of them are unnecessary because static analysis can show we are guaranteed to have already run the layer in question.
For example, reading different fields from a connected struct like below will often generate multiple conditional run layer calls:
```
struct Pair {
float x;
float y;
};
shader example_shader(Pair p = {})
{
if ([…]) {
float xx = p.x;
float yy = p.y;
[…]
}
}
```
Since this is not really a performance …

Don't insert redundant run layer calls inside a basic block

---

src/include/OSL/oslexec.h
src/include/osl_pvt.h
src/liboslcomp/symtab.cpp
src/liboslexec/instance.cpp
src/liboslexec/loadshader.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
src/osl.imageio/oslinput.cpp
src/testrender/testrender.cpp
src/testshade/testshade.cpp
testsuite/layers-entry/run.py
testsuite/testshade-expr/ref/out.txt

Establish two new metadata hints about shader parameters:
- "interpolated" means that the parameter comes from the geometry somehow and may be bound with a different value at different points on the surfaces, or different values for different primitives that share the material. This corresponds to concepts known variously as "geometric primitive data/variables", "user data", or "vertex variables", depending on the renderer.
- "interactive" means that the user desires the parameter to be allowed to change when the scene is interactively rerendered, without incurring a full recompile of the shader. (Variables not so marked might still be capable of being changed, but not necessarily without a re-JIT of the shaders.)
Both of these require that the parameter not be fully constant-folded or …

Switch lockgeom to interpolated and interactive

---

src/liboslexec/instance.cpp

This proposed patch fixes a corner case we were seeing during live rendering with ReParameterization.
We were experiencing a problem when `ss->ReParameterize()` wasn't successfully applying parameter changes for us.
In our situation, a shader's parameter, "A",  was marked with lockgeom=0 (ie. "live" or "editable") and was set via `ss->Parameter()`.  This parameter was connected (through a series of copies and network links) to another shader's parameter, "B", downstream whose initialized value (ie. the one specified in the .osl/.oso file) matched A's set value.  When this happened, A's shading layer was getting marked as "mergeable" and deleted, and we wouldn't see any updates to A via "reparameterization" take effect.
We are using  v3.13.2.3 locally and a similar fix (with …

fix for ReParameterization corner case

---

src/liboslexec/backendllvm.h
src/liboslexec/batched_backendllvm.h
src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

My initial implementation of the run layer check optimizations didn’t account for the fact that init ops for symbols have their llvm code generated before we build basic blocks from the OSL IR.
This caused the code to be wrong in two ways: 1) the set of known run layer calls was being reset between instances too late in the pipeline, so a useparam inside an init op would actually be checking the previously compiled layer’s set, and 2) even when reset earlier, it assumed valid basic block ids existed for the init ops when they did not.
So, if a layer had a useparam inside one of its init ops that generally matched the same code location as a useparam in the previously compiled layer, the run layer check could be incorrectly omitted.
I’ve updated the code so that the default optimization …

Make recent run-layer optimizations optional, and fix init ops-related false positive

---

src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

This includes two fixes:
1) When registering symbols that need user data, sort the entries in
the set so the layer number is ignored. A needed udata iteam shouldn't
depend on the layer and separating them makes find_userdata_index()
sometimes find an index with different derivs status.
2) osl_bind_interpolated_param() is memcpy'ing derivs that might not
be there, yielding corrupted derivs and possibly a crash.

Fix userdata binding corner case

---

src/cmake/pythonutils.cmake

This issue was caused by https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/commit/5efe15a79eb2d29a0f526f4c7e43c6f483b39d15. Essentially, we now use `Python_EXECUTABLE` to execute the `serialize-bc.py` script. Therefore, we have to run `find_package(python)` so that the `Python_EXECUTABLE` variable gets setup.

Fix builds when USE_PYTHON=OFF

---

src/liboslcomp/oslcomp.cpp

This issue was caused by https://github.com/AcademySoftwareFoundation/OpenShadingLanguage/commit/8c52d48965db74f56daa59c4a668b34daf32b220 . The problem is that the constant float values are being turned into ints. The PR restores the previous behavior and preserves the float format.

Fix constant float values being converted to ints

---

src/doc/languagespec.pdf
src/doc/languagespec.tex

Improve the documentation of optional parameters of `trace` to more accurately describe behavior.
N/A
- [N/A] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).

Docs: Improve documentation of `trace` function

---

src/cmake/compiler.cmake
src/liboslexec/opcolor.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/pointcloud.h

As Fabrice Macagno pointed out on the oiio-dev mail list, we weren't setting the correct variable name CMAKE_CXX_VISIBILITY_PRESET.
And, oops, this also revealed that there were some things that needed to be declared public that were not (because, specifically, they needed to be called across library boundaries by the per-ISA dynamic libraries used by batch shading!).

build(cmake): Fix incorrect variable name to control symbol visibility

---

CMakeLists.txt
src/include/OSL/oslnoise.h
src/liboslexec/optexture.cpp
src/liboslexec/wide/wide_optexture.cpp

Oops, I noticed that OSL was still using deprecated OIIO::simd type aliases (float4, int4, bool4) instead of the modern vfloat4, vint4, vbool4.

cleanup: switch deprecated oiio simd names to modern

---

src/liboslexec/llvm_instance.cpp

Following #1657, it turns out we forgot to zero initialize the userdata derivatives for the optix path. 
This leads to some rendering glitches caused by the memory garbage left in those derivatives.

Fix userdata derivatives for interpolated params on GPU

---

src/build-scripts/gh-installdeps.bash

The Intel yum repo renamed this package a couple weeks ago, and it broke our CI. Update to the new name.

ci: Fix package name for icc

---

README.md

Updated README.md to include LAIKA films and added Siggraph OSL course info to Documentation.
- [x ] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [x ] I have updated the documentation, if applicable.
- [x ] My code follows the prevailing code style of this project.

README.md: added filmography and Siggraph OSL course info.

---

src/liboslexec/instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

Sometimes, after optimization, symbols tagged as interactive get removed because they are unused. But ReParameter is failing with errors because it goes looking for the removed symbol to master, which is, of course, not interactive. This patch avoids that so the symbol is not found, and then we just return false.
We found this issue in production because code was being removed, then symbols too, then reparameter failed. 
There is no other way to prevent the error than from inside OSL. I'm suggesting this change but any other way to
handle it would work for us.

Don't try to ReParameter symbols not in the group

---

src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

For GPU in particular, this prevents needless transfers to the device when no values actually change.
Also, keep track of some statistics about how much ReParameter is being used. (Which also helps to verify that this change works as intended.)

fix: Have ReParameter only copy data when it changes

---

.github/workflows/ci.yml
src/cmake/compiler.cmake
src/liboslcomp/oslgram.y
src/liboslexec/osogram.y

Also add a MacOS 13 test to the CI matrix.

build: Fix for Apple clang 14+ warnings

---

.github/workflows/ci.yml

OIIO's 2.3 family is obsolete and no longer updating, so we removed the branch marker. (Branch markers should always indicate places where development may happen.)
But we sill reference that branch namd in a couple places for OSL's CI, so just replace it with the immutable tag of the last release in the 2.3 family.

ci: Switch OIIO dev-2.3 branch to using v2.3.21.0 tag

---

src/liboslexec/runtimeoptimize.cpp

Sometimes an interactive param is used in a way that gets flagged as needing derivs. But we were neither allocating space for that nor zeroing them. This resulted on memory corruption.
This fixes incorrect renders in a production context where params are often tagged as needing derivs.

Zero derivs for interactive params when needed

---

src/liboslexec/CMakeLists.txt

Like other oslcomp source files that are duplicated in oslexec, this duplication should only be done for shared library builds where the symbols are hidden from each other.
Not applicable.

Fix duplicate osl lexing symbols when building as static libraries

---

src/liboslexec/builtindecl.h
src/liboslexec/opstring.cpp

The recently merged PR 1702 fails all the OptiX tests. I tracked down the problem and it's that the patch was a bit too aggressive about removing things no longer needed. The intent was that even if you don't use the new journaling, nothing should break. But it does break for OptiX, and this patch restores some of the functions 1702 removed (like the implementation of osl_printf) and some other necessary stubs.
This takes us from failing all ~150 OptiX oriented tests to failing only 4, which I believe are unrelated to 1702 and are merely revealed by them. I will fix those in a separate PR.

Restore stubs for printf (fixes OptiX problems with 1702)

---

.github/workflows/ci.yml
src/build-scripts/build_llvm.bash

* Remove leftover logic from when we used TravisCI.
* Pick a default for LLVM_DISTRO_NAME so it works when the script is run standalone when not on GitHub Actions CI.
* Switch the logic about file location to enumerate only the couple of old versions that uses the old download location, rather than trying to enumerate an ever-growing set of modern releases that use the current download location.
* Comment o say that when LLVM 10+ is the floor, the old case can go away entirely.
Also bump the CI "bleeding edge" test to use LLVM 15.0.6.

ci: Simplify build_llvm.bash script

---

src/build-scripts/gh-installdeps.bash

Intel's servers have again updated the default icx that you get when you install from their yum repository, and the new one seems incompatible with our libstdc++ toolchain. So lock down on 2023.1.0 for now so that our CI can pass.
This is copied from a similar fix in OIIO.
Actually, it turns out that OSL had previously locked down to 2022.1, but that was only for the sake of icc; icx could have been newer all along (and was in OIIO's CI). So really, we are bumping icx *forward* for OSL's CI testing... but not all the way forward, only to the most recent version that still runs properly on our CI runners.

ci: Lock down icx version

---

.github/workflows/ci.yml
src/liboslcomp/ast.cpp
src/liboslexec/journal.cpp

Certain fmt library versions don't automatically know how to format atomics. Explicitly load them to turn into regular ints to avoid new build errors introduced by the recent journaling changes.

fix: Recent journaling changes break with some fmtlib versions

---

src/include/OSL/llvm_util.h
src/liboslexec/backendllvm.cpp
src/liboslexec/llvm_util.cpp

The string situation is still a bit tricky on the OptiX side.  There's a full overhaul of that coming separately as we continue to shift to an all-ustringhash world.
But in the mean time, we were getting some testsuite failures that were because of a mismatch between times we think of a gpu-side ustring as a char* and when it's a uint64. IN FACT, they are always the hashes, but we backed ourselves into a corner where sometimes that 64 bit pattern is passed around as a pointer, ugh.
This small patch attempts to catch this case and just do the appropriate cast to compensate. It's a band-aid; a more comprehensive fix is coming, as I said.
This gets us down to just ONE failing optix test case, which I will tackle separately.
The change necessitated adding a new `ptr_to_int64_cast()` method to …

fix: Handle mixed string casting that plagues optix codegen

---

src/testrender/cuda/rend_lib.h

There is a separate definition of `ShaderGlobals` in `testrender/cuda/rend_lib.h` that has drifted away from the definition in `include/OSL/shaderglobals.h`. Two new members were added in #1702 which changed the byte offset of the output closure `Ci`, which leads to incorrect shader output since the offset is baked into the PTX.
Adding the new members fixes the shading issue. But this should be regarded as a short-term fix, since the two `ShaderGlobals` definitions have diverged in other ways that might be significant.
All OptiX tests passing with the exception of `testoptix.optix.opt`, which is a preexisting failure.

Add missing members to ShaderGlobals in rend_lib.h

---

.github/workflows/ci.yml
src/build-scripts/gh-installdeps.bash

This test was pulling OIIO master, which had recently been upgraded to require newer cmake and openexr versions than were provided in the 2019 era container we were using for the GPU test. Upgrade the test to modern 2023 standards.

ci: Fix broken CI from new OIIO that needs newer cmake and openexr

---

.github/workflows/ci.yml
CHANGES.md
INSTALL.md
src/cmake/externalpackages.cmake
src/cmake/testing.cmake
src/include/OSL/batched_texture.h
src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/batched_llvm_instance.cpp
src/liboslexec/rendservices.cpp
src/liboslexec/shadeimage.cpp
src/liboslexec/wide/wide_optexture.cpp

This is just for future-looking OSL 1.13 releases, it won't be backported to the 1.12 release branch.
Remember that by the time we release OSL 1.13 as a supported release family, OIIO will also have done its annual release, of 2.5. So our minimum of OIIO 2.4 means that we will be supporting the current release, as well as the prior year's release (and, of course, we always stay compatible with OIIO's trunk as it evolves). So we're really keeping compatibility with 3 major releases, which seems like plenty to juggle.
We discussed doing this a few TSC meetings ago, and nobody raised any objections to our raising the OIIO floor to 2.4 for the upcoming OSL 1.13 release. But if anyone is bothered by this, please speak up on this PR.

build(deps): Raise minimum OpenImageIO version to 2.4

---

doc/app_integration/OptiX-Inlining-Options.md
src/build-scripts/analyze-ptx.py
src/build-scripts/process-ptx.py
src/cmake/cuda_macros.cmake
src/include/OSL/llvm_util.h
src/include/OSL/oslexec.h
src/liboslexec/CMakeLists.txt
src/liboslexec/backendllvm.h
src/liboslexec/builtindecl.h
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_ops.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
src/testrender/CMakeLists.txt
src/testrender/cuda/optix_raytracer.cu
src/testrender/cuda/rend_lib.cu
src/testrender/optixraytracer.cpp
src/testrender/testrender.cpp
src/testshade/CMakeLists.txt
src/testshade/cuda/optix_grid_renderer.cu
src/testshade/optixgridrender.cpp
src/testshade/optixgridrender.h
src/testshade/testshade.cpp

This PR is an overhaul of PTX compilation in OSL. The goal is to minimize the size of the generated PTX to help reduce time spent in subsequent stages (e.g., module creation, pipeline linking, etc.).
The main functional change is in how the functions defined in rend_lib.cu are handled. In the current setup, rend_lib.cu is compiled to a standalone PTX file using nvcc. The functions are considered `extern` in generated shaders, and the dependencies are satisfied when the final pipeline is linked together. Since the functions are `extern`, they are not available for optimization when each shader is generated. This prevents the inlining of small functions, which incurs a lot of function call overhead in terms of PTX size and run-time cost.
So instead of compiling rend_lib.cu separately, it is …

OptiX PTX pipeline overhaul

---

src/cmake/testing.cmake
src/include/OSL/oslexec.h
src/liboslexec/backendllvm.cpp
src/liboslexec/backendllvm.h
src/liboslexec/batched_backendllvm.cpp
src/liboslexec/batched_backendllvm.h
src/liboslexec/batched_llvm_instance.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
src/testshade/testshade.cpp
testsuite/groupdata-opt/connected_output.osl
testsuite/groupdata-opt/input.osl
testsuite/groupdata-opt/main.osl
testsuite/groupdata-opt/ref/out-batched.txt
testsuite/groupdata-opt/ref/out.txt
testsuite/groupdata-opt/run.py

On SPI Arnold, we are seeing GroupData as a bottleneck for GPU performance. Regardless of whether the buffer is backed by local or global memory, it's off-chip and slow to access.
This change moves qualifying parameters out of the GroupData struct and onto the stack. On GPU this makes those parameters more likely to be stored in registers, leading to better performance.
The qualifying parameters are all the output parameters minus three exceptions.
A typical output parameter's lifetime is scoped to the execution of the instance it is associated with. The parameter is initialized at the beginning of instance execution, accessed during the body of the instance, and after the instance body its final state is broadcast to all its downstream connections. This lifetime makes output parameters a …

Move qualifying GroupData params onto stack

---

CMakeLists.txt
src/include/OSL/rendererservices.h
src/liboslexec/rendservices.cpp
src/testrender/optixraytracer.cpp
src/testrender/optixraytracer.h
src/testshade/optixgridrender.cpp
src/testshade/optixgridrender.h
testsuite/example-cuda/cuda_grid_renderer.cpp
testsuite/example-cuda/cuda_grid_renderer.h

We were overzealous in switching everything to ustringhash.  The filename argument to get_texture_handle should allow taking a ustring.

Change RendererServices::get_texture_handle back to ustring

---

src/liboslexec/rendservices.cpp

The unconditional dereferencing of the sg pointer is only necessary if texture_thread_info is not supplied. And for that matter, the texture_thread_info is only necessary if the texture_handle is not supplied.
So rearranging the nesting skips a bunch of the work, and the need for the caller to supply the sg if they have the texture_thread_info, nor for them to need texture_thread_info if they already have the handle.

RS::get_texture_info make robust to empty shaderglobals param

---

src/cmake/cuda_macros.cmake
src/cmake/externalpackages.cmake
src/cmake/llvm_macros.cmake
src/include/OSL/llvm_util.h
src/liboslexec/backendllvm.cpp
src/liboslexec/batched_analysis.cpp
src/liboslexec/batched_backendllvm.cpp
src/liboslexec/batched_backendllvm.h
src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/batched_llvm_instance.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/llvmutil_test.cpp

New LLVM versions require opaque pointers, that is you can no longer tell from a pointer value which data type it points to.
* Remove deprecated `GEP` and `op_load` methods without type, and refactor code to always pass the type.
* Add element type argument to `op_scatter` and `op_gather`.
* Eliminate pointer type comparisons which no longer work with opaque pointers.
* Some useful asserts to verify correct pointer types must unfortunately be disabled with opaque pointers.
* Keep interactive params marked as uniform in batched analysis, so we can deduce uniform/varying correctly from just the symbol.
* Enable opaque pointers on LLVM 16+.
OptiX opaque pointers might not be working yet due to the conversion in`BackendLLVM::llvm_store_value` between `int64` and `char*`, where we can no …

LLVM opaque pointers support

---

src/build-scripts/ci-startup.bash
src/build-scripts/nosanitize.txt
src/testrender/testrender.cpp
testsuite/runtest.py

37cbab5b accidentally changed tests to accept failing commands by default.
This can cause tests to pass even though the program crashed, when a previous run created the correct output file.
This reveals existing asan and lsan errors. The asan error was fixed. The memory leaks remain ignored, as the exact cause is unclear.
N/A

Fix tests passing when test commands fail

---

.github/workflows/ci.yml
src/cmake/cuda_macros.cmake

In #1668 USE_OPTIX changed to OSL_USE_OPTIX, but CI was not updated.
And fix CPU SIMD flags being used for CUDA compilation, making the build fail.
N/A

ci: Fix GPU job not actually enabling OptiX

---

testsuite/runtest.py

Use the absolute path to the Python executable to avoid picking up a different executable with the same version.
N/A

ci: Fix python-oslquery test failure on macOS

---

INSTALL.md
src/cmake/externalpackages.cmake

Based on Brecht's tests, we realize that OSL doesn't work at all with Cuda 8.0 (which didn't support the C++14 that we use), so we're raising the minimum to 9.0. And there are some flaky tests with 9 and 10, so we're making the recommended minimum be 11.0.
It's not our policy to change the minimum versions of dependencies on release branches, but I think we should backport this to the release branch. I believe what this change is doing is not removing actual support for old versions, but rather, correctly documenting what has been working (or not) for quite some time.

build: Bump Cuda minimum to 9.0

---

.github/workflows/release-notice.yml

Add a GHA workflow that is triggered up on drafting a release, which will echo a notice to the ASWF slack #release-announcements channel.

admin: Alert slack "release-announcements" channel upon OSL release

---

.github/PULL_REQUEST_TEMPLATE.md

It gave a VERY old link to the SPI CLA, which we no longer use.  In fact, because we have CLA enforcement through the CLA bot, there is not really a need to have it in the checklist... nobody can forget.

admin: Update pull request template

---

.github/workflows/ci.yml

The MacOS 11 CI seems to be broken on GitHub's runners. I'm not sure why, but since it's old and getting various deprecation warnings from Homebrew and GH, I'm inclined to just disable it rather than work hard to keep this old version of the OS running.

ci: Disable MacOS-11 CI

---

src/liboslexec/oslexec_pvt.h

Stephen Friedman alerted me to the fact that on Windows, bit fields within a struct will only be combined if they are the same type.  We were a bit sloppy in the defintion of SymOverrideInfo, and that was causing the struct to end up a different size in Windows.  I think the solution is that all those bit fields should be `unsigned int`.

fix: SymOverrideInfo bitfields should be the same type

---

.github/workflows/ci.yml
src/build-scripts/gh-installdeps.bash
src/include/OSL/oslconfig.h.in
src/liboslexec/oslexec_pvt.h
src/testrender/optix_stringtable.h
src/testrender/optixraytracer.h
src/testshade/optixgridrender.h
testsuite/example-cuda/cuda_grid_renderer.h
testsuite/example-cuda/cuda_string_table.h

The newly released OIIO 2.5 (and changes in master) adjusts a few of its minimum dependencies (cmake, openexr, fmt) in ways that break some of our CI test cases for OSL 1.12, and also deprecated a helper method called ustringHash that OSL referenced in a few places.
These have already been addressed in the OSL main branch (what will soon be OSL 1.13), and in some cases OSL-next has also bumped some of the very same dependencies.
But this PR is dealing with the 1.12 branch, in which we cannot raise minimum dependencies that OSL requires. So here we are only adjusting which versions of those dependencies we are using or building for the specific tests in our CI matrix that use the sufficiently new OIIO that it needs the updated changes.

build: Fixes to build and test against OpenImageIO 2.5

---

src/testrender/shading.cpp

Fix a typo in the MxSheen builtin closure parameter for testrender.
I think this bug could read or write outside the intended struct memory when a MxSheen closure is used but I haven't tried to provoke this for a test.
already run clang-format before submitting, I definitely will look at the CI
test that runs clang-format and fix anything that it highlights as being
nonconforming.
All tests passed except `osl-imageio*`. But they failed on main branch as well for me so I think I'm doing something wrong. I don't think they are relevant to this fix.
```
99% tests passed, 3 tests failed out of 623
Label Time Summary:
batchregression    =  35.15 sec*proc (3 tests)
noise              =  34.52 sec*proc (48 tests)
render             =  96.00 sec*proc (22 tests)
texture            =  26.50 …
```

testrender: Fix wrong offset of MxSheen param

---

.github/workflows/ci.yml
CMakeLists.txt
src/build-scripts/build_abi_tools.bash
src/build-scripts/ci-abicheck.bash
src/build-scripts/gh-installdeps.bash
src/liboslexec/CMakeLists.txt
src/liboslnoise/CMakeLists.txt

This patch adds a new test to the CI matrix: verifying that we do not break the ABI during releases. This is based on similar work done a couple months ago in OpenImageIO.
Basically, in addition to building the current checkout, it also builds a checkout of the designated "ABI standard" (generally, the first non-beta release of a major version), then generates ABI dumps of both versions and runs the ABI compliance checker using the tools from https://github.com/lvc
Making two builds sounds expensive, but both builds are rigged to be minimal, since only the libraries are needed for ABI checks (we can turn off the binary tools, unit tests, python bindings, etc.), and of course the test suite need not run. So actually, it's less expensive than most of the test matrix entries, and it helps …

ci: Test ABI compliance

---

src/include/OSL/fmt_util.h
src/include/OSL/platform.h

This PR fixes a build error due to MSVC not supporting `__attribute__((packed, aligned(1)))` that GCC and Clang use.
I wrote a `static_assert` which checks the sizeof a struct which contains fields `int, char, int` to ensure it is not padded.
I have verified this test fails (on both GCC and MSVC) if the packed attribute/pragma is not present.
already run clang-format before submitting, I definitely will look at the CI
test that runs clang-format and fix anything that it highlights as being
nonconforming.

Fix struct align/pack for MSVC

---

src/testrender/cuda/rend_lib.h

This can come up if, for example, you build an OIIO using a static Imath library that's more recent (3.x) than what you're forced to use for your OSL build (2.4). (Don't ask, you don't want to know.) So OSL needs to see half.h before we include any OIIO headers. But it's the OIIO headers that adjudicated where we get half.h from, so we need to be a little more explicit in, of all places, rend_lib.h of testrender.

build: handle case where OIIO uses a different Imath than OSL

---

.github/workflows/ci.yml
INSTALL.md
src/build-scripts/install_homebrew_deps.bash

Bump the "bleeding edge" test to LLVM 17, the "stable latest releases" test to 16.

ci: test against LLVM 17

---

.clang-format
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
CONTRIBUTING.md
src/include/OSL/device_ptr.h
src/include/OSL/mask.h
src/include/OSL/oslclosure.h
src/include/OSL/rendererservices.h
src/include/OSL/wide.h
src/include/osl_pvt.h
src/liboslexec/batched_analysis.cpp
src/liboslexec/batched_backendllvm.cpp
src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/opcolor_impl.h
src/liboslexec/optexture.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/wide/wide_opdictionary.cpp
src/liboslexec/wide/wide_opspline.cpp
src/liboslexec/wide/wide_optexture.cpp
src/liboslnoise/sfm_gabornoise.h
src/testrender/optixraytracer.cpp
src/testrender/shading.cpp
src/testrender/shading.h
src/testrender/testrender.cpp
src/testshade/testshade.cpp

style: Raise our formatting standard to clang-format 17
We had been using clang-format 14. Bump to 17 as our official
reference standard for formatting.
Moved the clang-format CI test from an aswf container to bare Ubuntu
to make it run faster -- it doesn't need to do a real build, so
there's no point wasting 2 minutes or so downloading a container holding
library dependencies it won't need.
Also fix a duplicate line in .clang-format that newer clang-format
complained about.

style: Raise our formatting standard to clang-format 17

---

src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/llvm_gen.cpp

A recent change in OIIO master made some of the ustring methods "trivial", and somehow that makes this variable warn about being unused, which it did not do before.

fix(build): Remove unused static ustring

---

src/cmake/cuda_macros.cmake
src/liboslexec/llvm_util.cpp

This PR includes fixes for three issues:
1. A leak of the `llvm::TargetMachine` used for NVPTX.
2. ~~A segfault that can occur in `testrender` when the renderer is destroyed before the  `ShadingSystem`.~~
3. A compilation failure when using CUDA Toolkit 12.0 or newer due to references to the long-deprecated (and now removed) `textureReference` API still being present in the LLVM headers.
These changes aren't related, but I've bundled them up for convenience. I can break these into individual PRs if that would be preferable.
No new tests, but all previously passing tests still pass.

Fix NVPTX TargetMachine leak

---

src/cmake/checked_find_package.cmake
src/cmake/externalpackages.cmake

* New build option `CUDA_PREFER_STATIC_LIBS` tries to use Cuda's static libraries if they can be found.
* Remove code related to nvrt library, it's no longer needed in OptiX 7.
* Changes in checked_find_package to allow a PREFER_STATIC_LIBS optional argument. Turns out we didn't use this, but I think it's useful functionality to keep now that I've written it.

build: add options to use static Cuda libraries

---

src/cmake/externalpackages.cmake
src/liboslcomp/oslcomp.cpp
src/liboslexec/llvm_passes.h
src/liboslexec/llvm_util.cpp

Adds primary support for LLVM-18
I couldn't fix all issues because it needs a better understanding of the code.

Initial support for LLVM-18

---

src/doc/languagespec.tex
src/doc/stdlib.md

Pointed out in MaterialX discussions, our spec was not clear what round() should do in cases where the input value is exactly half way between two integers. Our design (and implementation) uses "round away from zero" policy for that case, matching C/C++ standard round(). But we were not clear about it in the docs.

docs: Clarify behavior of round()

---

.github/workflows/ci.yml

We didn't change anything on our end, but in the last few days, I believe the GHA MacOS-13 runners have slowed done somehow, and so now a few test are failing only because they don't complete within the ctest timeout period for "small tests". So this just bumps up the limit on this runner platform to allow the tests to pass.

ci: Increase timeout for slow MacOS-13 runner

---

src/liboslexec/pointcloud.cpp

This patch mutes the error printed to std::err from inside Partio when it fails to read a pointcloud.  OSL's pointcloud_search and pointcloud_find already reports errors "the proper way" via errorfmt, so a failed read will still thrown an error. Plain prints like this can sneak past log-limiting filtering  and result in very large log files.
Currently, running something like
shader partioerror(){
float test[1];
if(pointcloud_search("non-existing",P,1.0,1,"test",test))
printf("Success");
}
in testshade, will print
Partio: No extension detected in filename
ERROR: pointcloud_search: could not open "non-existing"
with the patch, it will just print
ERROR: pointcloud_search: could not open "non-existing"
I haven't added any tests yet
- [X ] I have read the [contribution …

Mute partio error prints

---

src/liboslexec/runtimeoptimize.cpp
testsuite/globals-needed/printcalculatenormal.osl
testsuite/globals-needed/ref/out.txt
testsuite/globals-needed/run.py

The calculatenormal() shadeop references flipHandedness in order to know which order to cross the derivatives.  This change makes it so flipHandedness shows up in the list of "globals_needed" that can be queried by renderers to lazily fill in.
The globals-needed test was extended to test caclulatenormal() as well

Calculatenormal needs fliphandedness

---

src/liboslexec/llvm_gen.cpp

Prevent complications on the GPU by printing error messages at compile time instead of generating code to print them at runtime when a closure doesn't exist.

Print closure missing error message at compile time instead of run time. 

---

src/liboslexec/optexture.cpp
src/liboslexec/oslexec_pvt.h

We noticed a few ustring-related performance regressions while converting Arnold to the new ustringhash pipeline.
These changes update relevant shadeops to avoid a ustringhash -> ustring conversion. The decode_wrapmode call into OIIO requires the latest master: https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4207/commits/6759d4d85dc6f41f16c56379d18daf4833663913

Use new OIIO ustringhash decode methods when available

---

src/cmake/testing.cmake
src/liboslexec/llvm_instance.cpp
testsuite/userdata-defaults/ref/out.txt
testsuite/userdata-defaults/run.py
testsuite/userdata-defaults/test.osl

Currently, the GPU will crash when initializing non-string interpolated parameters with default values.
It looks like this is a regression from the ustringhash conversion in 12530f115dfc759b00ee4de6dc27bf5fa3f32fe0. I believe that before the phase 3 commit, we had global variables on GPU that we memcpy'd the defaults values from. Now after their removal, we're memcpy'ing from an illegal address.
As a proposed fix I removed the entire memcpy branch of the code and let interpolated parameters fall back to the default code path that stores the values directly. I'm open to instead guarding the removed block with "&& !gpu" making the patch have no effect on cpu, but leaned towards having unified code paths. Still, it's not an area of the code I'm very familiar with, any feedback would be …

Fix GPU interpolated param initialization

---

src/include/OSL/oslquery.h
src/liboslquery/CMakeLists.txt
src/liboslquery/py_osl.h
src/oslinfo/CMakeLists.txt

The (should be) tiny oslquery library was over-including and over-linking beyond its actual needs.
* Remove`#include <OSL/oslconfig.h>`, which is a lot of setup, type definitions, and many transitive header includes.  Instead, just include the very small number of headers and types actually needed by the OSLQuery class definition.
* In particular, this removes includes of OpenEXR/Imath headers and references to Imath types, the OIIO TextureSystem (!), and other big things, from what oslquery.h needs to see.
* liboslquery can link against libOpenImageIO_Util (which it uses primarily for ustring and TypeDesc), it doesn't need the full libOpenImageIO, since it doesn't read or write image files.
* Remove some link references to Boost which isn't actually needed for this library.
* This also …

oslquery: Simplify include and link needs

---

src/liboslexec/runtimeoptimize.cpp
testsuite/isconnected/ref/out.txt
testsuite/isconnected/run.py
testsuite/isconnected/test.osl

The isconnected() returns 2 when used on an output that is connected to another downstream shader node -- this can be used to limit computation to only the outputs used.  However, that misses the important case of where the renderer has declared a shader node output as a renderer output, which happens often when using OSL purely for pattern generation purposes.  This change makes that case also return 2.
The isconnected test has been updated to include testing this functionality.

Make isconnected() work with downstream renderer "connections."

---

src/cmake/cuda_macros.cmake
testsuite/example-cuda/CMakeLists.txt
testsuite/example-cuda/example-cuda.cpp

OIIO recently pushed its master to be C++17 minimum. When using a C++17-minimum OIIO, you need to build OSL with C++17 as well. This broke a couple CI cases for OSL.
There were a few spots where we were hard-coded to C++14 on the OSL side rather than even using the C++ version specified for the OSL build, so these are some fixes here to address this.

build: Propagate cpp version

---

.github/workflows/ci.yml

Background: Intel's icc is essentially discontinued and we think all the renderers using OSL have moved on to the newer icx, but Alex Wells still likes to sometime use icc for its better facilities for some SIMD code generation sleuthing that he does. So we keep it in our CI matrix to esure we don't break it for OSL until it is truly unavoidable or he doesn't feel like he needs it anymore.
Some recent changes to OIIO's simd.h, from PR 4187 in that project, seem to tweak what appears to be a compiler bug in icc -- bugs were also noted in OIIO in the course of this PR and some workarounds were put there just for icc to make OIIO's own tests pass. Well, once that went in, OSL's CI tests for the icc case also started failing.  It's only texture derivatives that are broken, and in a weird wy …

ci: Lock down to OIIO 2.5 for icc tests

---

src/liboslexec/context.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

This had already been marked as deprecated, and there is concensus that the overhead does not outweight the slight inconvenience of creating one object per thread
Testsuite passes on my machine.

Remove the only use of boost::thread_specific_ptr

---

src/build-scripts/build_opencolorio.bash
src/build-scripts/build_openexr.bash
src/build-scripts/build_openimageio.bash
src/build-scripts/build_pugixml.bash
src/build-scripts/build_pybind11.bash

Especially for our "bleeding edge" test that builds from the current master of several dependencies, sometimes our tests fail not because of anything we've done, but because of a change in one of the dependencies.  To help track down exactly which change broke the dependency, make sure our CI build logs print the specific commit hash of those packages that we built.

build: print commit hash of locally built dependencies

---

src/include/OSL/oslconfig.h.in

This is the only way that makes any sense -- define OIIO_HIDE_FORMAT if it ISN'T already defined.

fix: Fix ifdef typo

---

src/include/OSL/dual.h
src/include/OSL/dual_vec.h
src/include/OSL/hashes.h

We've been C++14 minimum for a long time now, we can just say constexpr.
Change a couple of stray OIIO_CONSTEXPR14 occurrences as well.

cleanup: change OSL_CONSTEXPR14 to constexpr

---

src/build-scripts/nosanitize.txt

OSL's CI's sanitizer job has been failing since some recent changes in OIIO that expanded use of robin_map to cover some uses that are going to leak small amounts of memory in a way that's totally okay.

Suppress leak sanitizer warnings about internals of robin_hash

---

CHANGES.md
THIRD-PARTY.md
doc/build_install/windows/build_osl.py
src/build-scripts/build_openimageio.bash

* Fix references to old OIIO home
* Fix embarrassing release notes generating script botch that accidentally used OpenImageIO URLs where OSL URLs were needed.

docs: fix outdated or wrong repo URLs

---

src/testrender/optixraytracer.cpp
src/testrender/simpleraytracer.cpp
src/testrender/simpleraytracer.h
src/testrender/testrender.cpp

A few months back, PR #1733 seems to have switched the order that testrender destroys the shading system versus the renderer (services).
This made some subtle bugs that were only symptomatic for GPU renders, but it's because of the destructor order, where the shadingsystem's dtr still references the renderer, which cannot be destroyed yet.
The clue is that the SS's constructor takes the RS pointer as an argument. The RS, then, must have been constructed before the SS, and therefore we should expect it to be a requirement for the RS to outlast the lifetime of the SS. (Complex objects should be destroyed in the opposite order that they were constructed, if they contain references to each other.)

fix: Fix testrender GPU regression with bad destruction order

---

testsuite/array-copy/ref/out-alt.txt

Was spuriously failing tests only because on GPU, the points didn't always execute in the same order.
(This just adds an additional reference output with same results, but different point order.)

testing: Update ref output for OptiX execution order variance

---

src/doc/languagespec.tex
src/doc/stdlib.md

* The new parameter was explained, but not added to the function prototype in the docs.
* The semi-deprecated languagespec.tex was fixed, but it slipped our minds that we've shifted the docs to markdown for ReadTheDocs (the real place we should have changed was stdlib.md).

docs: Fixes to documentation of new oren_nayar_diffuse_bsdf parameters

---

src/liboslexec/optexture.cpp

I missed an unnecessary ustringhash to ustring conversion back in #1792. Looking up the interp value directly from the ustringhash fixes a performance regression caused by the conversion.

Remove unnecessary ustring lookup

---

src/liboslexec/runtimeoptimize.cpp
testsuite/globals-needed/ref/out.txt

The backfacing shadeop now directly accesses the backfacing field on the shader globals rather than calculating it from N and I. 
This updates the shader-globals-needed query to reflect that change.

fix: make backfacing shadeop indicate backfacing shader-global is needed

---

src/doc/languagespec.tex
src/doc/stdlib.md
src/shaders/stdosl.h
src/testrender/shading.cpp

We intended this closure to take the effective color and radius so that the SSS color remapping can be controlled by the renderer.
The implementation in testrender uses a simple diffuse response (which was effectively assuming it got a multiple-scattered albedo. So all that was needed was renaming the parameters and updating docs.

Fix the subsurface_bssrdf parameters

---

src/cmake/compiler.cmake

This does not change the minimum C++ standard, which is still C++14, even in main. But it does change the default in main to build in C++17 mode, and to get 14 you have to say so explicitly.
We do anticipate bumping the minimum before this fall's release, and this is just a half step to get us ready. Maybe it will help shake loose any compatibility problems and remind people on main that they are using a branch that in a few months will have a new minimum C++.
This will not be backported to the release.

build: Default to C++17 mode

---

CMakeLists.txt
src/include/OSL/oslnoise.h
src/liboslexec/llvm_ops.cpp
src/liboslexec/shadingsys.cpp
src/liboslexec/wide/wide_optest_float.cpp
src/liboslexec/wide/wide_shadingsys.cpp
src/liboslnoise/gabornoise.cpp
src/liboslnoise/sfm_gabornoise.h
src/testshade/testshade.cpp

Various minor changes to eliminate references to long-ago deprecated OIIO items (mostly which simply alias to std versions).

cleanup: OIIO deprecations

---

.github/workflows/release-notice.yml

This fixed the icon used by the release notice to make it show up better.
N/A

Change release notice icon to use the icon vs the normal logo so it shows up better

---

.github/workflows/ci.yml

They upgraded to a version that requires a glibc newer than is in the pre-2023 ASWF containers.

Fix GHA CI after they upgraded nodejs

---

src/testshade/testshade.cpp

This was breaking OSL's CI after a recent OIIO master merge that more thoroughly hit certain long-deprecated functions.

cleanup: Swich away from deprecated OIIO function names

---

src/build-scripts/gh-installdeps.bash

This was breaking CI for us. Hard break for icc/icx tests, since those REQUIRED a yum install of the intel compilers. Softer undetected break for all the ASWF <= 2022 containers based on CentOS 7, which were not failing outright but were failing to install certain optional packages.
The solution (for now) is to configure yum to exclude the missing repo.

ci: deal with CentOS 7 EOL and disappearance of yum mirrors

---

src/cmake/testing.cmake
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp
testsuite/reparam-string/ref/out.txt
testsuite/reparam-string/run.py
testsuite/reparam-string/test.osl

This PR fixes a regression that went unnoticed during the ustringhash conversion.
Right now OSL expects strings to be represented at runtime as ustringhashes, but interactive parameters' values are still being stored as ustrings. This requires fixing in two locations, first the code that sets the initial value of an interactive parameter, and second the code that copies updated parameters into the interactive buffer.
New reparameter-strings test.

Fix reparameter string representation

---

src/include/OSL/oslexec.h
src/liboslexec/shadeimage.cpp
src/osltoy/osltoyrenderer.cpp

... instead of long-deprecated parallel_options.
This is an API compatible change because OIIO itself has a paropt constructor that takes a parallel_options, and I'll leave that deprecated but present for a bit longer in OIIO.
For the sake of link compatibility, we leave the old function defined in shade_image.cpp, so this should not present an ABI change. We'll remove the old version later when it's safe.

api: Switch shade_image to use current OIIO::paropt

---

src/cmake/modules/FindLLVM.cmake

build: llvm 18 compat issue - include libclangAPINotes

---

src/cmake/flexbison.cmake

Homebrew changes location by default on the new ARM-based Macs. Check the new paths, too.

build: Make finding bison work better on Apple Silicon Macs + homebrew

---

src/liboslexec/wide/wide_optexture.cpp

The convention in the single-point RendererServices is that the texture call returns derivatives in st space, and they are transformed to xy space before returning from the wrapper to RenderServices.  This change makes BatchedRendererServices follow the same convention.
This is still tested by testrender/testshade, but the code motion means the assumptions visible at the renderer/OSL boundary are now consistent between batched/non-batched renderservices.

fix(batched): Assume BatchedRendererServices texture derivatives are in st space.

---

src/liboslexec/oslexec_pvt.h
src/liboslexec/rendservices.cpp
src/liboslexec/shadingsys.cpp
src/osl.imageio/oslinput.cpp
src/testshade/testshade.cpp

On the OIIO side, there's a PR in review that changes the ImageCache and TextureSystem APIs to return shared_ptr instead of raw. (https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4377) This is destined for the upcoming OIIO 3.0 release.
This patch on the OSL side ensures that we build cleanly against both OIIO 2.x and 3.0 after that patch is merged.

build(deps): Adjust to OIIO change to IC/TS API

---

src/liboslexec/llvm_gen.cpp

The GPU calling convention for variadic shadeops is to pass a pointer to the extra parameters as the op's final argument. Currently calls to osl_pointcloud_search don't follow this convention, so their ptx fails to compile due to argument count mismatches.
This PR doesn't implement the full correct behavior, it just adds a nullptr to the end of OptiX calls to osl_pointcloud_search. This makes everything at least compile, so scenes that have pointcloud operations can fail more gracefully on GPU (for now).

Mock gpu pointcloud_search calls with empty custom attributes

---

src/cmake/modules/FindLLVM.cmake

This change fixes LLVM find package ignoring the library path provided by LLVM_CONFIG and picking up a system-wide library instead.
This happens when a custom LLVM is compiled statically, and there is a system-wide LLVM of the version which OSL expects.
The solution is to pass NO_DEFAULT_PATH to the find_library so that the function only considers paths explicitly coming from the LLVM's configuration executable.
It is a bit unclear what is the expected behavior of this module when LLVM_CONFIG is not available. It is possible to limit possible side effects of this change by only ignoring default paths if the LLVM CONFIG executable is found.
In practice this issue happened in Blender's build environment where HIP is used for OpenImageDenoiser: HIP toolchain pulls in LLVM system wide. While …

Fix LLVM find package picking up system-wide libraries

---

src/testrender/shading.cpp

The MaterialX team noticed this issue here: https://github.com/AcademySoftwareFoundation/MaterialX/pull/2016
Basically, if you add a medium through the `anisotropic_vdf` closure, it should not force the ior back to 1.0 as this IOR might have been changed by one of the microfacet closures. The IOR already defaults to 1.0 so cases that do not involve a microfacet closure are not affected.

anisotropic_vdf closure should not set IOR

---

src/include/OSL/dual.h

fix: Typo in dual.h made invalid template DualStorage

---

src/osltoy/osltoyapp.cpp
src/osltoy/osltoyapp.h
src/osltoy/osltoymain.cpp

For Dev Days
#1862 
Addressing a osltoy feature request, I've added the ability to specify custom search paths. 
The changes consist of the following:
- Added a command line option `-I <path>` to specify search paths (`OIIO::ArgParse` unfortunately can't mirror `OSLCompiler`'s `-Ipath` syntax)
- OSLToyMainWindow now stores an array of `OSLCompiler` options alongside a flag indicating whether or not they should be regenerated before compilation. The only option currently able to be specified is `-Ipath`, but this should ease any future extension.
- Added a GUI component consiting of a window with a mutable list of the current set of search paths. This list is initially populated with any paths passed via the command line, but any modifications to the list will be reflected when the shader …

osltoy - Feature Request: custom #include search paths

---

src/testshade/rs_simplerend.cpp

OIIO 3.0 shifts some things around slightly and requires us to include fmath.h directly in a place where we had been inadvertently relying on it getting included transitively (but now is not).

deps: Add include to deal with OIIO 3.0 deprecations

---

src/liboslexec/llvmutil_test.cpp
src/liboslnoise/oslnoise_test.cpp
src/oslinfo/oslinfo.cpp
src/osltoy/osltoymain.cpp
src/testrender/testrender.cpp
src/testshade/testshade.cpp

OIIO 3.0 will finally warn aggressively about some long-deprecated ArgParse methods. Switch to the newer idioms on the OSL side.

build(deps): Fixes to using OIIO::ArgParse for OIIO 3.0

---

.github/workflows/ci.yml

The new test fails now, because we need to fix some things on the OSL side to work with some late-breaking changes in the OIIO 3.0 beta. Coming soon.

ci: Bump latest and bleeding edge versions, also build against OIIO 3.0 beta

---

Makefile
src/cmake/compiler.cmake
src/include/OSL/batched_texture.h
src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/batched_llvm_instance.cpp
src/liboslexec/constfold.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/optexture.cpp
src/liboslexec/oslexec_pvt.h

OIIO 3.0 changes the TextureOpt structure a bit, and we need to adjust on the OSL end, too.
To have context for this, you need to be aware of https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4485 and https://github.com/AcademySoftwareFoundation/OpenImageIO/pull/4490.

build(deps): Adjust to OIIO changes to TextureOpt structure

---

src/include/OSL/oslconfig.h.in
src/testrender/CMakeLists.txt
src/testrender/cuda/rend_lib.cu
src/testshade/CMakeLists.txt
src/testshade/cuda/optix_grid_renderer.cu
src/testshade/rs_simplerend.cpp

The recent free function change (#1852) put the OptiX paths in testrender and testshade in a non-working state (issue #1894). The bitcode for the free functions wasn't plumbed through for OptiX. This PR rolls the free function definitions into the existing "rendlib" bitcode and PTX. This is somewhat of a stopgap fix; eventually we'll want to handle the free function more explicitly.
No new tests added. But all existing OptiX tests pass.

Fix the OptiX path in testrender and testshade

---

.github/workflows/ci.yml
src/build-scripts/build_opencolorio.bash

Some of the changes are specifically related to OIIO 3.0 requiring OCIO and raising the minimum version it needs.
Also, we can eliminate the extra test we added to specifically test the 3.0 betas (now "release" picks up 3.0, so getting dev-3.0 explicitly isn't really needed).

ci: Various adjustments for OIIO 3.0 becoming the release

---

.github/workflows/ci.yml

Identical in spirit to the coresponding PR for OpenImageIO.
The background here takes some explaining...
The ASWF's prepared Docker containers that reproduce a CentOS7-based environment corresponding to VFX Platform 2021 and 2022 years contain a glibc that is too old to run a newer version of "node" -- which GitHub Actions themselves use. The old one is no longer receiving support, and GitHub finally changed the policy that was allowing its GHA runners to still run the old version that worked with those ASWF containers.  The new node version that is happy on the GHA runners requires a glibc newer than the one in the containers. So that breaks all our CI runs in 2021 and 2022 VFX Platform configurations.
See this thread, if you dare: …

ci: Fix broken CI for ASWF 2021 and 2022 containers

---

GOVERNANCE.md
README.md
doc/RELEASING.md

Also a little be of typo fixing and docs updating, mostly from comparing to the same docs in OIIO and picking the more thorough description.

docs: Update some URLs to our new vanity URLs

---

THIRD-PARTY.md
doc/dev/Build_Profiling.md
src/build-scripts/ninjatracing.py
src/cmake/compiler.cmake

build: add option for build profiling with clang -ftime-trace

---

src/liboslexec/batched_analysis.cpp
src/liboslexec/batched_llvm_instance.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp

Currently, symbols are only flagged for derivative computation if
- They're a dependency of an operation which requires derivatives
- They're connected to a downstream layer parameter which requires derivatives
- They're writable globals (except for N)
However, there's a fourth relevant case - when the renderer requests the symbol to be written as an output with derivatives. This is possible via `SymLocationDesc`, but in the current implementation, this only ends up writing derivatives if one of the three cases above also happens to be true.
Therefore, detect this case and explicitly mark the symbol as requiring dependencies.
No tests at the moment since it would require extensive changes to testshade. Let me know if this is something that you'd consider necessary here.
already run …

Generate symbol derivatives for outputs when requested

---

src/liboslcomp/symtab.cpp
src/liboslexec/batched_llvm_instance.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/master.cpp
src/liboslexec/runtimeoptimize.cpp

After reduction of shared dependencies in #1890, there is an unresolved OSLCompiler constructor symbol when linking liboslexec. Avoid including the oslcomp_pvt.h header that causes this.
N/A

fix: Link error on Windows due to shared symbols

---

.github/workflows/ci.yml
CMakeLists.txt
INSTALL.md
src/build-scripts/build_cmake.bash
src/build-scripts/build_llvm.bash
src/cmake/externalpackages.cmake
src/cmake/modules/FindLLVM.cmake
src/liboslexec/llvm_passes.h
src/liboslexec/llvm_util.cpp
src/liboslexec/opmatrix.cpp
src/shaders/CMakeLists.txt

Some last minute dependency adjustments before I cut a beta for OSL 1.14.
* Raise CMake minimum to 3.19 (from 3.15). This is still very conservative -- 4 years old, even more lax than our usual "3 years back" rule.
Raising to 3.18 matches OIIO 3.0, and compared to 3.15, it adds Cuda support as well as the `--debug-find` flag.  Further raising to 3.19 -- which in 2025 seems prudent, even though it's beyond the version chosen by OIIO 6 months ago -- adds more helpful features, including presets, and Apple Silicon support.
* Raise OpenImageIO to 2.5 (from 2.4). The current release is 3.0, FYI.
* Bump LLVM minimum to 11.0 (from 9.0). This is a pretty conservative move, still gives several years of back support, but brings a little code simplification. I expect that next year's OSL will raise …

deps: Raise dependencies: cmake 3.19, OIIO 2.5, LLVM 11

---

testsuite/color4/test.osl
testsuite/common/shaders/osl-unittest.h
testsuite/vector4/test.osl

Ugh, I broke test testsuite under OptiX a while back and it took me a while to notice. When I added new unit tests for color[24] and vector[24], I used the format() call, and that's not supported in OptiX mode. But printf is, so in this patch, I fix it all up and now the tests pass in OptiX.

fix: unbreak osl-unittest.h for OptiX

---

src/cmake/llvm_macros.cmake

To solve a problem finding system headers when building with command line tools instead of Xcode. Replaces some commented out code, as this should be a more general solution to the same problem.
Adding arch and minversion for completeness, not because of a particular known problem, but better to be sure everything matches up.
N/A

build: Use macOS sysroot, arch, minversion for generating bitcode

---

src/liboslcomp/oslcomp.cpp

I think this stems from libclang (doing the C preprocessing step for us) giving us relative paths on all platforms but Windows, where it gives absolute paths -- with backslaches and C:\ and all.
I'm going to be conservative and not switch to relative paths accross the board on Windows, but for now just restrict it to the builds we do for CI, in order to make the related tests pass for Windows on our CI (where we obviously don't want to have the reference output need to bake in absolute paths of the place they may happen to execute on the GHA runners).

testing: for CI only, trim PWD from the oslc -M output

---

src/include/OSL/oslexec.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp

This PR adds an API to ask the shading system if derivatives are required for attributes.

Add api to ask if attribute derivatives are requested.

---

src/doc/languagespec.tex
src/doc/stdlib.md

Sorry, I was the one who committed the typo in the first place!
N/A
- [ x ] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [ x ] I have updated the documentation, if applicable.
- [ x ] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [ x ] My code follows the prevailing code style of this project. If I haven't

Docs: Fix typo in the name of the argument "maxdist" of `trace`

---

src/cmake/testing.cmake
testsuite/runtest.py

For any individual test running, the OSL_TESTSUITE_THRESH_SCALE environment variable, if set, will scale the image comparison thresholds used to decide if a test passes.
Furthermore, a special OSL_TESTSUITE_OPTIX_THRESH_SCALE environment variable, if set, will cause *all* OptiX related tests to be set up with scaled thresholds.

testing: env variable OSL_TESTSUITE_THRESH_SCALE scales test thresholds

---

src/osltoy/osltoyapp.cpp

Qt 6.8 deprecates QCheckBox::stateChanged().

deps: Adjust osltoy for Qt 6.8

---

src/include/OSL/rendererservices.h
src/liboslexec/backendllvm.h
src/liboslexec/instance.cpp
src/liboslexec/llvm_gen.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/runtimeoptimize.h
src/liboslexec/shadingsys.cpp

This change adds a caching layer to the OptiX PTX pipeline that can skip LLVM generation and optimization. This helps improve scene build times for re-renders of scenes with large shader counts.
We generate a hash key from the optimized shadergroup, and depend on the renderer to provide a cache backend implementation. There is no overhead if the renderer doesn't explicitly opt-in to ptx caching.
A simple backend will be added to testshade/testrender in a follow-up PR.

API for renderer to cache OptiX ptx

---

src/doc/datatypes.md
src/doc/syntax.md

Resolves #1921
However, it could also be helpful to add in syntax.md (https://open-shading-language.readthedocs.io/en/latest/syntax.html#arrays) that only 1D arrays are supported. The fix so far only mentions this in datatypes.md (https://open-shading-language.readthedocs.io/en/latest/datatypes.html#arrays). Any suggestions?
Documentation built locally with sphinx, to ensure the changes worked.

Docs: Fix typo in Arrays

---

.github/workflows/build-steps.yml
.github/workflows/ci.yml
src/build-scripts/gh-installdeps.bash
src/cmake/externalpackages.cmake
src/cmake/modules/FindLLVM.cmake

Apparently, in LLVM 18, some things shifted between libraries and that requires a slightly different link order. But only on Linux, or maybe only with static libraries, so even though our Mac and Windows CI tests have used LLVM 18, it wasn't symptomatic there.
We didn't discover this earlier because we didn't actually test against LLVM 18 on any of the Linux CI runs. So we add that.
Also, to alleviate the pain in adjusting LLVM versions and often needing to modify our build_llvm.bash script, I'm trying out a GHA marketplace action KyleMayes/install-llvm-action, and it works well and saved me time, so we may switch to that for other cases over time as well.

build: Fix libclang link order

---

src/liboslexec/optexture.cpp
src/testrender/cuda/rend_lib.cu

Recent PR #1852 (Free functions for texturing, point clouds, and trace) added host/device decorations to certain `osl_` functions that previously were replicated in OptiX-based renderers. This means that now the ones in those renderers will be seen as duplicate symbols.
The more clear intent that we'd like to work towards is that all the `osl_` functions are meant to be "internal" to the liboslexec or the bitcode it provides, and the `rs_` functions are the customization points that the renderer is expected to supply.
Except... a bunch of the `osl_` functions that set parameters for subsequent texture and trace calls do not yet have `rs_` customization points. So we're actually not quite ready to change things.
To unbreak, then, this PR removes the `__device__` decorations (so they are …

Re-remove device decoration from some osl_ functions

---

src/liboslcomp/oslcomp_pvt.h

This is a change that seems to be needed if building with C++20.

int: Proper forwarding

---

.github/workflows/build-steps.yml
.github/workflows/ci.yml
src/build-scripts/gh-installdeps.bash
src/build-scripts/run-clang-format.bash
testsuite/example-batched-deformer/oslbatcheddeformer.cpp
testsuite/example-cuda/rend_lib.cu
testsuite/example-deformer/osldeformer.cpp

Make a new run-clang-format.bash utility to issue the commands for the right files. No "build" is required, and the only dependencies we need are the minimum it takes to run clang-format itself.
These changes reduce the approximate total elapsed time of a CI clang-format job from 8:00+ to under 0:30.
In the process, this catches a couple files in testsuite that were never going through the clang-format test, so fix that now.

ci: improve clang-format check

---

.github/workflows/ci.yml

GitHub has deprecated the older versions we were still using.

ci: Update cache action to modern version

---

src/liboslexec/instance.cpp

The ptx cache key introduced in #1938 didn't include a shader's entry layer name in its cache key. The direct callable function generated during llvm construction includes this layer name, so we could get false positive cache hits when two identical networks with matching group names had different entry layer names. The end result is an optix compilation error. This PR extends the cache key to handle this scenario.

Include entry layer name in PTX cache key

---

.github/workflows/build-steps.yml
.github/workflows/ci.yml
INSTALL.md

Bump to the latest in several cases. Also make sure the INSTALL.md is in line with what we support and/or test.

ci: bump dependencies for "latest versions" CI test

---

INSTALL.md
src/build-scripts/build_opencolorio.bash
src/build-scripts/build_pybind11.bash
src/build-scripts/build_zlib.bash

The tricky part is that several dependencies break because of cmake 4.0 dropping support for strict compatbility with cmake < 3.5. Have to resort to some trickery with CMAKE_POLICY_VERSION_MINIMUM overriding what those packages declare via their own cmake_minimum_required(), and hope it works.

build: Support for CMake 4.0

---

.github/workflows/ci.yml
src/build-scripts/install_homebrew_deps.bash

We're not LLVM 20 compatible yet, we'll deal with that separately and not under the time pressure of a major releases that's overdue.

build: Unbreak CI on Mac by not letting it install llvm 20

---

.github/workflows/ci.yml
src/build-scripts/install_homebrew_deps.bash
src/cmake/externalpackages.cmake
src/cmake/llvm_macros.cmake

The combination of cmake 4.0, changing homebrew default package versions, and slight changes rolled out to the GitHub Actions runner images conspired to break our CI for 2 of 3 Mac variants. Fixes:
* Apple: only add the -isysroot to the bitcode-generating clang++ command if CMAKE_OSX_SYSROOT is defined. Plot twist -- this is no longer set by cmake  starting with cmake 4.0!
* Fix incorrect warning message for apple clang vs newish llvm in externalpackages.cmake.
* Remove homebrew unlinking of python@3.10 that warned in install_homebrew_deps.bash. On the GHA runners, it was giving us warnings because we were asking this package to be unlinked but it wasn't installed.  For future needs, add an env variable based way to unlink individual packges.

build: Fix various MacOS problems with GitHub and CMake

---

.github/workflows/ci.yml
src/liboslexec/shadingsys.cpp

This symbol was for an architecture that never shipped mainstream, we don't need to look for it.

build: Remove unused symbol that was removed from OIIO main

---

src/liboslexec/CMakeLists.txt

The batched libraries seem to require at least one symbol provided by liboslexec : `OSL::v1_14::Strings::null`. If this is not available, then attempts to do batch shading result in the following error at runtime :
```
ERROR: /home/john/dev/build/gaffer-1.6/lib/lib_b16_AVX512_noFMA_oslexec.so could not be loaded with error "/home/john/dev/build/gaffer-1.6/lib/lib_b16_AVX512_noFMA_oslexec.so: undefined symbol: _ZN3OSL5v1_147Strings4nullE"
LLVM_Util::call_function(osl_b16_AVX512_noFMA_allocate_weighted_closure_component_masked, args), requested function name doesn't exist in the current module!
/home/john/dev/gafferDependencies/OpenShadingLanguage/working/OpenShadingLanguage-1.14.5.1/src/liboslexec/llvm_util.cpp:4370: call_function: Assertion 'func' failed.
```
This came up in Gaffer, where …

build: Link batched libraries with liboslexec

---

src/cmake/modules/FindOptiX.cmake

There was still some logic that was only needed during the period that we supported both OptiX 6 and 7+.

build: Simplify FindOptiX.cmake a bit now that OptiX 7 is the minimum

---

.github/workflows/ci.yml
src/build-scripts/gh-installdeps.bash

NVIDIA recently set up a GitHub repo with the OptiX headers (with version tags!), which is much better than the unreliable semi-secret location we used to use.

build: Get OptiX headers from new improved location

---

.github/workflows/build-steps.yml
.github/workflows/ci.yml
src/build-scripts/ci-build.bash
src/build-scripts/ci-startup.bash
src/cmake/compiler.cmake

I recently discovered that the caching of our ccache was either not working at all, or was much less efficient/heplful than I thought. So there are a number of improvements here:
- Split caching into separate restore/save, and rearrange the step order so we save cache before tests run. This allows us to save the ccache even for jobs with failed tests (where the all-in-one unsplit approach would skip the cache save step for a failed job), or for jobs that we purposely end early (maybe because we see failing tests), not only when all tests finish and succeed. This makes subsequent builds, that we do on the same branch while attempting to fix failures, go faster by using the cache.
- Make subsequent pushes to the same PR or REF to cancel any previous jobs, so if we push updates before the …

ci: improve CI caching scheme

---

src/liboslexec/shadingsys.cpp

ShadingSystem() wasn't checking whether the offset returned by interactive_param_offset() was valid or not before performing the ReParameter() memcpy().  So, we could copy data to a location outside of a valid memory block and cause a crash.
tests pass except for '987 - render-microfacet.opt (Failed)' but I get the same error for main.

check for errors in ShadingSystem::ReParameter()

---

src/liboslcomp/CMakeLists.txt
src/liboslexec/CMakeLists.txt
src/liboslnoise/CMakeLists.txt
src/liboslquery/CMakeLists.txt
src/oslc/CMakeLists.txt
src/oslinfo/CMakeLists.txt
src/osltoy/CMakeLists.txt
src/testrender/CMakeLists.txt
src/testshade/CMakeLists.txt

Adds directives to prioritize the includes from $OpenImageIO_ROOT in case there is an older (or newer!) system install of OpenImageIO.  Without this, OSL might use the includes in /usr/include/OpenImageIO yet link to the libraries in OpenImageIO_ROOT thus producing namespace clashes.
tests pass excdept for '987 - render-microfacet.opt', but I get the same failure for main.

update include directives for OpenImageIO_ROOT

---

INSTALL.md
src/cmake/externalpackages.cmake
src/include/OSL/platform.h
src/liboslexec/llvm_util.cpp

This adds LLVM 20 compatibility. The changes are thankfully quite concise. 
Fixes #1963.

Add compatibility with LLVM 20.1

---

.github/workflows/ci.yml
INSTALL.md
src/build-scripts/build_openimageio.bash
src/liboslquery/py_osl.cpp

Add pybind11 3.0 to the CI test matrix.
Found a place where we defined a python method twice, fixed that.
Ran into some trouble where the Mac runners which used a pre-built OIIO supplied by Homebrew, and apparently compiled against pybind11 2.x.  I think maybe there are some corner cases where if you have two python modules that share types (TypeDesc and a few more, in this case), they should not be built with pre-3.0 and post-3.0 versions of pybind11?
The quick fix was to switch to having OSL CI on Mac just build an OIIO from scratch to ensure that it was using the same pybind11. But that identified yet another problem (which I also think is a runner issue) that required some minor adjustment to how OIIO auto-builds libpng.

deps: test against pybind11 3.0 and minor fixes

---

.github/workflows/ci.yml
src/build-scripts/gh-win-installdeps.bash

Fixes #2003 
Recap: GHA Windows runners recently upgraded their MSVS to a version whose std headers no longer get along with the LLVM 18 we had been using for CI (which we download from the LLVM project's hosted binary builds). But upgrading to LLVM 19 or 20 didn't help, because all of the LLVM-hosted binaries of those releases were built with the flags selecting the static runtime library, which is different from the dynamic choice that's a more common default and which we used for both our build of OSL and its other dependencies. You can't mix and match. (The reason for this switch is related to their changing to build by default using a certain malloc repacement library, which somehow leads to needing the static runtime.)
To dig us out of this, Chris Kulla was kind enough to build us …

ci: Fix Windows CI with special LLVM pre-build

---

.github/workflows/ci.yml
src/build-scripts/build_pybind11.bash
src/osltoy/osltoyapp.cpp

And some minor tweaks for gcc14 + C++20 warnings

ci: Add a VFX 2026 platform test

---

.github/workflows/ci.yml

Most of these changes are actually just making the comments match what we really do. But some update or lock down the OIIO and OCIO versions we test against. Both packages had big releases this week, and for OIIO in particular, "release" now means 3.1, not 3.0 as it did last week.

ci: Adjust test matrix for recent OIIO and OCIO releases
