AcademySoftwareFoundation/OpenShadingLanguage

src/liboslexec/llvm_gen.cpp
src/liboslexec/rendservices.cpp

Restore compatibility with OIIO 1.5

---

src/liboslexec/llvm_instance.cpp

Markv asked if debugnan checks that its results aren't NaN/Inf. I thought it should, but upon checking, see that it didn't (and, sorry, even had a comment saying where I intended for it to be). So this patch implements the missing check.

Make debugnan also check the results of interpolated userdata

---

src/liboslexec/llvm_gen.cpp

1. The test for matching types of the keyword parameters were too strict.  It used '==' test for exact type match, should have been equivalent() so that all the 3-vector types would be treated the same. This is because at this point in code generation, temporaries whose lifetimes do not overlap have been coalesced -- so maybe a point and color were merged, for example.
2. In the event of a keyword mismatch, it skipped the code generation for filling in that slot, leaving it uninitialized. Probably not good. So now we explicitly zero out the optional parameter for a keyword that is unknown.

Fixed two bugs in generating code for closure optional keyword parameters

---

site/spi/Makefile-bits

Build changes for rhel7 at SPI

fix for rhel7 at SPI

---

src/liboslexec/instance.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp

Odds and ends I found while debugging recently, but these are not the actual fixes.

Improve some debugging printfs, assertions, and the like.

---

Makefile

This greatly speeds up build times, especially for incremental and
null builds.
Full (non-ccache, post-make nuke) build improves from 0:47s to 0:43).
Full build, fully ccached, improves 14.7 to 11.6.
Null build (nothing changed) improves from 2.4s to < 0.2s.
Identical change on the OIIO side can be found here:
https://github.com/OpenImageIO/oiio/pull/1158

'make USE_NINJA=1' uses Ninja back end rather than make

---

Makefile
site/spi/Makefile-bits

Same set of changes as here: https://github.com/OpenImageIO/oiio/pull/1160

Simplify ninja logic and make SPI customizations for finding its path

---

Makefile

Same as Brecht's patch here: https://github.com/OpenImageIO/oiio/pull/1164

Fix multithreaded build with make -jN no longer working.

---

src/testshade/testshade.cpp

Just realized that there was already a Filesystem call that does what was performed longhand here.

Misc refactoring of testshade

---

src/liboslexec/constfold.cpp

Suppose you have a call to noise:
C = noise (noisetype, P, "bandwidth", val);
Let's suppose that noisetype is a shader parameter. We're passing the optional "bandwidth" paramter just in case noisetype is "gabor" at runtime. But if it's not (let's say it's "perlin"), we're needlessly computing whatever is in 'val'. In fact, "gabor" is currently the only noise type that uses any of the optional token/value arguments to noise.
This patch culls any optional noise arguments during runtime optimization, if the noise type can be deduced to be anything other than "gabor".

Optimize away unused optional arguments to noise.

---

src/testshade/testshade.cpp

This makes it match how OIIO's "testtex" can set st ranges.
Also, I made -res a synonym for -g, I seem to always get that wrong, and now I can't remember why I would have used -g instead of -res.

Allow testshade to have st ranges other than 0-1. (For more flexible tests)

---

CMakeLists.txt

Same fix as https://github.com/OpenImageIO/oiio/pull/1254

Ensure proper build on Apple Clang 6.1

---

src/include/OSL/oslexec.h
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp

This was helpful for me in a debugging situation.

SS attribute 'connection_error' controls whether bad connection is a true error

---

src/liboslexec/shadeimage.cpp
src/liboslexec/shadingsys.cpp

Have I ranted lately about how much I hate size_t?

Fix compiler warnings related to int vs size_t

---

src/liboslexec/builtindecl.h
src/liboslexec/constfold.cpp
src/liboslexec/opstring.cpp
src/liboslexec/shadingsys.cpp
src/shaders/stdosl.h
testsuite/string/ref/out.txt
testsuite/string/test.osl

These two small functions will be useful from an upcoming contribution to `oslutil.h`.

Add string indexing and string hashing functions to stdosl.h

---

src/liboslexec/llvm_util.cpp

The last couple checkins botched some stuff, was leading to crashes
on real frames even though testsuite had passed. For the LLVM 3.5
case, it wasn't right.
1. The call to materializeAll() in do_optimize seems suspicious
for LLVM 3.5, taking it away solves crashes, so at Chris Kulla's
suggestion we're changing from #if OSL_LLVM_VERSION >= 35 to
> 35, so it only does the materializeAll for MCJIT cases.
2. LLVM_Util::module_from_bitcode was a mess. Impossible to follow.
Instead of a line-by-line #ifdef madness, I refactored it into a
much simpler <= 3.5 section and a >= 3.6 section, even if there was
some code repetition between the two. Also, I hereby declare that
we will not support LLVM 3.6, which further simplifies the logic.
3. As a result of that refactor, it was more obvious that …

Fix recent breakage against LLVM 3.5

---

.travis.yml
CHANGES.md
CMakeLists.txt
Makefile
site/spi/Makefile-bits
src/build-scripts/install_homebrew_deps.bash
src/include/CMakeLists.txt
src/include/OSL/oslconfig.h
src/include/OSL/oslversion.h.in

C++11: switch to C++11 baseline

---

CMakeLists.txt
Makefile
src/cmake/compiler.cmake
src/cmake/externalpackages.cmake
src/cmake/install.cmake
src/liboslexec/CMakeLists.txt

This mimics a cmake refactor we did recently in OIIO master.

Move compiler and installation logic to compiler.cmake, install.cmake

---

.travis.yml
site/spi/Makefile-bits
src/build-scripts/build_openexr.bash
src/include/OSL/matrix22.h

Includes some general cleanup of the .travis.yml file.

Add gcc7 to the Travis lineup, fix warnings, etc.

---

src/include/osl_pvt.h
src/liboslcomp/codegen.cpp
src/liboslcomp/oslcomp.cpp
src/liboslcomp/symtab.cpp
src/liboslexec/context.cpp
src/liboslexec/dictionary.cpp
src/liboslexec/lpexp.cpp
src/liboslexec/master.cpp
src/liboslexec/runtimeoptimize.cpp
src/liboslexec/shadingsys.cpp

Replace many loops with range-for

---

src/liboslexec/instance.cpp

We previously allowed float to vec3 conversions, and it turns out some workflows at SPI could lead to float parameters being passed in as int which we need to perserve.
However, we don't want to get too much more relaxed that this, so make all other cases errors because other mismatches should be flagged as bigger problems and not silently make the wrong picture.

Make relaxed parameter type checking less strict

---

src/include/OSL/oslquery.h
src/liboslquery/oslquery.cpp

@markfinal, I think it needed full implementations in order to properly set the `data` field.

Add missing OSLQuery::Parameter correct assignment operator

---

src/liboslexec/lpeparse.cpp

Fix compiler warning about possibly uninitialized variable (false positive)

---

CMakeLists.txt
src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h
src/oslc/oslcmain.cpp
testsuite/Werror/ref/out.txt
testsuite/Werror/run.py
testsuite/Werror/test.osl
testsuite/runtest.py

This flag to oslc will treat all warnings issued as if they were errors.

oslc -Werror

---

src/doc/languagespec.tex

Fixes #869
Fixes #870
[ci skip]

Fix docs typos

---

src/liboslexec/shadingsys.cpp

Thanks, Zap, for noticing this error.

Fix error_repeats: clearing happened for getattribute instead of attribute

---

src/osl.imageio/oslinput.cpp

See https://github.com/OpenImageIO/oiio/pull/1927
This makes OSL compile cleanly both before and after this breaking change in OIIO master.
(The OIIO changes doesn't break source compatibility for OIIO-calling apps, but it does change code that implements ImageInput subclasses, as we are doing here.)

Updates to handle OIIO ImageInput refactor.

---

src/osl.imageio/CMakeLists.txt
src/osl.imageio/oslinput.cpp

OSL-side changes to make it build properly with this proposed OIIO change:
https://github.com/OpenImageIO/oiio/pull/1934

Fixes for OIIO change to imageio create function signature

---

site/spi/Makefile-bits
src/liboslcomp/osllex.l
src/liboslexec/osolex.l

For some reason, this built ok on TravisCI, but not on the partciular
gcc6 version I had at work. Minor fix.

Warning fixes on gcc6

---

src/osltoy/qtutils.h

As #908 mentioned, I removed unnecessary nullptr check.
No

Remove useless nullptr check

---

src/osltoy/osltoyapp.cpp
src/osltoy/osltoyapp.h
src/osltoy/qtutils.h

Still a bit messy, but does the job.
Slider is in there to either provide a clamp/normalization or choose magnification level.
Does neither yet, so dealer's choice.

Add Pixel magnifier

---

src/liboslcomp/codegen.cpp
testsuite/struct-return/ref/out.txt
testsuite/struct-return/test.osl

Edge case that triggered an assert.

Fix crash with struct parameter assignment from function call.

---

src/testshade/testshade.cpp

Before testshade exits, check the ImageCache and TextureSystem and ask for any remaining error messages. In theory, all should have been properly captured and sent to the ErrorHandler and nothing should be left. If there is (that is, texture errors went unnoticed), consider it an error of the testshade execution. This is an aid to debugging interactions between OSL and the texture system.

testshade: check that no leftover errors are in the TS or IC

---

src/liboslcomp/typecheck.cpp
testsuite/oslc-err-initlist/ref/out.txt
testsuite/oslc-err-initlist/run.py
testsuite/oslc-err-initlist/test.osl

Fixes the the element count checking that occurs when initializing an array.
Added oslc-err-initlist

Fix array initialization counter

---

src/liboslcomp/ast.cpp
testsuite/oslc-err-paramdefault/ref/out.txt

Reword error with less yelling

---

site/spi/Makefile-bits

Older version uses an out of date Alembic.

[SPI] Update to latest partio version.

---

src/include/OSL/oslconfig.h
src/include/OSL/oslversion.h.in

Partly ported from equivalent changes in OIIO recently.

Some C++ definition and other touch-ups

---

CMakeLists.txt
src/liboslcomp/typecheck.cpp
testsuite/oslc-err-unknown-ctr/ref/out.txt
testsuite/oslc-err-unknown-ctr/run.py
testsuite/oslc-err-unknown-ctr/test.osl

The assertion was not needed, errors issue before this code is reached.

Fix oslc assertion on type constructor for unknown struct

---

src/liboslexec/shadingsys.cpp

Slight issue with OSLQuery::init always returning false.
Testing against CI

Fix OSLQuery::init return value on success

---

src/liboslcomp/ast.cpp

Avoids stack overflow for hideously complicated parse trees.

ASTNode: Make long chains of nodes (though m_next) free serially, not recursively

---

src/testrender/optixraytracer.cpp
src/testshade/optixgridrender.cpp

With -Werror this is promoted to an error (on gcc-4.8)

Fix sign/unsigned comparsison warning/error

---

site/spi/Makefile-bits

Also bump the default optix in my makefile wrapper for SPI, don't know
why that was so old.

Mark more tests as passing OptiX mode

---

src/build-scripts/docdeep.py
src/liboslexec/serialize-bc.py
src/shaders/MaterialX/build_materialX_osl.py
testsuite/fprintf/run.py
testsuite/runtest.py

Fix the things flagged by pylint --py3k
Fixes #1045

Python3 safety

---

src/cmake/modules/FindLLVM.cmake

Fix how we ask for LLVM static libs

---

src/include/OSL/platform.h

* Move OSL_NODISCARD by porting OIIO's OIIO_DISCARD.
* Also port OIIO_FALLTHROUGH.
* Move osl_assume_aligned to the end so it can be inside the usual
namespace. Also rename it assume_aligned to match C++20 and use a
`using` so that for C++20 it just aliases to the std one.

Cleanup of platform.h

---

src/include/OSL/dual.h

Thanks, Xavier Bec, for spotting this.

Fix mistake in recent-added operator-(Dual,T).

---

src/liboslexec/pointcloud.cpp

Fix compiler warning about signed/unsigned

---

src/include/OSL/dual.h

I had noticed the comment didn't match the code and updated the code not realizing it was the comment that was wrong ...

Fix cube root derivative sign

---

.github/ISSUE_TEMPLATE.md
ASWF/project_intake.md
CONTRIBUTING.md
GOVERNANCE.md
README.md

Update all references to the osl-dev mail list

---

src/build-scripts/oslcomp.pc.in
src/build-scripts/oslexec.pc.in
src/build-scripts/oslquery.pc.in

Fix typo in the .pc.in files that botched the version

---

src/include/OSL/llvm_util.h
src/liboslexec/llvm_util.cpp

These aren't used anywhere in OSL's codebase yet. But they will be.
By Alex Wells.

Add several wide data types and wide operations to LLVM_Util.

---

src/include/OSL/llvm_util.h
src/liboslexec/llvm_util.cpp

Expose packed flag to LLVM_Util::type_struct()

---

src/liboslexec/constfold.cpp
src/liboslexec/llvm_gen.cpp

Added various OSL_MAYBE_UNUSED to make compiler builds happy.

---

src/liboslexec/llvm_ops.cpp

Fix normalize() sqrt call to be sure it's using floats

---

src/testshade/simplerend.cpp

Modernize loop

---

src/liboslexec/llvm_util.cpp

Add `override` to the MemoryManager class.

---

src/liboslexec/llvm_instance.cpp

Change some data to static visibility

---

.github/workflows/workflow.yml
src/build-scripts/ci-build-and-test.bash
testsuite/runtest.py

This mimics the similar changes we did recently in OIIO.

GH CI: Failed tests save artifacts of all test output for debug

---

.clang-format
src/cmake/compiler.cmake
src/include/OSL/accum.h
src/include/OSL/export.h
src/include/osl_pvt.h
src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/codegen.cpp
src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h
src/liboslcomp/symtab.cpp
src/liboslcomp/symtab.h
src/liboslcomp/typecheck.cpp

Reformat the contents of src/liboslcomp
Some adjustment of .clang-format to match my taste.

More clang-format

---

.github/workflows/workflow.yml
src/liboslexec/shadingsys.cpp

And add workaround for some recent weirdness on their end (see the
related recent PR in OIIO).

Make sure to test against latest fmtlib

---

src/liboslexec/llvm_util.cpp

Avoid emitting any alloca instructions inside loops and reuse
temporaries across the body of a function, which means we should not
emit them in conditional branches either.  So always place alloca at
the very beginning of a function.  To do that, we save the current
insertion point, change it to the beginning of the function, emit the
alloca, then restore the insertion point to where it was previously.

Added ability to reuse allocas accross a function body.

---

src/cmake/compiler.cmake
src/liboslquery/oslquery.cpp
src/liboslquery/py_osl.cpp
src/liboslquery/querystub.cpp
src/osl.imageio/oslinput.cpp
src/oslc/oslcmain.cpp
src/oslinfo/oslinfo.cpp
src/osltoy/codeeditor.cpp
src/osltoy/codeeditor.h
src/osltoy/osltoyapp.cpp
src/osltoy/osltoyapp.h
src/osltoy/osltoymain.cpp
src/osltoy/osltoyrenderer.cpp
src/osltoy/osltoyrenderer.h
src/osltoy/qtutils.h

Still staying away from reformatting any of the areas that are currently
the subject of significant development work.

More clang-format: liboslquery, oslinfo, oslc, osl.imageio, osltoy

---

CHANGES.md

Fix spelling error in change log.
N/A

Fix spelling errors

---

src/liboslexec/opstring.cpp

Keep up with the long term fmt-related transition on the OIIO side.

Switch to the newer name of this OIIO function

---

src/testshade/testshade.cpp

testshade: make a way to force varying derivatives for testing

---

src/cmake/modules/FindLLVM.cmake

More flexible find of llvm-config with suffixed with '-64'

---

.github/workflows/ci.yml
src/build-scripts/install_homebrew_deps.bash
src/cmake/externalpackages.cmake

Fix CI build break on Mac with LLVM 10.0.1

---

CMakeLists.txt
site/spi/Makefile-bits
src/cmake/externalpackages.cmake
src/testrender/CMakeLists.txt
src/testrender/optixraytracer.cpp
src/testshade/CMakeLists.txt
src/testshade/optixgridrender.cpp

WIP:
I'm still having issues with the test-suite.
Running the tests individually/explicitly seems to pass, but if I run via **_ctest_** some shader's won't load.

Build against Cuda-11.0.1 and Optix 7.1

---

src/liboslexec/shadingsys.cpp

Remove ustring::format references, they will change meaning someday

---

src/osl.imageio/oslinput.cpp

While we're in there, get rid of some cruft that only applied to
OIIO 1.x.

Adjust for recent OIIO master change -- ImageInput no longer has m_mutex

---

src/build-scripts/build_opencolorio.bash

CI: build_opencolorio.bash: don't build gpu tests

---

src/include/OSL/mask.h

The version of Mask::first_on turned out not to have all the necessary
clauses fleshed out, breaking on Windows. So I refactored to get it
right.

Clean up Mask implementation of first_on

---

src/cmake/compiler.cmake
src/cmake/cuda_macros.cmake
src/include/OSL/export.h
src/liboslexec/CMakeLists.txt

This pull request fixes 1 compiler error when building using MSVC, and a lot of warnings (which makes errors quite hard to see)
Note: I'm waiting for the CLA, in the meantime if you have any comment on the pull request, don't hesitate.

Build fixes

---

src/testshade/simplerend.cpp
src/testshade/testshade.cpp

Fix compability break with OIIO < 2.2 (from change 1295)

---

src/include/OSL/mask.h

Rather than have complex per-platform implementations for the 64-bit
mask cases that we don't need for now, just assume that by the time we
need them, we can rely on the simple C++20 calls.

Simplify popcount and countr_zero implementations

---

ASWF/CLA-corporate-draft.md
ASWF/CLA-individual-draft.md
CONTRIBUTING.md

For review, these are the proposed new CLAs that will take effect after
the repo is moved from the imageworks to the AcademySoftwareFoundation
account. Please take to your orgs for approval if necessary. The TSC members
should expect to hold a vote to accept these at the next TSC meeting.

New ASWF preferred CLAs, based on Apache 2.0 CLAs

---

README.md

Embed sizzle reel video in main README

---

src/osltoy/osltoyrenderer.cpp
src/testshade/testshade.cpp

Switch from deprecated to current version of OIIO parallel_image call

---

INSTALL.md

Fix incorrect hyperlink for boost

---

src/shaders/vector2.h

This is useful when working with vec2 concepts through out shaders like UV data for example.
I can provide a working example if needed.

Updated vector2.h with a mod function: mod(vector2,vector2);

---

doc/build_install/windows/build_osl.py
src/liboslexec/batched_backendllvm.h
src/liboslexec/batched_llvm_gen.cpp
src/liboslexec/batched_llvm_instance.cpp
src/liboslexec/string_hash.h

Update several stray references to the old repo URL

---

.github/workflows/ci.yml

CI Mac fix: this was no longer necessary, and seemed to be problematic

---

.clang-format
.github/workflows/ci.yml
src/liboslcomp/codegen.cpp
src/osltoy/osltoyapp.h

CI: Change our clang-format standard to clang11

---

src/cmake/modules/FindLLVM.cmake

Build: llvm-config --system-libs needs --static for LLVM_STATIC

---

.github/workflows/ci.yml
INSTALL.md

CI: Bump OpenEXR versions to the latest patches in each branch

---

CMakeLists.txt

* "SOVERSION" option was set twice, oops!
* Stray "OIIO" in a name that should have been this project's name.

CMake fixes

---

.github/workflows/ci.yml
src/liboslcomp/osllex.l
src/liboslexec/osolex.l

Along the way, discovered and fixed a couple clang-specific warnings when
using C++17.

CI: add a clang11 test, also test batched shading with clang

---

src/include/OSL/oslexec.h
src/liboslexec/shadeimage.cpp

Move from some long-deprecated OIIO things to modern equivalents

---

src/include/OSL/oslquery.h
src/liboslexec/batched_llvm_instance.cpp
src/liboslexec/instance.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/loadshader.cpp
src/liboslexec/oslexec_pvt.h
src/liboslexec/shadingsys.cpp
src/liboslquery/oslquery.cpp

* OSLQuery::errorf (public)
* ShadingSysImpl::errorf, etc. (internals)
* Context::errorf (internals)

More string format convention modernization

---

src/include/OSL/llvm_util.h
src/liboslexec/batched_llvm_instance.cpp
src/liboslexec/llvm_instance.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/llvmutil_test.cpp

Convert some uses of temp vectors to span

---

src/include/osl_pvt.h

Give Symbol virtual destructor to fix UB because of derived classes.

---

GOVERNANCE.md

- [x ] I have read the [contribution guidelines](../CONTRIBUTING.md).
- [x ] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [x ] I have updated the documentation, if applicable.
- [x ] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [x ] My code follows the prevailing code style of this project.

Changing DNEG board member from Derek to Clint

---

src/include/OSL/oslclosure.h

Signed-off-by: Clifford Stein <cstein@imageworks.com>
Fixes return type mismatch
no changes in the testsuite

fixing return type

---

README.md

Signed-off-by: brendisurfs <brendan.prednis@protonmail.com>
This is just a small addition to the README.md, adding Maxon's Redshift to the list of software that supports OSL.

Added Redshift renderer to list of renderers/tools that support OSL.

---

src/liboslcomp/CMakeLists.txt
src/liboslexec/CMakeLists.txt
src/liboslnoise/CMakeLists.txt

CMake: use the more compact TARGET_NAME_IF_EXISTS to know if target exists

---

src/include/OSL/batched_texture.h

Catch up to change in OIIO TextureOptBatch in development

---

src/testrender/simpleraytracer.cpp
src/testshade/testshade.cpp

Because they can fail with some locales. Replace with OIIO::Strutil
parsing functions that are locale-independent.

Banish the last of the sscanf calls

---

.github/workflows/ci.yml
src/build-scripts/build_llvm.bash

CI: Update some of the 'latest' released versions we build against

---

.github/workflows/ci.yml

Adapt to OpenEXR/Imath changing branch master -> main

---

GOVERNANCE.md

Add Alex Wells to TSC, per recent vote

---

src/include/OSL/oslversion.h.in

Print all 4 version numbers in help messages

---

.gitignore

Just testing out commit workflow from windows 😄

Add Visual Studio Code folder to gitignore

---

src/include/OSL/oslconfig.h.in
src/liboslcomp/ast.cpp
src/liboslcomp/ast.h
src/liboslcomp/codegen.cpp
src/liboslcomp/oslcomp.cpp
src/liboslcomp/oslcomp_pvt.h
src/liboslcomp/oslgram.y

More fmt conversion

---

src/include/OSL/batched_texture.h

Typo fix in assertions

---

.github/workflows/ci.yml

ci: Bump OpenColorIO for 'latest' tests

---

CHANGES.md
CMakeLists.txt

Bump version to 1.13 after branching for 1.12

---

ASWF/project_intake.md

Mark DCO task as long since done

---

src/cmake/testing.cmake
testsuite/render-mx-conductor/run.py
testsuite/render-mx-dielectric-glass/run.py

Increase error threshold for tests

---

.github/workflows/ci.yml
testsuite/render-mx-generalized-schlick-glass/run.py

Also fix a CI test label -- we had a duplicate.

Testing: Adjust comparison thresholds to account for platform diffs

---

.github/workflows/analysis.yml
sonar-project.properties
src/build-scripts/ci-build.bash
src/build-scripts/ci-coverage.bash
src/build-scripts/gh-installdeps.bash

Try to enable Sonar Cloud static analysis

---

src/cmake/compiler.cmake
src/liboslexec/backendllvm.cpp
src/liboslexec/closure.cpp
src/liboslexec/llvm_ops.cpp
src/liboslexec/llvm_util.cpp
src/liboslexec/runtimeoptimize.cpp

clang-format: the very last piece of the puzzle

---

src/testrender/optixraytracer.cpp
src/testshade/optixgridrender.cpp

Fixes needed to support OptiX 7.4

---

.github/workflows/analysis.yml
src/include/OSL/oslnoise.h
src/liboslcomp/ast.cpp
src/liboslcomp/typecheck.cpp
src/liboslexec/splineimpl.h
src/liboslnoise/gabornoise.cpp
src/osltoy/osltoyapp.cpp
src/testrender/simpleraytracer.cpp

Fix minor bugs and warnings uncovered by SonarCloud

---

.github/workflows/ci.yml
INSTALL.md
src/build-scripts/gh-installdeps.bash

CI: test against python 3.10, gcc 12, latest fmt, update INSTALL

---

.git-blame-ignore-revs

Make sure all clang-format changes are in .git-blame-ignore-revs

---

doc/RELEASING.md

I've tried to write a complete set of step-by-step instructions for
everything about how to coordinate and deploy a release. This is a
living document, we will amend over time. I'm sure there must be
things I've forgotten.

Docs: RELEASING.md

---

CONTRIBUTING.md
INSTALL.md

Docs: Some minor updates to CONTRIBUTIONS and INSTALL docs

---

INSTALL.md
site/spi/Makefile-bits
src/liboslcomp/oslgram.y
src/liboslexec/instance.cpp
src/liboslexec/osogram.y

Note: this is only for building the code base with clang15.
I will have a separate PR for using LLVM15 as the JIT.

Fixes to compile with clang 15

---

.github/workflows/ci.yml
INSTALL.md
src/build-scripts/install_homebrew_deps.bash
src/cmake/externalpackages.cmake
src/cmake/llvm_macros.cmake
src/liboslexec/llvm_util.cpp

* A variety of changes to get a clean build and passing tests when using LLVM 15.0.
* I've noticed problems when using LLVM 15 but building with earlier clang, so the cmake scripts now print a warning in that case, so if users encounter trouble they have a hint about what to do to fix it.
* For our CI tests on Mac, force the MacOS-11 test to use llvm 14, and the MacOS-12 test to use llvm 15.
IMPORTANT TO-DO / CAVEATS:
1. When doing JIT at optlevel 12 or 13, I had to disable a number of passes that don't seem to exist anymore in LLVM 15. This is enough to get it working, and to be honest, I don't know if anybody uses these opt levels.  But we need to revisit this, because I don't know if there these are cases where the names of the passes merely changed or that new passes take their place …

LLVM 15.0 support

---

src/testrender/cuda/rend_lib.cu
testsuite/example-cuda/rend_lib.cu

Remove unused cuda variable that was warning

---

.github/workflows/ci.yml
src/build-scripts/install_homebrew_deps.bash

CI: Test against OpenColorIO 2.2

---

.github/workflows/ci.yml

CI: Fix build break by adjusting fmt version

---

testsuite/arithmetic-reg/run.py
testsuite/smoothstep-reg/run.py
testsuite/transcendental-reg/run.py
testsuite/trig-reg/run.py

Typo in test shaders

---

README.md

OSL was not used on Kubo.
Course was part of Educator's Forum.
- [x ] I have previously submitted a [Contributor License Agreement](http://opensource.imageworks.com/cla/).
- [x ] I have updated the documentation, if applicable.
- [ x] I have ensured that the change is tested somewhere in the testsuite (adding new test cases if necessary).
- [ x] My code follows the prevailing code style of this project.

Fixed booboos from the previous README commit.

---

src/liboslexec/wide/wide_shadingsys.cpp

This fixes recently-broken CI.

Fix default fmt logic changing in latest openimageio release

---

.mailmap

Please look this over. If you are one of the duplicated names and I
haven't chosen your preferred canonical email (I made my best guess),
please comment here with corrections.

admin: Account for duplicate emails in the .mailmap

---

src/build-scripts/install_homebrew_deps.bash

Some noodling was necessary to fix recently broken Mac CI.

ci: Fix broken Macos-13 CI

---

src/liboslexec/batched_rendservices.cpp

Didn't catch them all in #1848 -- missed the BatchedRendererServices side.

Adjust to OIIO change to IC/TS API

---

INSTALL.md
src/build-scripts/gh-installdeps.bash
src/cmake/externalpackages.cmake
src/liboslexec/llvm_passes.h
src/liboslexec/llvm_util.cpp

build: Support for LLVM 19

---

README.md

Updated Documentation section with latest Siggraph course and companion repo links. Also added a sentence about the SWinOSL book.
Examined Preview for correctness.

Updated README.md Documentation section.

---

doc/dev/CodeReview.md

Ported from OIIO, with minor changes in some areas that differ between the two projects.

admin: Add code reviewing guide
